## SETUP

In [2]:
import math 
import random 
import numpy as np
import pandas as pd 
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader 
from sqlalchemy import create_engine

## Fetch data from database

In [3]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [4]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, created_at
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)
num_items = pd.read_sql("SELECT COUNT(*) AS num_items FROM products", engine).iloc[0]['num_items']

In [5]:
df['created_at'] = pd.to_datetime(df['created_at'])

In [6]:
interactions_df = df.rename(columns={'product_id':'item_id','created_at':'timestamp'}).sort_values(['user_id','timestamp']).reset_index(drop=True)

In [7]:
interactions_df.head()

   user_id  item_id           timestamp
0      485      258 2026-04-17 18:15:13
1      485      191 2026-04-17 18:15:13
2      485      192 2026-04-17 18:15:13
3      485      201 2026-04-17 18:15:13
4      485      187 2026-04-17 18:15:13

In [8]:
interactions_df.shape

(10019, 3)

## Mapping handling

In [9]:
interactions_df["real_user_id"] = interactions_df["user_id"] 
interactions_df["user_id"] = interactions_df.groupby("user_id").ngroup() + 1 
interactions_df["real_item_id"] = interactions_df["item_id"]
interactions_df["item_id"] = interactions_df.groupby("item_id").ngroup() + 1

In [10]:
interactions_df.head()

   user_id  item_id           timestamp  real_user_id  real_item_id
0        1      221 2026-04-17 18:15:13           485           258
1        1      176 2026-04-17 18:15:13           485           191
2        1      177 2026-04-17 18:15:13           485           192
3        1      185 2026-04-17 18:15:13           485           201
4        1      172 2026-04-17 18:15:13           485           187

In [11]:
user_id_to_index = dict(zip(interactions_df["real_user_id"], interactions_df["user_id"])) 
item_id_to_index = dict(zip(interactions_df["real_item_id"], interactions_df["item_id"])) 
item_index_to_id = dict(zip(interactions_df["item_id"], interactions_df["real_item_id"]))

In [12]:
user_id_to_index[485],item_id_to_index[191],item_index_to_id[221]

(1, 176, 258)

## I. CONSTANT VARIABLES

In [13]:
SEED = 42 
NUM_USERS =  500
NUM_ITEMS = num_items 
NUM_CATEGORIES = 10 
MIN_INTERACTIONS = 10 
MAX_INTERACTIONS = 50 
MAX_SEQ_LEN = 30 
BATCH_SIZE = 64
PAD_ID = 0 
VOCAB_SIZE = NUM_ITEMS + 1

In [14]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

## Turn interactions into sequences

In [15]:
user_sequences = interactions_df.groupby('user_id')['item_id'].apply(list).to_dict()

In [16]:
user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222,
 176]

## Train test split

In [17]:
train_user_sequences = {}
test_user_sequences = [] 

for user_id, sequence in user_sequences.items(): 
    if len(sequence) < 2 : continue 

    train_sequence = sequence[:-1] 
    target_item = sequence[-1] 

    train_user_sequences[user_id] = train_sequence 

    test_user_sequences.append({
        "user_id": user_id, 
        "input_sequence": train_sequence, 
        "target_item": target_item
    })

In [18]:
train_user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222]

## Create Training Samples FOR SASRec

In [19]:
training_samples = [] 

for user_id, sequence in train_user_sequences.items(): 
    for target_index in range(1,len(sequence)): 
        input_sequence = sequence[:target_index] 
        target_item = sequence[target_index] 

        if len(input_sequence) > MAX_SEQ_LEN:
            input_sequence = input_sequence[-MAX_SEQ_LEN:] 
        
        training_samples.append({
            "user_id": user_id, 
            "input_sequence": input_sequence,
            "target_item": target_item
        })
samples_df = pd.DataFrame(training_samples)

In [20]:
samples_df.head()

   user_id             input_sequence  target_item
0        1                      [221]          176
1        1                 [221, 176]          177
2        1            [221, 176, 177]          185
3        1       [221, 176, 177, 185]          172
4        1  [221, 176, 177, 185, 172]          194

In [21]:
training_samples[0]

{'user_id': 1, 'input_sequence': [221], 'target_item': 176}

## Create Custom Pytorch Dataset

In [22]:
class ComiRecDataset(Dataset): 
    def __init__(self,samples,max_seq_len,pad_id = 0):
        self.samples = samples 
        self.max_seq_len = max_seq_len 
        self.pad_id = pad_id 
    def __len__(self):
        return len(self.samples)
    def __getitem__(self,index):
        sample = self.samples[index] 

        input_sequence = sample['input_sequence'] 
        target_item = sample['target_item'] 

        if len(input_sequence) > self.max_seq_len: 
            input_sequence = input_sequence[-self.max_seq_len:]

        padding_length = self.max_seq_len - len(input_sequence) 
        padded_sequence = [self.pad_id] * padding_length + input_sequence 

        input_tensor = torch.tensor(padded_sequence,dtype=torch.long)
        target_tensor = torch.tensor(target_item,dtype=torch.long)

        return input_tensor, target_tensor

In [23]:
train_dataset = ComiRecDataset(training_samples,MAX_SEQ_LEN,PAD_ID)

In [24]:
train_dataset[0]

(tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0, 221]),
 tensor(176))

## Create Dataloader

In [25]:
train_loader = DataLoader(train_dataset,batch_size=BATCH_SIZE,shuffle=True)

In [26]:
input_batch,target_batch = next(iter(train_loader))
print("Input batch shape:",input_batch.shape)
print("Target batch shape:",target_batch.shape)
print("Input first item in batch example:\n",input_batch[0])
print("Target first item in batch example:\n",target_batch[0])

Input batch shape: torch.Size([64, 30])
Target batch shape: torch.Size([64])
Input first item in batch example:
 tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38, 196,
        185, 188,  44, 222,  80, 220,  44, 195, 171, 195, 226, 178, 221, 186,
         21,  40])
Target first item in batch example:
 tensor(198)

## Create Multi-Interest Extractor For ComiRecSA

### Dim Notations: 
#### D => Embedding Dim 
#### hD => Hidden Dim 
#### B => Batch size 
#### K => Number of Interest 
#### L => Sequence Length 
#### Padding => [B,L] 
#### V => [B,K,D]
#### A => [B,K,L]
#### H => [B,L,D]

In [27]:
class MultiInterestExtractorSA(nn.Module): 
    def __init__(self,embedding_dim,hidden_dim,num_interests,dropout_rate=0.2): 
        super().__init__()
        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.num_interests = num_interests

        self.W1 = nn.Linear(embedding_dim, hidden_dim, bias=False) # D => hD 
        self.W2 = nn.Linear(hidden_dim,num_interests, bias=False) # hD => K

        self.dropout = nn.Dropout(dropout_rate)
    def forward(self,H,padding_mask=None): 
        hidden = torch.tanh(self.W1(H)) #[B,L,hD]
        hidden = self.dropout(hidden) 

        hidden = self.W2(hidden) #[B,L,K] 
        hidden = hidden.transpose(1,2) #[B,K,L] 

        if padding_mask is not None: 
            padding_mask = padding_mask.unsqueeze(1) #[B,1,L] <= [B,L] 
            padding_mask = padding_mask.expand(-1,self.num_interests,-1) #[B,K,L] <= [B,1,L]
            hidden = hidden.masked_fill(padding_mask,float("-inf")) 
        
        A = F.softmax(hidden,dim=-1) #[B,K,L]
        
        V = torch.bmm(A,H) # [B,K,D] <= [B,K,L] * [B,L,D] 
        return V,A

## Create class ComiRecSAModel

In [28]:
class ComiRecSAModel(nn.Module): 
    def __init__(self,num_items,max_seq_len,embedding_dim,hidden_dim,num_interests,dropout_rate=0.2,pad_id=0): 
        super().__init__()
        self.num_items = num_items 
        self.max_seq_len = max_seq_len 
        self.embedding_dim = embedding_dim 
        self.hidden_dim = hidden_dim 
        self.num_interests = num_interests 
        self.pad_id = pad_id 
        self.vocab_size = num_items + 1 

        self.item_embedding = nn.Embedding(
            num_embeddings = self.vocab_size,
            embedding_dim = self.embedding_dim,
            padding_idx = self.pad_id
        )

        self.positional_embedding = nn.Embedding(
            num_embeddings = self.max_seq_len,
            embedding_dim = self.embedding_dim
        )

        self.dropout = nn.Dropout(dropout_rate) 
        self.layer_norm = nn.LayerNorm(self.embedding_dim) 

        self.interest_extractor = MultiInterestExtractorSA(
            embedding_dim = self.embedding_dim,
            hidden_dim = self.hidden_dim,
            num_interests = self.num_interests,
            dropout_rate = dropout_rate
        )
    def forward(self,input_sequences):
        # Input: input_sequences [B,L]
        device = input_sequences.device
        batch_size, seq_len = input_sequences.size() 

        positions = torch.arange(seq_len, device = device)  #[L]
        positions = positions.unsqueeze(0) # [1,L] <= [L]
        positions = positions.expand(batch_size,-1) #[B,L] <= [1,L] 

        item_emb = self.item_embedding(input_sequences) #[B,L,D]
        pos_emb = self.positional_embedding(positions) #[B,L,D] 

        H = item_emb + pos_emb #[B,L,D]
        H = self.dropout(H)
        H = self.layer_norm(H) #[B,L,D] 

        padding_mask = input_sequences.eq(self.pad_id) #[B,L] 
        V,A = self.interest_extractor(H,padding_mask) #[B,K,D],[B,K,L]
        
        return V,A
    def compute_loss(self, input_sequences, target_items):  
        # Input: input_sequences [B,L], target_items [B]
        V, A = self.forward(input_sequences) #[B,K,D],[B,K,L] 
        target_emb = self.item_embedding(target_items) #[B,D]

        # 1. Compute the dot product between target_emb and each interest vector in V
        target_emb = target_emb.unsqueeze(1) #[B,1,D] <= [B,D]
        target_emb = target_emb.expand(-1,self.num_interests,-1) #[B,K,D] <= [B,1,D]
        interest_scores = torch.sum(V * target_emb, dim=-1) #[B,K] <= sum([B,K,D] * [B,K,D], dim=-1)

        # 2. Select the best interest vector that has the highest score for each sample/user 
        best_interest_idx = torch.argmax(interest_scores, dim=-1) #[B] <= argmax([B,K], dim=-1)
        batch_indices = torch.arange(V.size(0), device=V.device) #[B] 
        best_interest = V[batch_indices,best_interest_idx,:] #[B,D] <= V[[B],[B],:] 

        # 3. Compute the loss by dot product between best_interest and all item embeddings
        all_item_emb = self.item_embedding.weight #[num_items+1,D] 
        all_item_emb = all_item_emb.T #[D,num_items+1]
        logits = best_interest @ all_item_emb #[B,num_items+1] <= [B,D] @ [D,num_items+1] 
        logits[:,self.pad_id] = float("-inf")  # Mask the padding index
        loss = F.cross_entropy(logits, target_items) # scalar <= cross_entropy([B,num_items+1],[B])

        return loss

## II. CONSTANT VARIABLES FOR TRAINING

In [29]:
EMBEDDING_DIM = 128
DROPOUT_RATE = 0.2
NUM_EPOCHS = 300
HIDDEN_DIM = EMBEDDING_DIM*2
NUM_INTERESTS = 3

## Initialize ComiRec Model

In [30]:
model = ComiRecSAModel(
    num_items = NUM_ITEMS,
    max_seq_len = MAX_SEQ_LEN,
    embedding_dim = EMBEDDING_DIM,
    hidden_dim = HIDDEN_DIM,
    num_interests = NUM_INTERESTS,
    dropout_rate = DROPOUT_RATE,
    pad_id = PAD_ID
)

## Test Forward with 1 Batch

In [31]:
V, A = model(input_batch) #[B,K,D],[B,K,L]
print("Interest vectors shape:",V.shape)
print("Attention weights shape:",A.shape)
print("Interest vectors example:\n",V[0])
print("Attention weights example:\n",A[0])

Interest vectors shape: torch.Size([64, 3, 128])
Attention weights shape: torch.Size([64, 3, 30])
Interest vectors example:
 tensor([[-5.3056e-01,  1.9496e-01, -7.8935e-02,  8.5127e-02,  1.7268e-01,
         -6.8108e-02, -1.6613e-01,  1.2947e-01, -4.1811e-01,  4.2776e-02,
          3.2903e-01,  2.7894e-01, -1.9879e-01, -1.7641e-01,  1.3435e-01,
          4.0774e-02,  6.8662e-01,  3.7144e-01, -2.9711e-02, -6.8181e-02,
         -6.2264e-02,  2.3498e-04,  1.9874e-01, -1.4841e-01,  1.5710e-01,
          3.0733e-01, -1.6231e-01,  3.5484e-01, -2.4327e-01, -4.2781e-01,
         -4.4450e-02,  3.5469e-01,  6.6398e-01, -5.0432e-01,  2.4624e-01,
         -1.0799e-01, -5.9004e-02, -1.5309e-01,  1.3059e-01, -3.0737e-01,
         -1.2732e-01,  1.3286e-01,  2.1565e-02, -1.5609e-01,  2.4561e-01,
          2.6905e-01, -1.9292e-01, -5.9596e-02, -1.4783e-01, -2.7007e-01,
         -3.1849e-01, -1.8112e-01,  2.9675e-01,  4.3782e-01, -2.0738e-02,
         -2.2180e-01,  1.3183e-01, -5.1481e-01, -1.4137e-01, -1.3397e-01,
         -1.2909e-01,  8.0275e-02, -1.6696e-01,  3.4059e-01, -1.0961e-01,
          1.7633e-01,  3.6496e-01,  2.9782e-01,  1.5053e-01, -4.3823e-01,
          5.5220e-01,  3.1375e-01, -1.8553e-01,  4.3108e-02,  4.1285e-01,
          3.9237e-01, -2.4721e-01,  2.5643e-01, -2.0992e-01, -2.7492e-01,
          5.4521e-02, -1.8892e-01, -1.9534e-01,  4.0232e-01, -1.0901e-01,
          2.1624e-02,  1.2504e-01, -2.8839e-01,  5.3368e-01, -3.9345e-01,
          4.7410e-02,  2.8544e-01,  2.2456e-01,  3.2944e-01,  4.1697e-01,
         -2.8815e-02,  1.9857e-01, -1.6506e-01,  1.9587e-01, -1.7074e-01,
          1.0013e-01, -1.3184e-01, -3.1454e-01,  1.4806e-01, -3.5803e-02,
          4.1849e-01,  6.9160e-02, -2.4750e-01, -3.3961e-01, -1.4604e-01,
          8.1947e-02,  1.6951e-01, -1.7826e-01,  8.7903e-03, -7.1557e-01,
         -2.7342e-01, -1.6914e-01, -5.6802e-02, -3.9645e-01,  1.1138e-01,
          3.1526e-01,  4.1276e-01, -3.8239e-01,  3.2184e-04, -2.6392e-01,
         -1.9508e-01, -5.2026e-01, -3.5871e-01],
        [-3.7846e-01,  1.7278e-01,  8.8665e-02, -3.1475e-02,  2.9967e-01,
         -2.4110e-01, -3.3293e-01,  8.8863e-02, -3.7609e-01,  2.6170e-02,
          2.6734e-01,  3.2796e-01, -2.6258e-01, -3.1072e-01,  1.4628e-02,
          1.4015e-01,  1.6083e-01,  2.8384e-01,  1.8264e-04,  7.6945e-02,
         -2.2462e-01,  1.6285e-01,  1.2101e-01, -5.9427e-02,  1.4960e-01,
          2.6088e-01, -2.2036e-01,  4.5448e-01, -2.0454e-01, -4.9729e-01,
          8.7761e-02,  2.7449e-01,  3.9483e-01, -2.1086e-01,  3.9819e-01,
         -2.6065e-01,  8.7317e-02, -6.2428e-02,  2.2907e-01, -3.0713e-01,
         -4.7880e-02, -2.0853e-02,  8.5079e-02, -3.2625e-02,  3.2761e-01,
          2.6459e-01, -3.4254e-01,  4.9726e-02, -2.3275e-01, -6.5875e-02,
         -2.2547e-01, -1.4111e-01,  4.1458e-01,  4.0499e-01,  6.8083e-02,
         -5.9935e-02, -5.8148e-03, -3.2680e-01, -3.0308e-01, -2.6918e-01,
         -2.3961e-01, -9.6560e-03, -1.1272e-01,  1.9354e-01, -1.5266e-01,
         -7.6025e-03,  4.5849e-01,  2.3140e-01,  1.7788e-01, -3.7810e-01,
          2.1178e-01,  1.1768e-01, -1.1109e-01, -2.0340e-02,  6.2666e-01,
          2.8928e-01, -2.9963e-01,  3.8462e-01, -5.8968e-02, -3.7623e-01,
         -1.3214e-03, -7.3705e-02, -1.6914e-01,  2.1673e-01, -5.8798e-02,
          2.1726e-01,  1.1148e-01, -4.6173e-01,  2.3558e-01, -2.3963e-01,
         -9.6221e-03,  2.7390e-01,  1.3282e-01,  2.8805e-01,  2.7803e-01,
          1.7769e-01,  3.3719e-01, -1.4998e-01,  1.7210e-01, -1.8714e-01,
          1.8393e-01, -6.6151e-02, -4.2447e-01,  1.9954e-01,  2.5236e-01,
          2.4460e-01,  1.6802e-01, -2.7054e-01, -1.6826e-01, -3.4148e-02,
          2.3093e-01,  1.1113e-01, -1.3564e-01, -1.9479e-01, -6.2838e-01,
         -7.0825e-02, -2.4817e-01, -4.7771e-02, -4.0289e-01, -1.1783e-02,
          5.1330e-01,  2.4517e-01, -3.0002e-01,  3.3056e-02, -2.2398e-01,
         -1.5014e-01, -5.6972e-01, -3.7746e-01],
        [-4.7458e-01,  3.1115e-01,  2.4638e-02,  1.1127e-01,  4.7831e-01,
         -1.8787e-01, -3.0166e-02,  7.0953e-03, -4.7812e-01,  4.8405e-02,
          1.0803e-01,  2.8953e-01, -3.7610e-01, -2.5999e-01,  1.8934e-02,
          1.4287e-01,  2.5881e-01,  2.9576e-01, -1.1764e-02,  4.5104e-02,
         -2.7209e-01,  1.4335e-01,  6.0434e-02, -2.6831e-02,  1.7329e-01,
          2.2857e-01, -2.1219e-01,  3.0382e-01, -2.1212e-01, -4.5234e-01,
         -1.2817e-01,  2.5414e-01,  4.7241e-01, -3.2114e-01,  5.6354e-01,
         -2.0574e-01,  1.3387e-02, -1.2868e-01,  1.5070e-01, -3.5645e-01,
         -3.0787e-01,  8.5313e-03,  1.8114e-02, -1.0322e-01,  3.0608e-01,
          7.2269e-02, -1.8205e-01,  3.8670e-01, -1.7645e-01, -8.7635e-02,
         -3.5520e-01, -5.1856e-02,  2.9028e-01,  4.7565e-01,  1.1586e-01,
         -5.6919e-04,  1.1186e-01, -2.8471e-01, -1.4110e-01, -3.2407e-01,
         -1.8223e-01,  2.3454e-02,  4.3828e-02,  2.6790e-01, -1.3852e-01,
          1.2215e-01,  2.9868e-01,  3.3308e-01,  1.9855e-01, -4.5750e-01,
          5.2323e-01,  2.7024e-01, -1.5690e-01, -5.1117e-02,  3.5152e-01,
          1.9309e-01, -3.5457e-01,  3.3174e-01, -1.2922e-01, -2.7988e-01,
          2.1424e-03,  1.0789e-01,  6.9853e-02,  2.1897e-01, -1.0749e-01,
          1.4603e-01,  1.7094e-01, -4.9793e-01,  2.6164e-01, -2.3538e-01,
          8.2615e-02,  2.6819e-01,  2.9387e-01,  4.2353e-01,  3.4958e-01,
          1.3611e-01,  1.3433e-01, -6.4162e-02,  4.7394e-02, -1.3833e-01,
          2.0985e-01, -3.1332e-01, -5.3732e-01,  1.5001e-01,  2.0993e-01,
          2.7505e-01,  2.1884e-01, -1.7127e-01, -3.1992e-01, -2.7156e-01,
          1.5231e-01, -1.1206e-01, -1.0337e-01, -3.2999e-02, -6.3649e-01,
         -7.5632e-02, -1.1057e-01, -9.4854e-02, -3.4647e-01,  1.6524e-01,
          4.8218e-01,  2.9208e-01, -4.3328e-01, -6.9586e-02, -2.0162e-01,
         -4.2844e-01, -5.0205e-01, -4.1184e-01]], grad_fn=<SelectBackward0>)
Attention weights example:
 tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0694, 0.0391, 0.0521, 0.0474, 0.0408, 0.0758,
         0.0482, 0.0617, 0.0822, 0.0574, 0.0367, 0.0738, 0.0971, 0.0324, 0.0419,
         0.0693, 0.0283, 0.0465],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0417, 0.0599, 0.1090, 0.0571, 0.0447, 0.0476,
         0.0756, 0.0787, 0.0573, 0.0287, 0.0634, 0.0387, 0.0461, 0.0410, 0.0323,
         0.0549, 0.0507, 0.0726],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0714, 0.0631, 0.0606, 0.0458, 0.0759, 0.0482,
         0.0642, 0.0664, 0.0444, 0.0337, 0.0455, 0.0611, 0.0361, 0.0698, 0.0984,
         0.0263, 0.0390, 0.0501]], grad_fn=<SelectBackward0>)

In [32]:
loss = model.compute_loss(input_batch,target_batch) 
print("Loss:",loss.item())

Loss: 20.340402603149414

## Create Training Loop for Comirec

In [33]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu") 
model = model.to(device)

In [34]:
device

device(type='mps')

In [35]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001,weight_decay=1e-6)

In [36]:
for epoch in range(NUM_EPOCHS+200):
    model.train() 
    total_loss = 0.0 
    total_batches = 0 

    for input_batch, target_batch in train_loader:
        input_batch = input_batch.to(device) 
        target_batch = target_batch.to(device) 

        # --------- Training step -----------
        # 1. Feed Forward + 2. Compute Loss 
        loss = model.compute_loss(input_batch,target_batch)

        # 3. Reset gradients 
        optimizer.zero_grad() 

        # 4. Feed Backward
        loss.backward() 

        # 5. Update parameters
        optimizer.step() 
        # ---------- Training step ----------

        # Accumulate loss for monitoring
        total_loss += loss.item() 
        total_batches += 1
    avg_loss = total_loss / total_batches
    print(f"Epoch [{epoch+1}/{NUM_EPOCHS}], Average Loss: {avg_loss:.4f}")

Epoch [1/300], Average Loss: 18.9496
Epoch [2/300], Average Loss: 15.4975
Epoch [3/300], Average Loss: 12.7254
Epoch [4/300], Average Loss: 10.5771
Epoch [5/300], Average Loss: 8.8115
Epoch [6/300], Average Loss: 7.4421
Epoch [7/300], Average Loss: 6.4721
Epoch [8/300], Average Loss: 5.7850
Epoch [9/300], Average Loss: 5.3675
Epoch [10/300], Average Loss: 5.0887
Epoch [11/300], Average Loss: 4.8948
Epoch [12/300], Average Loss: 4.7661
Epoch [13/300], Average Loss: 4.6713
Epoch [14/300], Average Loss: 4.5737
Epoch [15/300], Average Loss: 4.5067
Epoch [16/300], Average Loss: 4.4286
Epoch [17/300], Average Loss: 4.3562
Epoch [18/300], Average Loss: 4.2904
Epoch [19/300], Average Loss: 4.2131
Epoch [20/300], Average Loss: 4.1372
Epoch [21/300], Average Loss: 4.0727
Epoch [22/300], Average Loss: 3.9981
Epoch [23/300], Average Loss: 3.9335
Epoch [24/300], Average Loss: 3.8714
Epoch [25/300], Average Loss: 3.8209
Epoch [26/300], Average Loss: 3.7667
Epoch [27/300], Average Loss: 3.7230
Epoch [28/300], Average Loss: 3.6831
Epoch [29/300], Average Loss: 3.6383
Epoch [30/300], Average Loss: 3.6027
Epoch [31/300], Average Loss: 3.5647
Epoch [32/300], Average Loss: 3.5500
Epoch [33/300], Average Loss: 3.5252
Epoch [34/300], Average Loss: 3.4834
Epoch [35/300], Average Loss: 3.4543
Epoch [36/300], Average Loss: 3.4445
Epoch [37/300], Average Loss: 3.4153
Epoch [38/300], Average Loss: 3.3845
Epoch [39/300], Average Loss: 3.3720
Epoch [40/300], Average Loss: 3.3487
Epoch [41/300], Average Loss: 3.3327
Epoch [42/300], Average Loss: 3.3129
Epoch [43/300], Average Loss: 3.3077
Epoch [44/300], Average Loss: 3.2889
Epoch [45/300], Average Loss: 3.2693
Epoch [46/300], Average Loss: 3.2734
Epoch [47/300], Average Loss: 3.2650
Epoch [48/300], Average Loss: 3.2391
Epoch [49/300], Average Loss: 3.2227
Epoch [50/300], Average Loss: 3.2196
Epoch [51/300], Average Loss: 3.1964
Epoch [52/300], Average Loss: 3.2000
Epoch [53/300], Average Loss: 3.1965
Epoch [54/300], Average Loss: 3.1731
Epoch [55/300], Average Loss: 3.1603
Epoch [56/300], Average Loss: 3.1607
Epoch [57/300], Average Loss: 3.1439
Epoch [58/300], Average Loss: 3.1271
Epoch [59/300], Average Loss: 3.1448
Epoch [60/300], Average Loss: 3.1119
Epoch [61/300], Average Loss: 3.1164
Epoch [62/300], Average Loss: 3.1134
Epoch [63/300], Average Loss: 3.0929
Epoch [64/300], Average Loss: 3.0852
Epoch [65/300], Average Loss: 3.0758
Epoch [66/300], Average Loss: 3.0723
Epoch [67/300], Average Loss: 3.0653
Epoch [68/300], Average Loss: 3.0585
Epoch [69/300], Average Loss: 3.0563
Epoch [70/300], Average Loss: 3.0441
Epoch [71/300], Average Loss: 3.0469
Epoch [72/300], Average Loss: 3.0259
Epoch [73/300], Average Loss: 3.0291
Epoch [74/300], Average Loss: 3.0309
Epoch [75/300], Average Loss: 3.0112
Epoch [76/300], Average Loss: 3.0073
Epoch [77/300], Average Loss: 2.9926
Epoch [78/300], Average Loss: 3.0011
Epoch [79/300], Average Loss: 3.0007
Epoch [80/300], Average Loss: 2.9855
Epoch [81/300], Average Loss: 2.9855
Epoch [82/300], Average Loss: 2.9834
Epoch [83/300], Average Loss: 2.9731
Epoch [84/300], Average Loss: 2.9800
Epoch [85/300], Average Loss: 2.9597
Epoch [86/300], Average Loss: 2.9596
Epoch [87/300], Average Loss: 2.9576
Epoch [88/300], Average Loss: 2.9584
Epoch [89/300], Average Loss: 2.9587
Epoch [90/300], Average Loss: 2.9514
Epoch [91/300], Average Loss: 2.9264
Epoch [92/300], Average Loss: 2.9306
Epoch [93/300], Average Loss: 2.9260
Epoch [94/300], Average Loss: 2.9250
Epoch [95/300], Average Loss: 2.9297
Epoch [96/300], Average Loss: 2.9218
Epoch [97/300], Average Loss: 2.9192
Epoch [98/300], Average Loss: 2.9223
Epoch [99/300], Average Loss: 2.9120
Epoch [100/300], Average Loss: 2.9005
Epoch [101/300], Average Loss: 2.8994
Epoch [102/300], Average Loss: 2.9033
Epoch [103/300], Average Loss: 2.8845
Epoch [104/300], Average Loss: 2.8955
Epoch [105/300], Average Loss: 2.8893
Epoch [106/300], Average Loss: 2.8806
Epoch [107/300], Average Loss: 2.8820
Epoch [108/300], Average Loss: 2.8838
Epoch [109/300], Average Loss: 2.8803
Epoch [110/300], Average Loss: 2.8717
Epoch [111/300], Average Loss: 2.8769
Epoch [112/300], Average Loss: 2.8574
Epoch [113/300], Average Loss: 2.8583
Epoch [114/300], Average Loss: 2.8646
Epoch [115/300], Average Loss: 2.8450
Epoch [116/300], Average Loss: 2.8392
Epoch [117/300], Average Loss: 2.8515
Epoch [118/300], Average Loss: 2.8416
Epoch [119/300], Average Loss: 2.8493
Epoch [120/300], Average Loss: 2.8400
Epoch [121/300], Average Loss: 2.8440
Epoch [122/300], Average Loss: 2.8455
Epoch [123/300], Average Loss: 2.8347
Epoch [124/300], Average Loss: 2.8265
Epoch [125/300], Average Loss: 2.8263
Epoch [126/300], Average Loss: 2.8277
Epoch [127/300], Average Loss: 2.8258
Epoch [128/300], Average Loss: 2.8063
Epoch [129/300], Average Loss: 2.8118
Epoch [130/300], Average Loss: 2.8075
Epoch [131/300], Average Loss: 2.8110
Epoch [132/300], Average Loss: 2.7993
Epoch [133/300], Average Loss: 2.8165
Epoch [134/300], Average Loss: 2.8068
Epoch [135/300], Average Loss: 2.8009
Epoch [136/300], Average Loss: 2.7931
Epoch [137/300], Average Loss: 2.7979
Epoch [138/300], Average Loss: 2.7900
Epoch [139/300], Average Loss: 2.7871
Epoch [140/300], Average Loss: 2.7686
Epoch [141/300], Average Loss: 2.7802
Epoch [142/300], Average Loss: 2.7919
Epoch [143/300], Average Loss: 2.7702
Epoch [144/300], Average Loss: 2.7781
Epoch [145/300], Average Loss: 2.7681
Epoch [146/300], Average Loss: 2.7820
Epoch [147/300], Average Loss: 2.7710
Epoch [148/300], Average Loss: 2.7835
Epoch [149/300], Average Loss: 2.7680
Epoch [150/300], Average Loss: 2.7618
Epoch [151/300], Average Loss: 2.7598
Epoch [152/300], Average Loss: 2.7635
Epoch [153/300], Average Loss: 2.7591
Epoch [154/300], Average Loss: 2.7528
Epoch [155/300], Average Loss: 2.7469
Epoch [156/300], Average Loss: 2.7480
Epoch [157/300], Average Loss: 2.7402
Epoch [158/300], Average Loss: 2.7424
Epoch [159/300], Average Loss: 2.7390
Epoch [160/300], Average Loss: 2.7438
Epoch [161/300], Average Loss: 2.7284
Epoch [162/300], Average Loss: 2.7491
Epoch [163/300], Average Loss: 2.7279
Epoch [164/300], Average Loss: 2.7313
Epoch [165/300], Average Loss: 2.7299
Epoch [166/300], Average Loss: 2.7372
Epoch [167/300], Average Loss: 2.7278
Epoch [168/300], Average Loss: 2.7254
Epoch [169/300], Average Loss: 2.7205
Epoch [170/300], Average Loss: 2.7226
Epoch [171/300], Average Loss: 2.7123
Epoch [172/300], Average Loss: 2.7288
Epoch [173/300], Average Loss: 2.7138
Epoch [174/300], Average Loss: 2.7073
Epoch [175/300], Average Loss: 2.7123
Epoch [176/300], Average Loss: 2.7096
Epoch [177/300], Average Loss: 2.7084
Epoch [178/300], Average Loss: 2.7030
Epoch [179/300], Average Loss: 2.7119
Epoch [180/300], Average Loss: 2.7040
Epoch [181/300], Average Loss: 2.6937
Epoch [182/300], Average Loss: 2.7028
Epoch [183/300], Average Loss: 2.6980
Epoch [184/300], Average Loss: 2.6986
Epoch [185/300], Average Loss: 2.6878
Epoch [186/300], Average Loss: 2.6852
Epoch [187/300], Average Loss: 2.6809
Epoch [188/300], Average Loss: 2.6806
Epoch [189/300], Average Loss: 2.6764
Epoch [190/300], Average Loss: 2.6797
Epoch [191/300], Average Loss: 2.6767
Epoch [192/300], Average Loss: 2.6781
Epoch [193/300], Average Loss: 2.6829
Epoch [194/300], Average Loss: 2.6740
Epoch [195/300], Average Loss: 2.6715
Epoch [196/300], Average Loss: 2.6623
Epoch [197/300], Average Loss: 2.6594
Epoch [198/300], Average Loss: 2.6596
Epoch [199/300], Average Loss: 2.6474
Epoch [200/300], Average Loss: 2.6750
Epoch [201/300], Average Loss: 2.6639
Epoch [202/300], Average Loss: 2.6552
Epoch [203/300], Average Loss: 2.6544
Epoch [204/300], Average Loss: 2.6553
Epoch [205/300], Average Loss: 2.6572
Epoch [206/300], Average Loss: 2.6527
Epoch [207/300], Average Loss: 2.6638
Epoch [208/300], Average Loss: 2.6500
Epoch [209/300], Average Loss: 2.6399
Epoch [210/300], Average Loss: 2.6458
Epoch [211/300], Average Loss: 2.6440
Epoch [212/300], Average Loss: 2.6399
Epoch [213/300], Average Loss: 2.6411
Epoch [214/300], Average Loss: 2.6475
Epoch [215/300], Average Loss: 2.6260
Epoch [216/300], Average Loss: 2.6303
Epoch [217/300], Average Loss: 2.6459
Epoch [218/300], Average Loss: 2.6277
Epoch [219/300], Average Loss: 2.6362
Epoch [220/300], Average Loss: 2.6260
Epoch [221/300], Average Loss: 2.6169
Epoch [222/300], Average Loss: 2.6354
Epoch [223/300], Average Loss: 2.6272
Epoch [224/300], Average Loss: 2.6308
Epoch [225/300], Average Loss: 2.6087
Epoch [226/300], Average Loss: 2.6162
Epoch [227/300], Average Loss: 2.6326
Epoch [228/300], Average Loss: 2.6321
Epoch [229/300], Average Loss: 2.6339
Epoch [230/300], Average Loss: 2.6093
Epoch [231/300], Average Loss: 2.6187
Epoch [232/300], Average Loss: 2.6241
Epoch [233/300], Average Loss: 2.6087
Epoch [234/300], Average Loss: 2.6236
Epoch [235/300], Average Loss: 2.6078
Epoch [236/300], Average Loss: 2.6154
Epoch [237/300], Average Loss: 2.6124
Epoch [238/300], Average Loss: 2.5942
Epoch [239/300], Average Loss: 2.6163
Epoch [240/300], Average Loss: 2.6103
Epoch [241/300], Average Loss: 2.6144
Epoch [242/300], Average Loss: 2.6049
Epoch [243/300], Average Loss: 2.5990
Epoch [244/300], Average Loss: 2.6076
Epoch [245/300], Average Loss: 2.5962
Epoch [246/300], Average Loss: 2.5948
Epoch [247/300], Average Loss: 2.5892
Epoch [248/300], Average Loss: 2.5939
Epoch [249/300], Average Loss: 2.5938
Epoch [250/300], Average Loss: 2.5813
Epoch [251/300], Average Loss: 2.5885
Epoch [252/300], Average Loss: 2.6006
Epoch [253/300], Average Loss: 2.6032
Epoch [254/300], Average Loss: 2.6089
Epoch [255/300], Average Loss: 2.5827
Epoch [256/300], Average Loss: 2.5823
Epoch [257/300], Average Loss: 2.5999
Epoch [258/300], Average Loss: 2.5955
Epoch [259/300], Average Loss: 2.5786
Epoch [260/300], Average Loss: 2.5818
Epoch [261/300], Average Loss: 2.5921
Epoch [262/300], Average Loss: 2.5867
Epoch [263/300], Average Loss: 2.5792
Epoch [264/300], Average Loss: 2.5807
Epoch [265/300], Average Loss: 2.5699
Epoch [266/300], Average Loss: 2.5731
Epoch [267/300], Average Loss: 2.5674
Epoch [268/300], Average Loss: 2.5730
Epoch [269/300], Average Loss: 2.5632
Epoch [270/300], Average Loss: 2.5693
Epoch [271/300], Average Loss: 2.5883
Epoch [272/300], Average Loss: 2.5671
Epoch [273/300], Average Loss: 2.5687
Epoch [274/300], Average Loss: 2.5769
Epoch [275/300], Average Loss: 2.5700
Epoch [276/300], Average Loss: 2.5749
Epoch [277/300], Average Loss: 2.5568
Epoch [278/300], Average Loss: 2.5680
Epoch [279/300], Average Loss: 2.5598
Epoch [280/300], Average Loss: 2.5646
Epoch [281/300], Average Loss: 2.5574
Epoch [282/300], Average Loss: 2.5567
Epoch [283/300], Average Loss: 2.5712
Epoch [284/300], Average Loss: 2.5631
Epoch [285/300], Average Loss: 2.5493
Epoch [286/300], Average Loss: 2.5560
Epoch [287/300], Average Loss: 2.5532
Epoch [288/300], Average Loss: 2.5609
Epoch [289/300], Average Loss: 2.5523
Epoch [290/300], Average Loss: 2.5614
Epoch [291/300], Average Loss: 2.5623
Epoch [292/300], Average Loss: 2.5492
Epoch [293/300], Average Loss: 2.5661
Epoch [294/300], Average Loss: 2.5481
Epoch [295/300], Average Loss: 2.5409
Epoch [296/300], Average Loss: 2.5574
Epoch [297/300], Average Loss: 2.5453
Epoch [298/300], Average Loss: 2.5618
Epoch [299/300], Average Loss: 2.5590
Epoch [300/300], Average Loss: 2.5408
Epoch [301/300], Average Loss: 2.5494
Epoch [302/300], Average Loss: 2.5602
Epoch [303/300], Average Loss: 2.5361
Epoch [304/300], Average Loss: 2.5491
Epoch [305/300], Average Loss: 2.5487
Epoch [306/300], Average Loss: 2.5449
Epoch [307/300], Average Loss: 2.5309
Epoch [308/300], Average Loss: 2.5414
Epoch [309/300], Average Loss: 2.5503
Epoch [310/300], Average Loss: 2.5295
Epoch [311/300], Average Loss: 2.5377
Epoch [312/300], Average Loss: 2.5296
Epoch [313/300], Average Loss: 2.5378
Epoch [314/300], Average Loss: 2.5300
Epoch [315/300], Average Loss: 2.5347
Epoch [316/300], Average Loss: 2.5265
Epoch [317/300], Average Loss: 2.5393
Epoch [318/300], Average Loss: 2.5209
Epoch [319/300], Average Loss: 2.5393
Epoch [320/300], Average Loss: 2.5325
Epoch [321/300], Average Loss: 2.5450
Epoch [322/300], Average Loss: 2.5199
Epoch [323/300], Average Loss: 2.5376
Epoch [324/300], Average Loss: 2.5201
Epoch [325/300], Average Loss: 2.5189
Epoch [326/300], Average Loss: 2.5332
Epoch [327/300], Average Loss: 2.5327
Epoch [328/300], Average Loss: 2.5263
Epoch [329/300], Average Loss: 2.5160
Epoch [330/300], Average Loss: 2.5258
Epoch [331/300], Average Loss: 2.5249
Epoch [332/300], Average Loss: 2.5249
Epoch [333/300], Average Loss: 2.5039
Epoch [334/300], Average Loss: 2.5215
Epoch [335/300], Average Loss: 2.5222
Epoch [336/300], Average Loss: 2.5162
Epoch [337/300], Average Loss: 2.5237
Epoch [338/300], Average Loss: 2.5142
Epoch [339/300], Average Loss: 2.5114
Epoch [340/300], Average Loss: 2.5225
Epoch [341/300], Average Loss: 2.5196
Epoch [342/300], Average Loss: 2.5149
Epoch [343/300], Average Loss: 2.5016
Epoch [344/300], Average Loss: 2.5214
Epoch [345/300], Average Loss: 2.5124
Epoch [346/300], Average Loss: 2.5063
Epoch [347/300], Average Loss: 2.5102
Epoch [348/300], Average Loss: 2.5206
Epoch [349/300], Average Loss: 2.5163
Epoch [350/300], Average Loss: 2.5157
Epoch [351/300], Average Loss: 2.5062
Epoch [352/300], Average Loss: 2.5141
Epoch [353/300], Average Loss: 2.4978
Epoch [354/300], Average Loss: 2.4928
Epoch [355/300], Average Loss: 2.4969
Epoch [356/300], Average Loss: 2.5015
Epoch [357/300], Average Loss: 2.5100
Epoch [358/300], Average Loss: 2.4921
Epoch [359/300], Average Loss: 2.5033
Epoch [360/300], Average Loss: 2.4987
Epoch [361/300], Average Loss: 2.5077
Epoch [362/300], Average Loss: 2.5066
Epoch [363/300], Average Loss: 2.4915
Epoch [364/300], Average Loss: 2.4985
Epoch [365/300], Average Loss: 2.4996
Epoch [366/300], Average Loss: 2.4926
Epoch [367/300], Average Loss: 2.4950
Epoch [368/300], Average Loss: 2.5002
Epoch [369/300], Average Loss: 2.5081
Epoch [370/300], Average Loss: 2.5057
Epoch [371/300], Average Loss: 2.4994
Epoch [372/300], Average Loss: 2.4873
Epoch [373/300], Average Loss: 2.4811
Epoch [374/300], Average Loss: 2.4981
Epoch [375/300], Average Loss: 2.4996
Epoch [376/300], Average Loss: 2.4797
Epoch [377/300], Average Loss: 2.4881
Epoch [378/300], Average Loss: 2.4852
Epoch [379/300], Average Loss: 2.4852
Epoch [380/300], Average Loss: 2.4836
Epoch [381/300], Average Loss: 2.4891
Epoch [382/300], Average Loss: 2.5002
Epoch [383/300], Average Loss: 2.4953
Epoch [384/300], Average Loss: 2.4704
Epoch [385/300], Average Loss: 2.4855
Epoch [386/300], Average Loss: 2.4844
Epoch [387/300], Average Loss: 2.4826
Epoch [388/300], Average Loss: 2.4878
Epoch [389/300], Average Loss: 2.4875
Epoch [390/300], Average Loss: 2.4609
Epoch [391/300], Average Loss: 2.4834
Epoch [392/300], Average Loss: 2.4670
Epoch [393/300], Average Loss: 2.4765
Epoch [394/300], Average Loss: 2.4818
Epoch [395/300], Average Loss: 2.4646
Epoch [396/300], Average Loss: 2.4686
Epoch [397/300], Average Loss: 2.4719
Epoch [398/300], Average Loss: 2.4730
Epoch [399/300], Average Loss: 2.4844
Epoch [400/300], Average Loss: 2.4863
Epoch [401/300], Average Loss: 2.4802
Epoch [402/300], Average Loss: 2.4779
Epoch [403/300], Average Loss: 2.4715
Epoch [404/300], Average Loss: 2.4696
Epoch [405/300], Average Loss: 2.4742
Epoch [406/300], Average Loss: 2.4785
Epoch [407/300], Average Loss: 2.4686
Epoch [408/300], Average Loss: 2.4712
Epoch [409/300], Average Loss: 2.4671
Epoch [410/300], Average Loss: 2.4613
Epoch [411/300], Average Loss: 2.4664
Epoch [412/300], Average Loss: 2.4736
Epoch [413/300], Average Loss: 2.4774
Epoch [414/300], Average Loss: 2.4655
Epoch [415/300], Average Loss: 2.4692
Epoch [416/300], Average Loss: 2.4775
Epoch [417/300], Average Loss: 2.4621
Epoch [418/300], Average Loss: 2.4632
Epoch [419/300], Average Loss: 2.4677
Epoch [420/300], Average Loss: 2.4761
Epoch [421/300], Average Loss: 2.4785
Epoch [422/300], Average Loss: 2.4780
Epoch [423/300], Average Loss: 2.4695
Epoch [424/300], Average Loss: 2.4746
Epoch [425/300], Average Loss: 2.4652
Epoch [426/300], Average Loss: 2.4656
Epoch [427/300], Average Loss: 2.4642
Epoch [428/300], Average Loss: 2.4580
Epoch [429/300], Average Loss: 2.4680
Epoch [430/300], Average Loss: 2.4616
Epoch [431/300], Average Loss: 2.4613
Epoch [432/300], Average Loss: 2.4558
Epoch [433/300], Average Loss: 2.4690
Epoch [434/300], Average Loss: 2.4650
Epoch [435/300], Average Loss: 2.4711
Epoch [436/300], Average Loss: 2.4586
Epoch [437/300], Average Loss: 2.4672
Epoch [438/300], Average Loss: 2.4528
Epoch [439/300], Average Loss: 2.4586
Epoch [440/300], Average Loss: 2.4733
Epoch [441/300], Average Loss: 2.4613
Epoch [442/300], Average Loss: 2.4541
Epoch [443/300], Average Loss: 2.4590
Epoch [444/300], Average Loss: 2.4647
Epoch [445/300], Average Loss: 2.4634
Epoch [446/300], Average Loss: 2.4742
Epoch [447/300], Average Loss: 2.4714
Epoch [448/300], Average Loss: 2.4543
Epoch [449/300], Average Loss: 2.4613
Epoch [450/300], Average Loss: 2.4493
Epoch [451/300], Average Loss: 2.4647
Epoch [452/300], Average Loss: 2.4424
Epoch [453/300], Average Loss: 2.4592
Epoch [454/300], Average Loss: 2.4427
Epoch [455/300], Average Loss: 2.4549
Epoch [456/300], Average Loss: 2.4618
Epoch [457/300], Average Loss: 2.4523
Epoch [458/300], Average Loss: 2.4492
Epoch [459/300], Average Loss: 2.4649
Epoch [460/300], Average Loss: 2.4370
Epoch [461/300], Average Loss: 2.4537
Epoch [462/300], Average Loss: 2.4476
Epoch [463/300], Average Loss: 2.4514
Epoch [464/300], Average Loss: 2.4548
Epoch [465/300], Average Loss: 2.4621
Epoch [466/300], Average Loss: 2.4611
Epoch [467/300], Average Loss: 2.4431
Epoch [468/300], Average Loss: 2.4451
Epoch [469/300], Average Loss: 2.4570
Epoch [470/300], Average Loss: 2.4496
Epoch [471/300], Average Loss: 2.4388
Epoch [472/300], Average Loss: 2.4416
Epoch [473/300], Average Loss: 2.4496
Epoch [474/300], Average Loss: 2.4495
Epoch [475/300], Average Loss: 2.4479
Epoch [476/300], Average Loss: 2.4320
Epoch [477/300], Average Loss: 2.4311
Epoch [478/300], Average Loss: 2.4559
Epoch [479/300], Average Loss: 2.4363
Epoch [480/300], Average Loss: 2.4436
Epoch [481/300], Average Loss: 2.4466
Epoch [482/300], Average Loss: 2.4552
Epoch [483/300], Average Loss: 2.4343
Epoch [484/300], Average Loss: 2.4313
Epoch [485/300], Average Loss: 2.4468
Epoch [486/300], Average Loss: 2.4377
Epoch [487/300], Average Loss: 2.4286
Epoch [488/300], Average Loss: 2.4542
Epoch [489/300], Average Loss: 2.4401
Epoch [490/300], Average Loss: 2.4495
Epoch [491/300], Average Loss: 2.4443
Epoch [492/300], Average Loss: 2.4394
Epoch [493/300], Average Loss: 2.4389
Epoch [494/300], Average Loss: 2.4402
Epoch [495/300], Average Loss: 2.4397
Epoch [496/300], Average Loss: 2.4273
Epoch [497/300], Average Loss: 2.4410
Epoch [498/300], Average Loss: 2.4456
Epoch [499/300], Average Loss: 2.4322
Epoch [500/300], Average Loss: 2.4369

## Saving Model

In [37]:
# Save model state_dict
torch.save({"model_state_dict": model.state_dict(),
            "pad_id": int(PAD_ID),
            "embedding_dim": int(EMBEDDING_DIM),
            "hidden_dim": int(HIDDEN_DIM),
            "max_seq_len": int(MAX_SEQ_LEN),
            "num_items": int(NUM_ITEMS),
            "num_interests": int(NUM_INTERESTS),
            "dropout_rate": float(DROPOUT_RATE), 
            }, "../models/comirec/comirec_checkpoint.pth")  
# Save mappings
torch.save(user_id_to_index, "../models/comirec/user_id_to_index.pth")
torch.save(item_id_to_index, "../models/comirec/item_id_to_index.pth")
torch.save(item_index_to_id, "../models/comirec/item_index_to_id.pth")

# Save the entire model 
torch.save(model, "../models/comirec/complete_comirec_model.pth")

# ------------------ TESTING ------------------

## Recommend for next items

In [40]:
TOP_K = 50 
def recommend(model, user_sequence, top_k = 10, return_attention = False): 
    model.eval() 

    if len(user_sequence) > MAX_SEQ_LEN: 
        user_sequence = user_sequence[-MAX_SEQ_LEN:] 
    padding_length = MAX_SEQ_LEN - len(user_sequence) 
    padded_sequence = [PAD_ID] * padding_length + user_sequence 

    input_tensor = torch.tensor([padded_sequence],dtype=torch.long).to(device) #[1,L] <= [L]

    with torch.no_grad():
        V, A = model(input_tensor) #[1,K,D],[1,K,L] 

        all_item_emb = model.item_embedding.weight #[num_items+1, D]
        all_item_emb = all_item_emb.T #[D, num_items+1]

        V = V.squeeze(0) #[K,D] <= [1,K,D] 

        scores_by_interest = V @ all_item_emb #[K,num_items+1] <= [K,D] @ [D,num_items+1] 

        final_scores,best_interest_for_item = torch.max(scores_by_interest,dim=0) #[num_items+1] <= max([K,num_items+1],dim=0) 
    final_scores[PAD_ID] = float("-inf")  # Mask the padding index 

    for item_id in user_sequence: 
        final_scores[item_id] = float("-inf")  # Mask already interacted items
    
    top_scores, top_items = torch.topk(final_scores, k=top_k)

    recommended_items = top_items.cpu().numpy().tolist()
    recommended_scores = top_scores.cpu().numpy().tolist()
    if return_attention:
        return recommended_items, recommended_scores, A,padded_sequence
    else:
        return recommended_items, recommended_scores , padded_sequence

In [41]:
index = item_id_to_index[100] 
index2 = item_id_to_index[103]

In [42]:
recommended_items,_,padded_seq = recommend(
    model=model,
    user_sequence=[index,index2],
    top_k=10
) 

recommended_items,padded_seq

([108, 128, 103, 11, 230, 98, 91, 133, 107, 171],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  87,
  90])

## Evaluation

In [43]:
def evaluate_model(model,evaluation_samples,top_k=10): 
    hits = []
    recalls = []
    ndcgs = []

    for sample in evaluation_samples:
        user_sequence = sample['input_sequence'] 
        target_item = sample['target_item'] 

        recommended_items,recommended_scores,_ = recommend(model,user_sequence,top_k=top_k,return_attention=False)

        if target_item in recommended_items: 
            hit = 1 
            recall = 1 
            rank = recommended_items.index(target_item) + 1
            ndcg = 1 / math.log2(rank + 1)
        else:
            hit = 0 
            recall = 0 
            ndcg = 0
        hits.append(hit)
        recalls.append(recall)
        ndcgs.append(ndcg)
    hit_at_k = np.mean(hits)
    recall_at_k = np.mean(recalls)
    ndcg_at_k = np.mean(ndcgs)
    return hit_at_k, recall_at_k, ndcg_at_k,hits, recalls, ndcgs

In [44]:
hit_at_10, recall_at_10, ndcg_at_10, hits, recalls, ndcgs = evaluate_model(model,test_user_sequences,top_k=10)
print(f"Hit@10: {hit_at_10:.4f}, Recall@10: {recall_at_10:.4f}, NDCG@10: {ndcg_at_10:.4f}")

Hit@10: 0.2500, Recall@10: 0.2500, NDCG@10: 0.1198

In [45]:
hits.count(1)

125

In [55]:
user_id_to_index[487], item_id_to_index[6], item_index_to_id[1]

(3, 2, 5)