In [1]:
import joblib
import pandas as pd
import scipy.sparse as sp
from sqlalchemy import create_engine
from implicit.als import AlternatingLeastSquares

In [2]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [3]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, interaction_type
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10019 entries, 0 to 10018
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10019 non-null  int64
 1   product_id        10019 non-null  int64
 2   interaction_type  10019 non-null  str
dtypes: int64(2), str(1)
memory usage: 309.4 KB

In [5]:
interaction_weight = {
    "click": 0.001,
    "wishlist_add": 0.7,
    "cart_add": 1,
    "R5": 2.0,
    "R4": 1.8,
    "R3": 1.6,
    "R2": 1.4,
    "R1": 1.2,
    "R0": 1.0,
}

In [6]:
def preprocess(df):
    user_product = df[["user_id", "product_id"]].copy()

    user_product["score"] = df["interaction_type"].map(interaction_weight)

    user_product = (
        user_product
        .groupby(["user_id", "product_id"])["score"]
        .sum()
        .reset_index()
    )

    user_product["user_idx"] = user_product["user_id"].astype("category").cat.codes
    user_product["product_idx"] = user_product["product_id"].astype("category").cat.codes

    return user_product

In [7]:
def build_matrix(user_product):
    return sp.csr_matrix(
        (user_product["score"], (user_product["user_idx"], user_product["product_idx"]))
    )

In [8]:
def get_mappings(user_product):
    product_idx_to_id = dict(zip(user_product["product_idx"], user_product["product_id"]))
    product_id_to_idx = dict(zip(user_product["product_id"], user_product["product_idx"]))
    user_id_to_idx = dict(zip(user_product["user_id"], user_product["user_idx"]))
    return product_idx_to_id, product_id_to_idx, user_id_to_idx

In [9]:
def train_als(matrix):
    model = AlternatingLeastSquares(
        factors=50,
        regularization=0.05,
        iterations=100,
        alpha=10
    )
    model.fit(matrix)
    return model

In [10]:
def save_artifacts(user_product, matrix, model, product_idx_to_id, product_id_to_idx,user_id_to_idx):
    joblib.dump(matrix, "../models/matrix_factorization/feature_matrix.joblib")
    joblib.dump(model, "../models/matrix_factorization/matrix_factorization_model.joblib")
    joblib.dump(product_idx_to_id,
                "../models/matrix_factorization/product_idx_to_id_mapping.joblib")
    joblib.dump(product_id_to_idx,
                "../models/matrix_factorization/product_id_to_idx_mapping.joblib") 
    joblib.dump(user_id_to_idx,
                "../models/matrix_factorization/user_id_to_idx_mapping.joblib") 
    joblib.dump(model.item_factors, "../models/matrix_factorization/item_factors.joblib") 
    joblib.dump(model.user_factors, "../models/matrix_factorization/user_factors.joblib")

In [11]:
def train_model(df):

    user_product = preprocess(df)
    matrix = build_matrix(user_product) 
    model = train_als(matrix)
    product_idx_to_id, product_id_to_idx, user_id_to_idx = get_mappings(user_product)
    save_artifacts(user_product, matrix, model, product_idx_to_id, product_id_to_idx,user_id_to_idx)

    return model, matrix, product_idx_to_id, product_id_to_idx, user_id_to_idx

In [12]:
model,matrix,product_idx_to_id,product_id_to_idx,user_id_to_idx = train_model(df)

  0%|          | 0/100 [00:00<?, ?it/s]

In [13]:
product_id_to_idx[10]

4

In [14]:
df3 = df[ df['product_id'] == 95 ]

In [15]:
df3

      user_id  product_id interaction_type
77        488          95            click
3207      645          95            click
3314      650          95            click
8334      901          95               R5
8363      903          95     wishlist_add
8366      903          95               R4
8427      906          95     wishlist_add
8504      910          95               R4
8561      912          95               R4
8580      913          95         cart_add
8624      916          95               R5
8695      919          95         cart_add
8720      920          95         cart_add
8797      924          95     wishlist_add
8884      929          95               R5
8929      931          95               R4
8942      931          95         cart_add
8995      934          95         cart_add
9008      935          95         cart_add
9013      935          95               R4
9052      937          95         cart_add
9055      937          95     wishlist_add
9069      938          95         cart_add
9072      938          95     wishlist_add

In [16]:
df.head()

   user_id  product_id interaction_type
0      485         258               R5
1      485         191               R5
2      485         192     wishlist_add
3      485         201     wishlist_add
4      485         187               R5

In [17]:
model.user_factors

array([[-0.51688486, -0.3978531 ,  0.40242946, ...,  0.25081208,
         0.05935377,  0.10291579],
       [-1.085677  ,  1.4833729 , -0.27612004, ...,  0.06918569,
        -0.12772432,  0.14861092],
       [-0.32953736,  1.002977  , -0.38568252, ..., -0.2982323 ,
        -0.20106037, -0.3343168 ],
       ...,
       [ 0.08542821,  0.19561417, -0.32077816, ...,  0.4550414 ,
         0.46962005, -0.14112832],
       [ 0.08369512,  0.19408275, -0.3166029 , ...,  0.45428473,
         0.46381366, -0.14241044],
       [ 0.0851946 ,  0.19210713, -0.3188237 , ...,  0.45064506,
         0.46323317, -0.14247794]], shape=(500, 50), dtype=float32)

In [19]:
user_id_to_idx[487], product_id_to_idx[6], product_idx_to_id[1]

(2, 1, 6)