In [222]:
import joblib
import pandas as pd
import scipy.sparse as sp
from sqlalchemy import create_engine
from implicit.als import AlternatingLeastSquares

In [223]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [224]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, interaction_type
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)

In [225]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  int64
 1   product_id        10000 non-null  int64
 2   interaction_type  10000 non-null  str
dtypes: int64(2), str(1)
memory usage: 308.7 KB

In [226]:
interaction_weight = {
    "click": 0.001,
    "wishlist_add": 0.7,
    "cart_add": 1,
    "R5": 2.0,
    "R4": 1.8,
    "R3": 1.6,
    "R2": 1.4,
    "R1": 1.2,
    "R0": 1.0,
}

In [227]:
def preprocess(df):
    user_product = df[["user_id", "product_id"]].copy()

    user_product["score"] = df["interaction_type"].map(interaction_weight)

    user_product = (
        user_product
        .groupby(["user_id", "product_id"])["score"]
        .sum()
        .reset_index()
    )

    user_product["user_idx"] = user_product["user_id"].astype("category").cat.codes
    user_product["product_idx"] = user_product["product_id"].astype("category").cat.codes

    return user_product

In [228]:
def build_matrix(user_product):
    return sp.csr_matrix(
        (user_product["score"], (user_product["user_idx"], user_product["product_idx"]))
    )

In [229]:
def get_mappings(user_product):
    product_idx_to_id = dict(zip(user_product["product_idx"], user_product["product_id"]))
    product_id_to_idx = dict(zip(user_product["product_id"], user_product["product_idx"]))
    user_id_to_idx = dict(zip(user_product["user_id"], user_product["user_idx"]))
    return product_idx_to_id, product_id_to_idx, user_id_to_idx

In [230]:
def train_als(matrix):
    model = AlternatingLeastSquares(
        factors=50,
        regularization=0.05,
        iterations=100,
        alpha=10
    )
    model.fit(matrix)
    return model

In [231]:
def save_artifacts(user_product, matrix, model, product_idx_to_id, product_id_to_idx,user_id_to_idx):
    joblib.dump(matrix, "../models/matrix_factorization/feature_matrix.joblib")
    joblib.dump(model, "../models/matrix_factorization/matrix_factorization_model.joblib")
    joblib.dump(product_idx_to_id,
                "../models/matrix_factorization/product_idx_to_id_mapping.joblib")
    joblib.dump(product_id_to_idx,
                "../models/matrix_factorization/product_id_to_idx_mapping.joblib") 
    joblib.dump(user_id_to_idx,
                "../models/matrix_factorization/user_id_to_idx_mapping.joblib") 
    joblib.dump(model.item_factors, "../models/matrix_factorization/item_factors.joblib") 
    joblib.dump(model.user_factors, "../models/matrix_factorization/user_factors.joblib")

In [232]:
def train_model(df):

    user_product = preprocess(df)
    matrix = build_matrix(user_product) 
    model = train_als(matrix)
    product_idx_to_id, product_id_to_idx, user_id_to_idx = get_mappings(user_product)
    save_artifacts(user_product, matrix, model, product_idx_to_id, product_id_to_idx,user_id_to_idx)

    return model, matrix, product_idx_to_id, product_id_to_idx, user_id_to_idx

In [233]:
model,matrix,product_idx_to_id,product_id_to_idx,user_id_to_idx = train_model(df)

  0%|          | 0/100 [00:00<?, ?it/s]

In [234]:
product_id_to_idx[10]

4

In [235]:
df3 = df[ df['product_id'] == 95 ]

In [236]:
df3

      user_id  product_id interaction_type
77        488          95            click
3207      645          95            click
3314      650          95            click
8331      901          95               R5
8360      903          95     wishlist_add
8363      903          95               R4
8424      906          95     wishlist_add
8501      910          95               R4
8558      912          95               R4
8577      913          95         cart_add
8621      916          95               R5
8692      919          95         cart_add
8717      920          95         cart_add
8794      924          95     wishlist_add
8881      929          95               R5
8926      931          95               R4
8939      931          95         cart_add
8992      934          95         cart_add
9005      935          95         cart_add
9010      935          95               R4
9049      937          95         cart_add
9052      937          95     wishlist_add
9066      938          95         cart_add
9069      938          95     wishlist_add

In [237]:
df.head()

   user_id  product_id interaction_type
0      485         258               R5
1      485         191               R5
2      485         192     wishlist_add
3      485         201     wishlist_add
4      485         187               R5

In [238]:
model.user_factors

array([[ 1.0629839e-01, -2.6842454e-01,  5.6547873e-02, ...,
        -1.2075589e-03,  8.9980555e-01,  1.0467221e-01],
       [ 3.0563992e-01,  7.8849626e-01, -2.1813642e-02, ...,
         4.1739170e-02,  5.5660814e-01,  2.6663947e-01],
       [ 1.6738017e-01,  4.3663865e-01,  3.0676568e-01, ...,
         1.6585350e-01,  2.1119507e-01,  4.5849059e-02],
       ...,
       [ 5.2159393e-01, -3.8072958e-03,  7.4168408e-01, ...,
         4.0410146e-02,  3.1623632e-01, -5.8979398e-01],
       [ 5.2874553e-01,  4.0931255e-03,  7.4405473e-01, ...,
         4.0650722e-02,  3.1582466e-01, -5.8969927e-01],
       [ 5.2383244e-01, -5.5953057e-04,  7.4141186e-01, ...,
         4.1125067e-02,  3.1468979e-01, -5.8846468e-01]],
      shape=(500, 50), dtype=float32)