## SETUP

In [180]:
import math 
import random 
import numpy as np 
import pandas as pd 
import torch 
from torch.utils.data import Dataset, DataLoader
from torch import nn
from sqlalchemy import create_engine

## Fetch data from database

In [181]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [182]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, created_at
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)
num_items = pd.read_sql("SELECT COUNT(*) AS num_items FROM products", engine).iloc[0]['num_items']

In [183]:
df['created_at'] = pd.to_datetime(df['created_at'])

In [184]:
interactions_df = df.rename(columns={'product_id':'item_id','created_at':'timestamp'}).sort_values(['user_id','timestamp']).reset_index(drop=True)

In [185]:
interactions_df.head()

   user_id  item_id           timestamp
0      485      258 2026-04-17 18:15:13
1      485      191 2026-04-17 18:15:13
2      485      192 2026-04-17 18:15:13
3      485      201 2026-04-17 18:15:13
4      485      187 2026-04-17 18:15:13

In [186]:
interactions_df.shape

(10019, 3)

## Mapping handling

In [188]:
interactions_df["real_user_id"] = interactions_df["user_id"] 
interactions_df["user_id"] = interactions_df.groupby("user_id").ngroup() + 1 
interactions_df["real_item_id"] = interactions_df["item_id"]
interactions_df["item_id"] = interactions_df.groupby("item_id").ngroup() + 1

In [190]:
interactions_df.head()

   user_id  item_id           timestamp  real_user_id  real_item_id
0        1      221 2026-04-17 18:15:13           485           258
1        1      176 2026-04-17 18:15:13           485           191
2        1      177 2026-04-17 18:15:13           485           192
3        1      185 2026-04-17 18:15:13           485           201
4        1      172 2026-04-17 18:15:13           485           187

In [191]:
user_id_to_index = dict(zip(interactions_df["real_user_id"], interactions_df["user_id"])) 
item_id_to_index = dict(zip(interactions_df["real_item_id"], interactions_df["item_id"])) 
item_index_to_id = dict(zip(interactions_df["item_id"], interactions_df["real_item_id"]))

In [192]:
user_id_to_index[485],item_id_to_index[191],item_index_to_id[221]

(1, 176, 258)

In [193]:
item_index_to_id[245]

KeyError: 245

## I. CONSTANT VARIABLES FOR SETUP

In [ ]:
SEED = 42
NUM_USERS = 1000
NUM_ITEMS = 500
NUM_CATEGORIES = 10 
MIN_INTERACTIONS = 10 
MAX_INTERACTIONS = 50
MAX_SEQ_LEN = 30
BATCH_SIZE = 64
PAD_ID = 0 
MASK_ID = NUM_ITEMS + 1
VOCAB_SIZE = NUM_ITEMS + 2

In [195]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# Generate Item Categories

In [99]:
item_ids = np.arange(1,NUM_ITEMS + 1)
item_categories = np.random.randint(0, NUM_CATEGORIES, size=NUM_ITEMS) 

items_df = pd.DataFrame({
    'item_id': item_ids,
    'category_id': item_categories
})

In [100]:
items_df.head()

   item_id  category_id
0        1            6
1        2            3
2        3            7
3        4            4
4        5            6

## Generate User Item Interactions

In [101]:
interactions = []
for user_id in range(1,NUM_USERS + 1): 
    favorite_categories = np.random.choice(
        NUM_CATEGORIES, size=2, replace=False
    )
    num_interactions = np.random.randint(MIN_INTERACTIONS, MAX_INTERACTIONS + 1)

    current_time = 0

    for _ in range(num_interactions):
        use_favorite = np.random.rand() < 0.8

        if use_favorite:
            chosen_category = np.random.choice(favorite_categories)
        else:
            chosen_category = np.random.randint(0, NUM_CATEGORIES)
        candidate_items = items_df[items_df['category_id'] == chosen_category]['item_id'].values

        chosen_item = np.random.choice(candidate_items)

        interactions.append({
            "user_id": user_id,
            "item_id": int(chosen_item),
            "timestamp": current_time
        })
        current_time += 1
interactions_df = pd.DataFrame(interactions)
interactions_df = interactions_df.sort_values(by=['user_id', 'timestamp'])
interactions_df = interactions_df.reset_index(drop=True)
interactions_df.head()

   user_id  item_id  timestamp
0        1      347          0
1        1       77          1
2        1      206          2
3        1      460          3
4        1      240          4

## Turn interactions into sequences

In [102]:
user_sequences = interactions_df.groupby("user_id")["item_id"].apply(list).to_dict()

In [103]:
user_sequences[1]

[347,
 77,
 206,
 460,
 240,
 332,
 412,
 317,
 45,
 385,
 103,
 380,
 109,
 353,
 5,
 341,
 184,
 190,
 51,
 390,
 95,
 8,
 256,
 256,
 370,
 104,
 441,
 341]

## Train Test Split

In [104]:
train_user_sequences = {}
test_user_sequences = []
for user_id,seq in user_sequences.items():
    if len(seq) < 2: continue
    train_seq = seq[:-1]
    target_item = seq[-1]

    train_user_sequences[user_id] = train_seq
    test_user_sequences.append({
        "user_id":user_id, 
        "input_sequence": train_seq, 
        "target_item": target_item
    })

In [105]:
train_user_sequences[1]

[347,
 77,
 206,
 460,
 240,
 332,
 412,
 317,
 45,
 385,
 103,
 380,
 109,
 353,
 5,
 341,
 184,
 190,
 51,
 390,
 95,
 8,
 256,
 256,
 370,
 104,
 441]

## Create Training Samples For BERT4Rec

In [106]:
training_samples = []

for user_id,sequence in train_user_sequences.items(): 
    for target_index in range(1,len(sequence)): 
        input_sequence = sequence[:target_index+1] 
        
        if len(input_sequence) > MAX_SEQ_LEN: 
            input_sequence = input_sequence[-MAX_SEQ_LEN:]
        
        training_samples.append({"user_id":user_id, "input_sequence": input_sequence})
samples_df = pd.DataFrame(training_samples)

In [107]:
training_samples[2]

{'user_id': 1, 'input_sequence': [347, 77, 206, 460]}

In [108]:
samples_df.head()

   user_id                 input_sequence
0        1                      [347, 77]
1        1                 [347, 77, 206]
2        1            [347, 77, 206, 460]
3        1       [347, 77, 206, 460, 240]
4        1  [347, 77, 206, 460, 240, 332]

## Create mask sequence function

In [109]:
def mask_sequence_for_bert4rec(input_sequence, mask_id,pad_id,mask_prob=0.2): 
    masked_sequence = input_sequence.copy() 
    labels = [-100] * len(input_sequence) 

    candidate_positions =[] 

    for index,item_id in enumerate(input_sequence): 
        if item_id != pad_id : 
            candidate_positions.append(index) 
    masked_any = False 

    for index in candidate_positions: 
        if random.random() < mask_prob: 
            labels[index] = input_sequence[index]
            masked_sequence[index] = mask_id
            masked_any = True 
            
    if not masked_any and len(candidate_positions) > 0:
        index = random.choice(candidate_positions)
        labels[index] = input_sequence[index] 
        masked_sequence[index] = mask_id

    return masked_sequence, labels

## Create Custom Pytorch Dataset

In [110]:
class BERT4RecDataset(Dataset): 
    def __init__(self,samples,max_seq_len,mask_id,pad_id,mask_prob=0.2):
        self.samples = samples 
        self.max_seq_len = max_seq_len 
        self.mask_id = mask_id 
        self.pad_id = pad_id 
        self.mask_prob = mask_prob
    def __len__(self): 
        return len(self.samples)
    def __getitem__(self,index):
        sample = self.samples[index]
        input_sequence = sample["input_sequence"]

        padding_length = self.max_seq_len - len(input_sequence) 
        padded_sequence = [self.pad_id] * padding_length + input_sequence

        masked_sequence, labels = mask_sequence_for_bert4rec(
            input_sequence = padded_sequence,
            mask_id = self.mask_id, 
            pad_id = self.pad_id,
            mask_prob = self.mask_prob
        )

        input_tensor = torch.tensor(masked_sequence,dtype=torch.long)
        target_tensor = torch.tensor(labels,dtype=torch.long)

        return input_tensor,target_tensor
train_dataset = BERT4RecDataset(training_samples,MAX_SEQ_LEN,MASK_ID,PAD_ID,mask_prob=0.2)

In [111]:
input,target = train_dataset[10]
input,target

(tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 347, 501, 206, 460, 240, 332, 412, 501,  45, 501,
         103, 380]),
 tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100,   77, -100, -100, -100, -100,
         -100,  317, -100,  385, -100, -100]))

## Create DataLoader

In [112]:
train_loader = DataLoader(train_dataset,batch_size=BATCH_SIZE,shuffle=True)

In [113]:
input_batch,target_batch = next(iter(train_loader))
print("Input batch shape:",input_batch.shape)
print("Target batch shape:",target_batch.shape)
print("Input first item in batch example:\n",input_batch[0])
print("Target first item in batch example:\n",target_batch[0])

Input batch shape: torch.Size([64, 30])
Target batch shape: torch.Size([64, 30])
Input first item in batch example:
 tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 501, 501, 347, 388,
        208, 299])
Target first item in batch example:
 tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         242,  156, -100, -100, -100, -100])

## Create Class BERT4Rec Model

In [114]:
class BERT4RecModel(nn.Module): 
    def __init__(
            self,
            num_items,
            max_seq_len,
            embedding_dim=64,
            num_attention_heads=2,
            num_transformer_blocks=2,
            dropout_rate=0.1 
        ):
        super().__init__()
        self.num_items = num_items 
        self.max_seq_len = max_seq_len
        self.embedding_dim = embedding_dim

        # 1. Item Embedding Layer
        self.item_embedding = nn.Embedding(
            num_embeddings = VOCAB_SIZE,
            embedding_dim = embedding_dim,
            # Embedding for padding will be a zero vector and not updated during training
            padding_idx = 0 # Position of embedding zero in the embedding matrix
        )

        # 2. Position Embedding Layer
        self.position_embedding = nn.Embedding(
            num_embeddings = max_seq_len, 
            embedding_dim = embedding_dim
        )
        
        self.dropout = nn.Dropout(dropout_rate) # Dropout layer for regularization

        # Transformer Blocks
        transformer_block = nn.TransformerEncoderLayer(
            # Multi-Head Self-Attention
            d_model = embedding_dim,  # Embedding dimension for the transformer, define the dim for matrices Q, K, V
            nhead = num_attention_heads, # Number of attention heads in the multi-head attention mechanism

            # Multi Layer Perceptron (MLP)
            dropout = dropout_rate, # Dropout rate for regularization
            dim_feedforward = embedding_dim * 4, # Expansion Weights 
            activation = "gelu", # Activation function for the feedforward network

            #Supplementary Arguments
            batch_first = True, # Input shape (batch_size, seq_len, embedding_dim)
            norm_first = True # Apply layer normalization before the attention and feedforward layers
        )

        # 3. Transformer Layer
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer = transformer_block, # Base transformer block to be repeated
            num_layers = num_transformer_blocks # Number of transformer blocks
        )
        
        self.layer_norm = nn.LayerNorm(embedding_dim) # Layer normalization to stabilize training 

        # 4. Output Layer
        self.output_layer = nn.Linear(embedding_dim, VOCAB_SIZE) # Linear layer to project
    def forward(self, input_sequences):
        device = input_sequences.device
        batch_size, seq_len = input_sequences.shape 

        positions = torch.arange(
            seq_len, device=device
        )

        positions = positions.unsqueeze(0)
        positions = positions.expand(batch_size, seq_len)

        item_emb = self.item_embedding(input_sequences) 
        pos_emb = self.position_embedding(positions) 

        x = item_emb + pos_emb
        x = self.dropout(x)

        padding_mask = input_sequences.eq(0)

        x = self.transformer_encoder(
            x,
            src_key_padding_mask = padding_mask 
        )

        x = self.layer_norm(x) 
        logits = self.output_layer(x)  

        return logits

## II. CONSTANT VARIABLES FOR TRAINING

In [115]:
EMBEDDING_DIM = 256
NUM_ATTENTION_HEADS = 4
NUM_TRANSFORMER_BLOCKS = 4
DROPOUT_RATE = 0.2
NUM_EPOCHS = 50

## Initialize Bert4Rec Model

In [116]:
model = BERT4RecModel(
    num_items = NUM_ITEMS,
    max_seq_len = MAX_SEQ_LEN,
    embedding_dim = EMBEDDING_DIM,
    num_attention_heads = NUM_ATTENTION_HEADS,
    num_transformer_blocks = NUM_TRANSFORMER_BLOCKS,
    dropout_rate = DROPOUT_RATE
)

/var/folders/v1/f1gz50591kl2_tm8_gxbrtcc0000gn/T/ipykernel_12354/3944191416.py:49: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.transformer_encoder = nn.TransformerEncoder(

## Testing Model with 1 batch

In [117]:
input_batch,target_batch = next(iter(train_loader))

In [118]:
input_batch,target_batch

(tensor([[  0,   0,   0,  ..., 369, 501, 275],
         [501, 501, 209,  ..., 115, 289, 108],
         [  0,   0,   0,  ..., 501,   5, 341],
         ...,
         [501, 195, 489,  ...,   4, 365, 501],
         [  0,   0,   0,  ..., 389, 501, 501],
         [  0,   0,   0,  ...,  77, 131, 444]]),
 tensor([[-100, -100, -100,  ..., -100,   85, -100],
         [  86,  235, -100,  ..., -100, -100, -100],
         [-100, -100, -100,  ...,  374, -100, -100],
         ...,
         [  28, -100, -100,  ..., -100, -100,   54],
         [-100, -100, -100,  ..., -100,  235,  451],
         [-100, -100, -100,  ..., -100, -100, -100]]))

In [119]:
input_batch.shape,target_batch.shape

(torch.Size([64, 30]), torch.Size([64, 30]))

In [120]:
logits = model(input_batch)
print("Logits shape:",logits.shape)
print("Logits example:\n",logits)

Logits shape: torch.Size([64, 30, 502])
Logits example:
 tensor([[[-0.2946,  0.7168, -0.7213,  ..., -0.2161, -0.2515, -0.7539],
         [-0.5479,  0.1619, -0.2051,  ..., -0.1555,  0.4236, -0.2373],
         [-0.9166,  0.3043,  0.6871,  ..., -0.9856,  0.9525, -0.5755],
         ...,
         [ 0.3224,  0.1292, -0.5921,  ...,  0.6683, -1.1226, -0.0392],
         [ 0.5555,  0.6209, -0.3408,  ..., -0.1311, -0.4885, -0.1810],
         [-0.7871,  0.2832, -0.2521,  ..., -0.5797,  0.6592,  0.1621]],

        [[-0.2280,  0.5696,  0.0592,  ..., -0.8582, -0.1815, -0.5942],
         [ 0.2246, -0.0953,  0.2292,  ..., -0.6911,  0.4932, -0.0296],
         [-1.4440,  0.2673, -0.0788,  ..., -0.1792, -0.2258, -0.3393],
         ...,
         [ 0.5173,  0.2284, -0.1944,  ..., -0.2217, -0.4282,  0.4257],
         [-0.6953, -0.6209,  1.2456,  ..., -0.2588, -0.5247,  0.2843],
         [-0.8787,  0.8805, -0.0876,  ...,  0.0624, -0.0040, -0.0815]],

        [[-0.9505,  0.9014,  0.2695,  ..., -0.8124,  0.1304, -0.6235],
         [-0.1506,  0.6245, -0.0629,  ...,  0.2198,  0.8181, -0.5501],
         [-1.6496,  0.2413, -0.3584,  ..., -1.2556,  0.5938, -0.2077],
         ...,
         [ 0.5985,  0.7337, -0.1245,  ...,  0.0790, -1.2896,  0.5364],
         [-0.0454, -0.1126,  0.4570,  ..., -0.0822, -0.0149, -1.0498],
         [-1.0527,  0.3800,  0.3774,  ..., -0.5059, -0.5146, -0.1713]],

        ...,

        [[-0.3691,  0.9498, -0.0167,  ..., -1.1606,  0.1173, -0.3279],
         [-0.4258,  0.5759, -0.3856,  ..., -0.6005,  0.3156,  0.2487],
         [-1.7847,  0.6745,  0.4369,  ..., -0.8531,  0.5212, -0.6977],
         ...,
         [ 0.3743, -0.1029, -0.0904,  ...,  0.8783, -0.5370,  0.6086],
         [ 0.1392,  0.1421, -0.2283,  ..., -0.5820, -0.0935, -1.1731],
         [-1.0276,  0.4795,  0.4545,  ..., -1.0496,  0.3851,  0.5441]],

        [[-0.3942,  0.5965, -0.5839,  ..., -0.8630, -0.2771, -0.5046],
         [ 0.4682, -0.0070,  0.3720,  ..., -0.0449,  0.4793, -0.4458],
         [-1.0543,  0.3371, -0.1463,  ..., -0.9650,  0.1294, -0.1462],
         ...,
         [ 0.2562,  0.8671, -0.5364,  ...,  0.1656, -1.1038, -0.2253],
         [-0.3374,  0.5961, -0.3384,  ..., -0.2036, -0.4639, -0.5727],
         [-0.8313,  0.9426, -0.0456,  ..., -0.4733, -0.3366,  0.3377]],

        [[-0.8130,  0.1059,  0.1401,  ..., -0.6931,  0.2587, -0.4727],
         [ 0.2579,  0.0361,  0.2148,  ..., -0.0756,  0.9053, -0.2248],
         [-1.2869,  0.0384,  0.1981,  ..., -1.3730,  0.6976, -0.4851],
         ...,
         [-0.1003,  0.5159,  0.1414,  ...,  0.5101,  0.2281,  0.2706],
         [ 0.0284, -0.0846,  0.1933,  ...,  0.6088, -0.8798, -0.5025],
         [-1.9849,  0.7254,  0.4296,  ..., -0.4531,  0.4262,  0.7421]]],
       grad_fn=<ViewBackward0>)

In [121]:
loss_function = nn.CrossEntropyLoss(ignore_index=-100)
loss = loss_function(logits.view(-1,VOCAB_SIZE),target_batch.view(-1))
print("Loss:",loss.item())

Loss: 6.393956661224365

## Create Training Loop for SASRec

In [122]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu") 
model = model.to(device)

In [123]:
loss_function = nn.CrossEntropyLoss(ignore_index=-100)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)

In [163]:
for epoch in range(1,NUM_EPOCHS + 1): 
    model.train()
    total_loss = 0.0
    total_batches = 0

    for input_batch,target_batch in train_loader:
        input_batch = input_batch.to(device) 
        target_batch = target_batch.to(device)

        # ----- Training step -----
        # 1. Feed Forward 
        logits = model(input_batch) 

        # 2. Compute Loss 
        loss = loss_function(logits.view(-1,VOCAB_SIZE),target_batch.view(-1)) 

        # 3. Reset gradients
        optimizer.zero_grad()

        # 4. Feed Backward
        loss.backward()
        
        # 5. Update Weights
        optimizer.step() 
        # -------- Training Step --------

        # Accumulate loss for monitoring 
        total_loss += loss.item()
        total_batches += 1
    avg_loss = total_loss / total_batches
    print(f"Epoch {epoch}/{NUM_EPOCHS}, Average Loss: {avg_loss:.4f}")

Epoch 1/50, Average Loss: 3.0151
Epoch 2/50, Average Loss: 2.9629
Epoch 3/50, Average Loss: 2.9141
Epoch 4/50, Average Loss: 2.8714
Epoch 5/50, Average Loss: 2.8244
Epoch 6/50, Average Loss: 2.7895
Epoch 7/50, Average Loss: 2.7480
Epoch 8/50, Average Loss: 2.7064
Epoch 9/50, Average Loss: 2.6769
Epoch 10/50, Average Loss: 2.6252
Epoch 11/50, Average Loss: 2.5860
Epoch 12/50, Average Loss: 2.5537
Epoch 13/50, Average Loss: 2.5244
Epoch 14/50, Average Loss: 2.4846
Epoch 15/50, Average Loss: 2.4460
Epoch 16/50, Average Loss: 2.4150
Epoch 17/50, Average Loss: 2.3851
Epoch 18/50, Average Loss: 2.3586
Epoch 19/50, Average Loss: 2.3282
Epoch 20/50, Average Loss: 2.2924
Epoch 21/50, Average Loss: 2.2720
Epoch 22/50, Average Loss: 2.2452
Epoch 23/50, Average Loss: 2.2101
Epoch 24/50, Average Loss: 2.1923
Epoch 25/50, Average Loss: 2.1633
Epoch 26/50, Average Loss: 2.1321
Epoch 27/50, Average Loss: 2.1139
Epoch 28/50, Average Loss: 2.0867
Epoch 29/50, Average Loss: 2.0627
Epoch 30/50, Average Loss: 2.0384
Epoch 31/50, Average Loss: 2.0196
Epoch 32/50, Average Loss: 1.9928
Epoch 33/50, Average Loss: 1.9726
Epoch 34/50, Average Loss: 1.9633
Epoch 35/50, Average Loss: 1.9341
Epoch 36/50, Average Loss: 1.9209
Epoch 37/50, Average Loss: 1.8960
Epoch 38/50, Average Loss: 1.8955
Epoch 39/50, Average Loss: 1.8561
Epoch 40/50, Average Loss: 1.8509
Epoch 41/50, Average Loss: 1.8345
Epoch 42/50, Average Loss: 1.8238
Epoch 43/50, Average Loss: 1.7957
Epoch 44/50, Average Loss: 1.7864
Epoch 45/50, Average Loss: 1.7715
Epoch 46/50, Average Loss: 1.7583
Epoch 47/50, Average Loss: 1.7499
Epoch 48/50, Average Loss: 1.7317
Epoch 49/50, Average Loss: 1.7153
Epoch 50/50, Average Loss: 1.7016

## Recommend For Next Items

In [165]:
TOP_K = 50

In [166]:
def recommend(model,user_sequence,top_k=TOP_K):
    model.eval() 
    
    if len(user_sequence) > MAX_SEQ_LEN - 1:
        user_sequence = user_sequence[-(MAX_SEQ_LEN-1):]

    sequence_with_mask = user_sequence + [MASK_ID] 
    padding_length = MAX_SEQ_LEN - len(sequence_with_mask)
    padded_sequence = [PAD_ID] * padding_length + sequence_with_mask

    input_tensor = torch.tensor(
        [padded_sequence], 
        dtype=torch.long
    ).to(device)

    with torch.no_grad():
        logits = model(input_tensor) 
        mask_position = len(padded_sequence) - 1 
        scores = logits[0][mask_position] 

    scores[PAD_ID] = float('-inf')
    scores[MASK_ID] = float('-inf')

    for item_id in set(user_sequence): 
        scores[item_id] = float('-inf')
    
    top_scres,top_items = torch.topk(scores, top_k)

    return top_items.cpu().tolist(),top_scres.cpu().tolist()

In [177]:
example_user_id = 10
example_sequence = user_sequences[example_user_id]
recommended_items,recommended_scores = recommend(
    model=model,
    user_sequence=example_sequence,
    top_k=TOP_K
)
print("Past interacted items:\n", example_sequence)
print("Recommended items:\n ", recommended_items)
print("Recommended scores:\n ", recommended_scores)

Past interacted items:
 [82, 395, 355, 122, 41, 324, 433, 463, 99, 404, 412, 83, 312, 78, 153, 326, 37, 33, 463, 480, 148, 342, 230, 391, 27]
Recommended items:
  [94, 257, 384, 97, 482, 456, 261, 473, 64, 314, 358, 159, 417, 259, 80, 265, 331, 408, 330, 26, 357, 340, 4, 72, 228, 21, 66, 333, 167, 182, 77, 43, 203, 120, 121, 398, 229, 219, 6, 274, 73, 399, 426, 93, 209, 154, 346, 450, 466, 150]
Recommended scores:
  [5.985180377960205, 5.98385763168335, 5.371004581451416, 5.332705497741699, 5.135697364807129, 5.07022762298584, 4.793736934661865, 4.774608135223389, 4.696044921875, 4.489660263061523, 4.482052326202393, 4.424026012420654, 4.406745910644531, 4.279779434204102, 4.227138996124268, 4.197723388671875, 4.170734405517578, 4.092684745788574, 3.9893949031829834, 3.877502679824829, 3.8228559494018555, 3.7549331188201904, 3.705932855606079, 3.689011812210083, 3.6855411529541016, 3.5998520851135254, 3.588669538497925, 3.5738444328308105, 3.514799118041992, 3.506056785583496, 3.493881940841675, 3.4647648334503174, 3.4544150829315186, 3.454127550125122, 3.395585298538208, 3.3228206634521484, 3.2823238372802734, 3.282123565673828, 3.2525157928466797, 3.2127737998962402, 3.1932506561279297, 3.1784698963165283, 3.130402088165283, 3.1269619464874268, 3.0238842964172363, 3.0029571056365967, 2.99786376953125, 2.9945363998413086, 2.980213165283203, 2.9691944122314453]

In [176]:
category_from_recommended = items_df[items_df['item_id'].isin(recommended_items)]['category_id'].unique()
category_from_past = items_df[items_df['item_id'].isin(example_sequence)]['category_id'].unique()
print("Categories of recommended items:\n", category_from_recommended, ",length: ", len(category_from_recommended))
print("Categories of past interacted items:\n", category_from_past, ",length: ", len(category_from_past))
recommended_categories_not_in_past = np.setdiff1d(category_from_recommended, category_from_past)
print("Recommended Categories that ARE NOT IN past interacted items:\n", recommended_categories_not_in_past, ",length: ", len(recommended_categories_not_in_past))
recommended_categories_in_past = np.intersect1d(category_from_recommended, category_from_past)
print("Recommended Categories that ARE IN past interacted items:\n", recommended_categories_in_past, ",length: ", len(recommended_categories_in_past))
length_of_total_past_categories_is_recommended = len(np.intersect1d(category_from_recommended, category_from_past))
print("Total past categories that are recommended:\n", length_of_total_past_categories_is_recommended)

Categories of recommended items:
 [4 9 0 1 8 7 6 5 2] ,length:  9
Categories of past interacted items:
 [9 4 8 7 5 1] ,length:  6
Recommended Categories that ARE NOT IN past interacted items:
 [0 2 6] ,length:  3
Recommended Categories that ARE IN past interacted items:
 [1 4 5 7 8 9] ,length:  6
Total past categories that are recommended:
 6

## Evaluation

In [171]:
def evaluate_model(model,test_samples,top_k=10): 
    hits = []
    recalls = []
    ndcgs = []
    for sample in test_samples:
        user_sequence = sample["input_sequence"]
        target_item = sample["target_item"]
        recommended_items,recommended_scores = recommend(
            model=model,
            user_sequence=user_sequence,
            top_k=top_k
        )

        if target_item in recommended_items: 
            hit = 1
            recall = 1 
            rank = recommended_items.index(target_item) + 1 
            ndcg = 1/math.log2(rank+1) 
        else:
            hit = 0 
            recall = 0 
            ndcg = 0
        hits.append(hit)
        recalls.append(recall)
        ndcgs.append(ndcg)  
    hit_at_k = sum(hits)/len(hits)
    recall_at_k = sum(recalls)/len(recalls)
    ndcg_at_k = sum(ndcgs)/len(ndcgs)

    return hit_at_k, recall_at_k, ndcg_at_k,hits, recalls, ndcgs

In [172]:
hit_at_10, recall_at_10, ndcg_at_10 ,hits, recalls, ndcgs = evaluate_model(model,test_user_sequences,top_k=10)
print(f"Hit@10: {hit_at_10:.4f}, Recall@10: {recall_at_10:.4f}, NDCG@10: {ndcg_at_10:.4f}")

Hit@10: 0.0760, Recall@10: 0.0760, NDCG@10: 0.0347

In [173]:
hits.count(1)

76

In [174]:
len(test_user_sequences)

1000