In [224]:
import re
import math 
import random 
import pandas as pd 

import torch 
import torch.nn as nn 
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.feature_extraction.text import TfidfVectorizer
from sqlalchemy import create_engine

In [225]:
SEED = 42 
random.seed(SEED)
torch.manual_seed(SEED)
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

## Fetch data from database

In [226]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [227]:
products_df = pd.read_sql(
    """SELECT 
    id,category_id, sub_category_id, brand_id, price, offer_price,name, short_description, 
    long_description FROM products""", engine)

In [228]:
interactions_df = pd.read_sql(
    """
    SELECT user_id, product_id, interaction_type, created_at
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """, engine)

In [229]:
products_df.head()

,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description
0,5,20,58,52,7.0,6.0,Nestle Ready Meal Bento Box,<b>Instant Food</b><p>Convenient ready meal wi...,<b>Nestle Ready Meal Bento Box</b><p>This read...
1,6,5,7,19,25.0,20.0,Nike Summer Cotton T-Shirt,<b>Summer T-Shirt</b><p>Breathable cotton t-sh...,<b>Nike Summer Cotton T-Shirt</b><p>This light...
2,7,5,4,6,35.0,29.0,Selons Knit Sweater,<b>Knit Sweater</b><p>Soft knit sweater design...,<b>Selons Knit Sweater</b><p>This sweater is m...
3,9,6,10,18,699.0,649.0,Samsung Galaxy Tab S9 5G,<b>Tablet</b><p>High performance tablet design...,<b>Samsung Galaxy Tab S9 5G</b><p>This tablet ...
4,10,7,14,12,39.0,34.0,Xiaomi Y68 Smart Watch,<b>Smart Watch</b><p>Affordable smart watch wi...,<b>Xiaomi Y68 Smart Watch</b><p>This smart wat...

In [230]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 243 non-null    int64
 1   category_id        243 non-null    int64
 2   sub_category_id    243 non-null    int64
 3   brand_id           243 non-null    int64
 4   price              243 non-null    float64
 5   offer_price        243 non-null    float64
 6   name               243 non-null    str
 7   short_description  243 non-null    str
 8   long_description   243 non-null    str
dtypes: float64(2), int64(4), str(3)
memory usage: 114.0 KB

In [231]:
interactions_df.head()

   user_id  product_id interaction_type          created_at
0      485         258               R5 2026-04-17 18:15:13
1      485         191               R5 2026-04-17 18:15:13
2      485         192     wishlist_add 2026-04-17 18:15:13
3      485         201     wishlist_add 2026-04-17 18:15:13
4      485         187               R5 2026-04-17 18:15:13

In [232]:
interactions_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10019 entries, 0 to 10018
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10019 non-null  int64
 1   product_id        10019 non-null  int64
 2   interaction_type  10019 non-null  str
 3   created_at        10019 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(2), str(1)
memory usage: 387.6 KB

## Train Test Split

In [233]:
def train_test_split_by_user(interactions,min_interactions=2): 
    train_rows = [] 
    test_rows = []

    for user_id, user_df in interactions.groupby("user_id"): 
        user_df = user_df.sort_values("created_at").reset_index(drop=True)
        if len(user_df) < min_interactions:
            train_rows.append(user_df)
            continue 
        train_part = user_df.iloc[:-1]
        test_part = user_df.iloc[-1:]

        train_rows.append(train_part)
        test_rows.append(test_part)
    train_interactions_df = pd.concat(train_rows).reset_index(drop=True)

    if len(test_rows) > 0:
        test_interactions_df = pd.concat(test_rows).reset_index(drop=True)
    else:
        test_interactions_df = pd.DataFrame(columns=interactions.columns)
    return train_interactions_df, test_interactions_df

In [234]:
train_interactions_df, test_interactions_df = train_test_split_by_user(interactions_df) 
print(f"Train interactions: {len(train_interactions_df)}")
print(f"Test interactions: {len(test_interactions_df)}")

Train interactions: 9519
Test interactions: 500

In [235]:
train_interactions_df.head()

   user_id  product_id interaction_type          created_at
0      485         258               R5 2026-04-17 18:15:13
1      485         186         cart_add 2026-04-17 18:15:13
2      485         253            click 2026-04-17 18:15:13
3      485         257               R4 2026-04-17 18:15:13
4      485         203         cart_add 2026-04-17 18:15:13

## Merge Train interactions with products

In [236]:
train_df = train_interactions_df.merge(products_df,left_on="product_id",right_on="id", how="inner")

In [237]:
train_df.head()

,user_id,product_id,interaction_type,created_at,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description
0,485,258,R5,2026-04-17 18:15:13,258,8,64,24,1299.0,1219.0,Apple MacBook Air M3 Laptop,<b>Apple MacBook Air M3 Laptop</b><p>Powerful ...,<b>Apple MacBook Air M3 Laptop</b><p>This MacB...
1,485,186,cart_add,2026-04-17 18:15:13,186,6,9,24,899.0,839.0,Apple iPhone X Smartphone,<b>Apple iPhone X Smartphone</b><p>Modern iPho...,<b>Apple iPhone X Smartphone</b><p>This smartp...
2,485,253,click,2026-04-17 18:15:13,253,7,16,8,21.0,17.0,Sony Battlefield Hardline Deluxe Edition Game ...,<b>Battlefield Hardline Deluxe Edition Game Di...,<b>Sony Battlefield Hardline Deluxe Edition Ga...
3,485,257,R4,2026-04-17 18:15:13,257,8,64,24,1099.0,1019.0,Apple MacBook Air M2 Laptop,<b>Apple MacBook Air M2 Laptop</b><p>Modern Ap...,<b>Apple MacBook Air M2 Laptop</b><p>This lapt...
4,485,203,cart_add,2026-04-17 18:15:13,203,6,10,24,499.0,459.0,Apple iPad Mini 6 Tablet,<b>Apple iPad Mini 6 Tablet</b><p>Compact tabl...,<b>Apple iPad Mini 6 Tablet</b><p>This small f...

## Encode User_id and Product_id

In [238]:
all_user_ids = sorted(interactions_df["user_id"].unique())
all_product_ids = sorted(products_df["id"].unique())

user_id_to_index = {user_id: idx for idx, user_id in enumerate(all_user_ids)} 
idx_to_user_id = {idx:user_id for user_id,idx in user_id_to_index.items()} 

product_id_to_index = {product_id: idx for idx, product_id in enumerate(all_product_ids)}
idx_to_product_id = {idx: product_id for product_id, idx in product_id_to_index.items()}

In [239]:
user_id_to_index[487],product_id_to_index[6],idx_to_product_id[1]

(2, 1, np.int64(6))

In [240]:
train_df["user_idx"] = train_df["user_id"].map(user_id_to_index)
train_df["product_idx"] = train_df["product_id"].map(product_id_to_index) 

products_df["product_idx"] = products_df["id"].map(product_id_to_index)

In [241]:
train_df.head()

,user_id,product_id,interaction_type,created_at,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description,user_idx,product_idx
0,485,258,R5,2026-04-17 18:15:13,258,8,64,24,1299.0,1219.0,Apple MacBook Air M3 Laptop,<b>Apple MacBook Air M3 Laptop</b><p>Powerful ...,<b>Apple MacBook Air M3 Laptop</b><p>This MacB...,0,220
1,485,186,cart_add,2026-04-17 18:15:13,186,6,9,24,899.0,839.0,Apple iPhone X Smartphone,<b>Apple iPhone X Smartphone</b><p>Modern iPho...,<b>Apple iPhone X Smartphone</b><p>This smartp...,0,170
2,485,253,click,2026-04-17 18:15:13,253,7,16,8,21.0,17.0,Sony Battlefield Hardline Deluxe Edition Game ...,<b>Battlefield Hardline Deluxe Edition Game Di...,<b>Sony Battlefield Hardline Deluxe Edition Ga...,0,215
3,485,257,R4,2026-04-17 18:15:13,257,8,64,24,1099.0,1019.0,Apple MacBook Air M2 Laptop,<b>Apple MacBook Air M2 Laptop</b><p>Modern Ap...,<b>Apple MacBook Air M2 Laptop</b><p>This lapt...,0,219
4,485,203,cart_add,2026-04-17 18:15:13,203,6,10,24,499.0,459.0,Apple iPad Mini 6 Tablet,<b>Apple iPad Mini 6 Tablet</b><p>Compact tabl...,<b>Apple iPad Mini 6 Tablet</b><p>This small f...,0,186

In [242]:
products_df.head()

,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description,product_idx
0,5,20,58,52,7.0,6.0,Nestle Ready Meal Bento Box,<b>Instant Food</b><p>Convenient ready meal wi...,<b>Nestle Ready Meal Bento Box</b><p>This read...,0
1,6,5,7,19,25.0,20.0,Nike Summer Cotton T-Shirt,<b>Summer T-Shirt</b><p>Breathable cotton t-sh...,<b>Nike Summer Cotton T-Shirt</b><p>This light...,1
2,7,5,4,6,35.0,29.0,Selons Knit Sweater,<b>Knit Sweater</b><p>Soft knit sweater design...,<b>Selons Knit Sweater</b><p>This sweater is m...,2
3,9,6,10,18,699.0,649.0,Samsung Galaxy Tab S9 5G,<b>Tablet</b><p>High performance tablet design...,<b>Samsung Galaxy Tab S9 5G</b><p>This tablet ...,3
4,10,7,14,12,39.0,34.0,Xiaomi Y68 Smart Watch,<b>Smart Watch</b><p>Affordable smart watch wi...,<b>Xiaomi Y68 Smart Watch</b><p>This smart wat...,4

## Encode category, sub_category, brand

In [243]:
category_ids = sorted(products_df["category_id"].unique())
sub_category_ids = sorted(products_df["sub_category_id"].unique())
brand_ids = sorted(products_df["brand_id"].unique())

category_id_to_index = {cat_id: idx for idx, cat_id in enumerate(category_ids)}
sub_category_id_to_index = {sub_cat_id: idx for idx, sub_cat_id in enumerate(sub_category_ids)}
brand_id_to_index = {brand_id: idx for idx, brand_id in enumerate(brand_ids)}

In [244]:
train_df["category_idx"] = train_df["category_id"].map(category_id_to_index)
train_df["sub_category_idx"] = train_df["sub_category_id"].map(sub_category_id_to_index)
train_df["brand_idx"] = train_df["brand_id"].map(brand_id_to_index)

products_df["category_idx"] = products_df["category_id"].map(category_id_to_index)
products_df["sub_category_idx"] = products_df["sub_category_id"].map(sub_category_id_to_index)
products_df["brand_idx"] = products_df["brand_id"].map(brand_id_to_index)

In [245]:
train_df.head()

,user_id,product_id,interaction_type,created_at,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description,user_idx,product_idx,category_idx,sub_category_idx,brand_idx
0,485,258,R5,2026-04-17 18:15:13,258,8,64,24,1299.0,1219.0,Apple MacBook Air M3 Laptop,<b>Apple MacBook Air M3 Laptop</b><p>Powerful ...,<b>Apple MacBook Air M3 Laptop</b><p>This MacB...,0,220,3,27,9
1,485,186,cart_add,2026-04-17 18:15:13,186,6,9,24,899.0,839.0,Apple iPhone X Smartphone,<b>Apple iPhone X Smartphone</b><p>Modern iPho...,<b>Apple iPhone X Smartphone</b><p>This smartp...,0,170,1,6,9
2,485,253,click,2026-04-17 18:15:13,253,7,16,8,21.0,17.0,Sony Battlefield Hardline Deluxe Edition Game ...,<b>Battlefield Hardline Deluxe Edition Game Di...,<b>Sony Battlefield Hardline Deluxe Edition Ga...,0,215,2,12,1
3,485,257,R4,2026-04-17 18:15:13,257,8,64,24,1099.0,1019.0,Apple MacBook Air M2 Laptop,<b>Apple MacBook Air M2 Laptop</b><p>Modern Ap...,<b>Apple MacBook Air M2 Laptop</b><p>This lapt...,0,219,3,27,9
4,485,203,cart_add,2026-04-17 18:15:13,203,6,10,24,499.0,459.0,Apple iPad Mini 6 Tablet,<b>Apple iPad Mini 6 Tablet</b><p>Compact tabl...,<b>Apple iPad Mini 6 Tablet</b><p>This small f...,0,186,1,7,9

In [246]:
products_df.head()

,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description,product_idx,category_idx,sub_category_idx,brand_idx
0,5,20,58,52,7.0,6.0,Nestle Ready Meal Bento Box,<b>Instant Food</b><p>Convenient ready meal wi...,<b>Nestle Ready Meal Bento Box</b><p>This read...,0,6,25,19
1,6,5,7,19,25.0,20.0,Nike Summer Cotton T-Shirt,<b>Summer T-Shirt</b><p>Breathable cotton t-sh...,<b>Nike Summer Cotton T-Shirt</b><p>This light...,1,0,4,4
2,7,5,4,6,35.0,29.0,Selons Knit Sweater,<b>Knit Sweater</b><p>Soft knit sweater design...,<b>Selons Knit Sweater</b><p>This sweater is m...,2,0,1,0
3,9,6,10,18,699.0,649.0,Samsung Galaxy Tab S9 5G,<b>Tablet</b><p>High performance tablet design...,<b>Samsung Galaxy Tab S9 5G</b><p>This tablet ...,3,1,7,3
4,10,7,14,12,39.0,34.0,Xiaomi Y68 Smart Watch,<b>Smart Watch</b><p>Affordable smart watch wi...,<b>Xiaomi Y68 Smart Watch</b><p>This smart wat...,4,2,10,2

## Normalize Price and offer_price

In [247]:
def get_mean_std(df,col): 
    mean = df[col].mean()
    std = df[col].std() 
    if std == 0: 
        std = 1.0
    return mean, std

In [248]:
price_mean,price_std = get_mean_std(products_df,"price") 
offer_price_mean, offer_price_std = get_mean_std(products_df,"offer_price") 

train_df["price_norm"] = (train_df["price"] - price_mean) / price_std
train_df["offer_price_norm"] = (train_df["offer_price"] - offer_price_mean) / offer_price_std

products_df["price_norm"] = (products_df["price"] - price_mean) / price_std
products_df["offer_price_norm"] = (products_df["offer_price"] - offer_price_mean) / offer_price_std

In [249]:
train_df.head()

,user_id,product_id,interaction_type,created_at,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description,user_idx,product_idx,category_idx,sub_category_idx,brand_idx,price_norm,offer_price_norm
0,485,258,R5,2026-04-17 18:15:13,258,8,64,24,1299.0,1219.0,Apple MacBook Air M3 Laptop,<b>Apple MacBook Air M3 Laptop</b><p>Powerful ...,<b>Apple MacBook Air M3 Laptop</b><p>This MacB...,0,220,3,27,9,0.384334,0.386462
1,485,186,cart_add,2026-04-17 18:15:13,186,6,9,24,899.0,839.0,Apple iPhone X Smartphone,<b>Apple iPhone X Smartphone</b><p>Modern iPho...,<b>Apple iPhone X Smartphone</b><p>This smartp...,0,170,1,6,9,0.162667,0.162879
2,485,253,click,2026-04-17 18:15:13,253,7,16,8,21.0,17.0,Sony Battlefield Hardline Deluxe Edition Game ...,<b>Battlefield Hardline Deluxe Edition Game Di...,<b>Sony Battlefield Hardline Deluxe Edition Ga...,0,215,2,12,1,-0.323891,-0.320767
3,485,257,R4,2026-04-17 18:15:13,257,8,64,24,1099.0,1019.0,Apple MacBook Air M2 Laptop,<b>Apple MacBook Air M2 Laptop</b><p>Modern Ap...,<b>Apple MacBook Air M2 Laptop</b><p>This lapt...,0,219,3,27,9,0.273501,0.268787
4,485,203,cart_add,2026-04-17 18:15:13,203,6,10,24,499.0,459.0,Apple iPad Mini 6 Tablet,<b>Apple iPad Mini 6 Tablet</b><p>Compact tabl...,<b>Apple iPad Mini 6 Tablet</b><p>This small f...,0,186,1,7,9,-0.058999,-0.060705

## Vectorize Text

In [250]:
def clean_text(text): 
    if pd.isna(text):
        return ""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", "", text)
    return text

In [251]:
products_df["full_text"] = (
    products_df["name"].fillna("") + " " +
    products_df["short_description"].fillna("") + " " +
    products_df["long_description"].fillna("")
).apply(clean_text) 

tfidf_vectorizer = TfidfVectorizer(max_features=1000)
tfidf_matrix = tfidf_vectorizer.fit_transform(products_df["full_text"])

# Convert sparse matrix to dense 
tfidf_array = tfidf_matrix.toarray() 
tfidf_dim = tfidf_array.shape[1] 

#Add TF-IDF features to products_df
products_df["text_tfidf"] = list(tfidf_array)

# Map product_idx to text_tfidf 
product_idx_to_tfidf = dict(zip(products_df["product_idx"], products_df["text_tfidf"]))  

# Add text_tfidf to train_df by mapping product_idx
train_df["text_tfidf"] = train_df["product_idx"].map(product_idx_to_tfidf) 


print("\nTF-IDF dimensions:", tfidf_dim)
print("Sample TF-IDF vector for first product:", products_df["text_tfidf"].iloc[0])

TF-IDF dimensions: 1000
Sample TF-IDF vector for first product: [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.13470555 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.08477332 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.3001722  0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.11769092 0.         0.         0.         0.         0.
 0.         0.         0.         0.13216202 0.         0.
 0.         0.         0.12639175 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.10375302 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.07015488 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.04078447 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.09054359 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.0932681  0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.10600304 0.         0.         0.         0.
 0.         0.         0.         0.13960119 0.14565465 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.09186998
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.04294884 0.03861321 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.10600304 0.         0.         0.         0.         0.
 0.         0.         0.11769092 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.58845461
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.11769092 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.05741993 0.08375911 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.07463551 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.05535011 0.
 0.         0.         0.         0.11769092 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.22847587 0.         0.
 0.         0.45025831 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.13960119
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.12639175
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.08093533 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.09798275 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.04116475 0.11423794 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]

## Interaction Weight Handling

In [252]:
interaction_weight_map={
    "click": 1.0,
    "wishlist_add": 2.0,
    "cart_add": 3.0,
    "R4": 4.0,
    "R5": 5.0
}

In [253]:
train_df["interaction_weight"] = train_df["interaction_type"].map(interaction_weight_map).fillna(0.0)

In [254]:
train_df.head()

,user_id,product_id,interaction_type,created_at,id,category_id,sub_category_id,brand_id,price,offer_price,...,long_description,user_idx,product_idx,category_idx,sub_category_idx,brand_idx,price_norm,offer_price_norm,text_tfidf,interaction_weight
0,485,258,R5,2026-04-17 18:15:13,258,8,64,24,1299.0,1219.0,...,<b>Apple MacBook Air M3 Laptop</b><p>This MacB...,0,220,3,27,9,0.384334,0.386462,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",5.0
1,485,186,cart_add,2026-04-17 18:15:13,186,6,9,24,899.0,839.0,...,<b>Apple iPhone X Smartphone</b><p>This smartp...,0,170,1,6,9,0.162667,0.162879,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",3.0
2,485,253,click,2026-04-17 18:15:13,253,7,16,8,21.0,17.0,...,<b>Sony Battlefield Hardline Deluxe Edition Ga...,0,215,2,12,1,-0.323891,-0.320767,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1.0
3,485,257,R4,2026-04-17 18:15:13,257,8,64,24,1099.0,1019.0,...,<b>Apple MacBook Air M2 Laptop</b><p>This lapt...,0,219,3,27,9,0.273501,0.268787,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",4.0
4,485,203,cart_add,2026-04-17 18:15:13,203,6,10,24,499.0,459.0,...,<b>Apple iPad Mini 6 Tablet</b><p>This small f...,0,186,1,7,9,-0.058999,-0.060705,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",3.0

## Custom Dataset

In [255]:
class TwoTowerDataset(Dataset):
    def __init__(self,df): 
        self.df = df.reset_index(drop=True)
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        row = self.df.iloc[idx] 
        return {
            "user_idx": torch.tensor(row["user_idx"], dtype=torch.long),
            "product_idx": torch.tensor(row["product_idx"], dtype=torch.long),
            "category_idx": torch.tensor(row["category_idx"], dtype=torch.long),
            "sub_category_idx": torch.tensor(row["sub_category_idx"], dtype=torch.long),
            "brand_idx": torch.tensor(row["brand_idx"], dtype=torch.long),
            "price_norm": torch.tensor(row["price_norm"], dtype=torch.float),
            "offer_price_norm": torch.tensor(row["offer_price_norm"], dtype=torch.float),
            "text_tfidf": torch.tensor(row["text_tfidf"], dtype=torch.float),
            "interaction_weight": torch.tensor(row["interaction_weight"], dtype=torch.float)    
        }

In [256]:
dataset = TwoTowerDataset(train_df)
dataset[0]

{'user_idx': tensor(0),
 'product_idx': tensor(220),
 'category_idx': tensor(3),
 'sub_category_idx': tensor(27),
 'brand_idx': tensor(9),
 'price_norm': tensor(0.3843),
 'offer_price_norm': tensor(0.3865),
 'text_tfidf': tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.4453,
         0.0000, 0.0000, 0.0000, 0.0712, 0.0000, 0.0000, 0.0000, 0.0000, 0.2213,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1476, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0698, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1164, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0721, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0618,
         0.0000, 0.0000, 0.0389, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0567, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0934, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1230,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0424, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0822, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.1026, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0955, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0378, 0.0340, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.3735, 0.0934, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0798, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3689, 0.0000, 0.4453,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0879, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0618, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0879,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0738, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0522, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0640,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0729, 0.0955, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1113, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.1072, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0629, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0776, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0468, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0835, 0.1037, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1164, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0879, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0482, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0407, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0725, 0.0000, 0.0000, 0.1410, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]),
 'interaction_weight': tensor(5.)}

In [257]:
dataloader = DataLoader(dataset, batch_size=64, shuffle=True)

In [258]:
first_batch = next(iter(dataloader))
print("User indices:", first_batch["user_idx"])
print("Product indices:", first_batch["product_idx"])
print("Category indices:", first_batch["category_idx"])
print("Sub-category indices:", first_batch["sub_category_idx"])  
print("price_norm:", first_batch["price_norm"])

User indices: tensor([ 86, 114,  92, 205, 141,  57, 414, 342, 303,  66, 402,  79, 301, 410,
        266, 331,  39, 192, 168, 446, 217, 360, 112, 292, 442, 393, 429, 462,
        424, 304, 257,  88,  66, 409, 458, 213,  92, 497, 450,  68, 152, 462,
         28, 458, 317, 413, 111, 456,   6, 191, 274, 468, 137, 220, 317, 273,
        210, 238, 354, 338, 343, 421, 288, 405])
Product indices: tensor([182, 191, 181, 196,  45, 197, 222, 220,  38, 187,  26, 204,   5, 127,
         60, 220, 186,  50, 169,  90, 203, 155,   3, 215,   2,  28,  11, 229,
         97,   5,  47, 200,  44, 135, 236,  44, 178,   0,  81, 195, 169, 237,
         43, 231, 221,  15, 181, 234, 173, 203,  61, 236, 189,  50,  74, 207,
        195, 207,   2, 222,  70,  62,  46, 121])
Category indices: tensor([1, 1, 1, 2, 2, 2, 3, 3, 1, 1, 0, 2, 2, 4, 2, 3, 1, 2, 1, 5, 2, 6, 1, 2,
        0, 0, 0, 7, 5, 2, 2, 2, 2, 4, 7, 2, 1, 6, 5, 2, 1, 7, 1, 7, 3, 0, 1, 7,
        1, 2, 2, 7, 1, 2, 3, 2, 2, 2, 0, 3, 3, 2, 2, 4])
Sub-category indices: tensor([ 6,  7,  6, 10, 10, 10, 27, 27,  7,  7,  1, 10, 11, 18, 12, 27,  7, 10,
         6, 26, 10, 25,  7, 12,  1,  3,  5, 28, 26, 11, 11, 10, 10, 19, 28, 10,
         6, 25, 26, 10,  6, 28,  9, 28, 27,  3,  6, 28,  6, 10, 12, 28,  7, 10,
        15, 12, 10, 12,  1, 27, 16, 12, 11, 17])
price_norm: tensor([ 0.2735, -0.1975,  0.0518, -0.1975, -0.2474, -0.0978,  0.1073,  0.3843,
        -0.1532,  0.3289, -0.3111, -0.1809, -0.1698, -0.2330, -0.2973,  0.3843,
        -0.0590, -0.2640, -0.2474, -0.3134, -0.2252, -0.3333,  0.0518, -0.3239,
        -0.3161, -0.3139, -0.3145, -0.3195, -0.3034, -0.1698, -0.2973, -0.0867,
        -0.1698, -0.3178, -0.3217, -0.1698,  0.1627, -0.3316, -0.3250,  0.1073,
        -0.2474, -0.3289, -0.2973, -0.3206,  0.6614, -0.3161,  0.0518, -0.3211,
         0.3289, -0.2252, -0.2973, -0.3217,  0.2181, -0.2640, -0.2086, -0.3139,
         0.1073, -0.3139, -0.3161,  0.1073, -0.3222, -0.2973, -0.0590,  0.5788])

## Two Tower Model

In [259]:
class TwoTowerModel(nn.Module): 
    def __init__(
        self,
        num_users,
        num_products,
        num_categories,
        num_sub_categories,
        num_brands,
        tfidf_dim, 
        embedding_dim=64, 
        hidden_dim= 64 * 8
    ):
        super().__init__()
        self.embedding_dim = embedding_dim 

        # --------- User Tower  ---------
        self.user_embedding = nn.Embedding(num_users, embedding_dim) 
        self.user_tower = nn.Sequential(
            nn.Linear(embedding_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, embedding_dim)
        )
        # --------- User Tower  --------- 

        # --------- Categorical item embeddings ---------
        self.product_embedding = nn.Embedding(num_products, embedding_dim)
        self.category_embedding = nn.Embedding(num_categories, embedding_dim)
        self.sub_category_embedding = nn.Embedding(num_sub_categories, embedding_dim)
        self.brand_embedding = nn.Embedding(num_brands, embedding_dim)
        # --------- Categorical item embeddings ---------

        # --------- Numerical item features ---------
        self.price_projection = nn.Linear(2, embedding_dim) #[B,embedding_dim] <= [B,2] = [B, price_norm . offer_price_norm]
        # --------- Numerical item features ---------

        # --------- Textual item features ---------
        self.text_projection = nn.Linear(tfidf_dim, embedding_dim) #[B,embedding_dim] <= [B, tfidf_dim]
        # --------- Textual item features ---------

        # --------- Item Tower ---------
        item_input_dim = embedding_dim * 6 # product_emb + category_emb + sub_category_emb + brand_emb + price_emb + text_emb
        self.item_tower = nn.Sequential(
            nn.Linear(item_input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, embedding_dim)
        )
        # --------- Item Tower ---------
    def encode_user(self, user_idx): 
        user_emb = self.user_embedding(user_idx) #[B, embedding_dim] 
        user_vector = self.user_tower(user_emb) #[B, embedding_dim]
        user_vector = F.normalize(user_vector, dim=1)
        return user_vector
    def encode_item(
        self,
        product_idx,
        category_idx,
        sub_category_idx,
        brand_idx,
        price_norm,
        offer_price_norm,
        text_tfidf
    ): 
        product_emb = self.product_embedding(product_idx) #[B,embedding_dim] 
        category_emb = self.category_embedding(category_idx) #[B,embedding_dim]
        sub_category_emb = self.sub_category_embedding(sub_category_idx) #[B,embedding_dim]
        brand_emb = self.brand_embedding(brand_idx) #[B,embedding_dim]
        
        price_features = torch.stack([price_norm, offer_price_norm], dim=1) #[B,2] <= stack([B],[B])
        price_emb = self.price_projection(price_features) #[B,embedding_dim]  

        text_emb = self.text_projection(text_tfidf) #[B,embedding_dim] <= [B, tfidf_dim]

        item_vector = torch.cat(
            [product_emb, category_emb, sub_category_emb, brand_emb, price_emb, text_emb], dim=1
        ) #[B, embedding_dim * 6]

        item_vector = self.item_tower(item_vector) #[B, embedding_dim]
        item_vector = F.normalize(item_vector, dim=1)
        return item_vector
    def forward(self,batch): 

        user_vector = self.encode_user(batch["user_idx"]) #[B, embedding_dim]
        item_vector = self.encode_item(
            batch["product_idx"],
            batch["category_idx"],
            batch["sub_category_idx"],
            batch["brand_idx"],
            batch["price_norm"],
            batch["offer_price_norm"],
            batch["text_tfidf"]
        )  #[B, embedding_dim]

        #In batch negative sampling 
        scores = user_vector @ item_vector.T #[B,B] 
        return scores

In [260]:
num_users = len(user_id_to_index)
num_products = len(product_id_to_index)
num_categories = len(category_id_to_index)
num_sub_categories = len(sub_category_id_to_index)
num_brands = len(brand_id_to_index)

In [261]:
model = TwoTowerModel(
    num_users=num_users,
    num_products=num_products,
    num_categories=num_categories,
    num_sub_categories=num_sub_categories,
    num_brands=num_brands,
    tfidf_dim=tfidf_dim,
    embedding_dim=64,
    hidden_dim=64 * 8
).to(device)

In [262]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

## Training Loop

In [263]:
num_epochs = 300 
for epoch in range(num_epochs):
    model.train() 
    total_loss = 0.0
    for batch in dataloader:
        batch = {k:v.to(device) for k,v in batch.items()}

        #1. Forward pass
        scores = model(batch) #[B,B] 

        #2. Compute loss 
        labels = torch.arange(scores.size(0)).to(device) #[0,1,2,...B-1] 
        loss_per_sample = F.cross_entropy(scores, labels, reduction="none") #[B]
        loss = (loss_per_sample * batch["interaction_weight"]).mean()

        #3. Backward pass 
        optimizer.zero_grad()
        loss.backward()

        #4. Update parameters
        optimizer.step()

        total_loss += loss.item() 
    avg_loss = total_loss / len(dataloader)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_loss:.4f}")

Epoch 1/300, Loss: 10.8816
Epoch 2/300, Loss: 9.8541
Epoch 3/300, Loss: 9.7527
Epoch 4/300, Loss: 9.7290
Epoch 5/300, Loss: 9.7081
Epoch 6/300, Loss: 9.7037
Epoch 7/300, Loss: 9.7006
Epoch 8/300, Loss: 9.6978
Epoch 9/300, Loss: 9.6970
Epoch 10/300, Loss: 9.6950
Epoch 11/300, Loss: 9.6920
Epoch 12/300, Loss: 9.6937
Epoch 13/300, Loss: 9.6927
Epoch 14/300, Loss: 9.6907
Epoch 15/300, Loss: 9.6871
Epoch 16/300, Loss: 9.6837
Epoch 17/300, Loss: 9.6843
Epoch 18/300, Loss: 9.6859
Epoch 19/300, Loss: 9.6797
Epoch 20/300, Loss: 9.6769
Epoch 21/300, Loss: 9.6827
Epoch 22/300, Loss: 9.6760
Epoch 23/300, Loss: 9.6760
Epoch 24/300, Loss: 9.6785
Epoch 25/300, Loss: 9.6818
Epoch 26/300, Loss: 9.6761
Epoch 27/300, Loss: 9.6786
Epoch 28/300, Loss: 9.6793
Epoch 29/300, Loss: 9.6715
Epoch 30/300, Loss: 9.6756
Epoch 31/300, Loss: 9.6735
Epoch 32/300, Loss: 9.6737
Epoch 33/300, Loss: 9.6754
Epoch 34/300, Loss: 9.6726
Epoch 35/300, Loss: 9.6742
Epoch 36/300, Loss: 9.6757
Epoch 37/300, Loss: 9.6753
Epoch 38/300, Loss: 9.6722
Epoch 39/300, Loss: 9.6755
Epoch 40/300, Loss: 9.6704
Epoch 41/300, Loss: 9.6696
Epoch 42/300, Loss: 9.6762
Epoch 43/300, Loss: 9.6779
Epoch 44/300, Loss: 9.6666
Epoch 45/300, Loss: 9.6686
Epoch 46/300, Loss: 9.6746
Epoch 47/300, Loss: 9.6764
Epoch 48/300, Loss: 9.6707
Epoch 49/300, Loss: 9.6700
Epoch 50/300, Loss: 9.6704
Epoch 51/300, Loss: 9.6692
Epoch 52/300, Loss: 9.6685
Epoch 53/300, Loss: 9.6671
Epoch 54/300, Loss: 9.6725
Epoch 55/300, Loss: 9.6706
Epoch 56/300, Loss: 9.6705
Epoch 57/300, Loss: 9.6643
Epoch 58/300, Loss: 9.6694
Epoch 59/300, Loss: 9.6672
Epoch 60/300, Loss: 9.6675
Epoch 61/300, Loss: 9.6674
Epoch 62/300, Loss: 9.6695
Epoch 63/300, Loss: 9.6696
Epoch 64/300, Loss: 9.6649
Epoch 65/300, Loss: 9.6676
Epoch 66/300, Loss: 9.6659
Epoch 67/300, Loss: 9.6690
Epoch 68/300, Loss: 9.6642
Epoch 69/300, Loss: 9.6666
Epoch 70/300, Loss: 9.6660
Epoch 71/300, Loss: 9.6654
Epoch 72/300, Loss: 9.6667
Epoch 73/300, Loss: 9.6737
Epoch 74/300, Loss: 9.6722
Epoch 75/300, Loss: 9.6703
Epoch 76/300, Loss: 9.6653
Epoch 77/300, Loss: 9.6698
Epoch 78/300, Loss: 9.6688
Epoch 79/300, Loss: 9.6666
Epoch 80/300, Loss: 9.6652
Epoch 81/300, Loss: 9.6647
Epoch 82/300, Loss: 9.6628
Epoch 83/300, Loss: 9.6637
Epoch 84/300, Loss: 9.6677
Epoch 85/300, Loss: 9.6669
Epoch 86/300, Loss: 9.6657
Epoch 87/300, Loss: 9.6687
Epoch 88/300, Loss: 9.6638
Epoch 89/300, Loss: 9.6622
Epoch 90/300, Loss: 9.6690
Epoch 91/300, Loss: 9.6644
Epoch 92/300, Loss: 9.6644
Epoch 93/300, Loss: 9.6696
Epoch 94/300, Loss: 9.6627
Epoch 95/300, Loss: 9.6647
Epoch 96/300, Loss: 9.6648
Epoch 97/300, Loss: 9.6606
Epoch 98/300, Loss: 9.6639
Epoch 99/300, Loss: 9.6663
Epoch 100/300, Loss: 9.6638
Epoch 101/300, Loss: 9.6677
Epoch 102/300, Loss: 9.6630
Epoch 103/300, Loss: 9.6650
Epoch 104/300, Loss: 9.6646
Epoch 105/300, Loss: 9.6658
Epoch 106/300, Loss: 9.6684
Epoch 107/300, Loss: 9.6643
Epoch 108/300, Loss: 9.6668
Epoch 109/300, Loss: 9.6626
Epoch 110/300, Loss: 9.6591
Epoch 111/300, Loss: 9.6614
Epoch 112/300, Loss: 9.6691
Epoch 113/300, Loss: 9.6622
Epoch 114/300, Loss: 9.6598
Epoch 115/300, Loss: 9.6616
Epoch 116/300, Loss: 9.6651
Epoch 117/300, Loss: 9.6581
Epoch 118/300, Loss: 9.6674
Epoch 119/300, Loss: 9.6568
Epoch 120/300, Loss: 9.6658
Epoch 121/300, Loss: 9.6586
Epoch 122/300, Loss: 9.6588
Epoch 123/300, Loss: 9.6627
Epoch 124/300, Loss: 9.6590
Epoch 125/300, Loss: 9.6631
Epoch 126/300, Loss: 9.6638
Epoch 127/300, Loss: 9.6612
Epoch 128/300, Loss: 9.6654
Epoch 129/300, Loss: 9.6605
Epoch 130/300, Loss: 9.6593
Epoch 131/300, Loss: 9.6633
Epoch 132/300, Loss: 9.6632
Epoch 133/300, Loss: 9.6636
Epoch 134/300, Loss: 9.6617
Epoch 135/300, Loss: 9.6626
Epoch 136/300, Loss: 9.6630
Epoch 137/300, Loss: 9.6584
Epoch 138/300, Loss: 9.6622
Epoch 139/300, Loss: 9.6616
Epoch 140/300, Loss: 9.6557
Epoch 141/300, Loss: 9.6627
Epoch 142/300, Loss: 9.6594
Epoch 143/300, Loss: 9.6618
Epoch 144/300, Loss: 9.6577
Epoch 145/300, Loss: 9.6671
Epoch 146/300, Loss: 9.6580
Epoch 147/300, Loss: 9.6633
Epoch 148/300, Loss: 9.6590
Epoch 149/300, Loss: 9.6609
Epoch 150/300, Loss: 9.6627
Epoch 151/300, Loss: 9.6588
Epoch 152/300, Loss: 9.6568
Epoch 153/300, Loss: 9.6626
Epoch 154/300, Loss: 9.6597
Epoch 155/300, Loss: 9.6621
Epoch 156/300, Loss: 9.6604
Epoch 157/300, Loss: 9.6613
Epoch 158/300, Loss: 9.6618
Epoch 159/300, Loss: 9.6604
Epoch 160/300, Loss: 9.6603
Epoch 161/300, Loss: 9.6659
Epoch 162/300, Loss: 9.6603
Epoch 163/300, Loss: 9.6605
Epoch 164/300, Loss: 9.6606
Epoch 165/300, Loss: 9.6593
Epoch 166/300, Loss: 9.6575
Epoch 167/300, Loss: 9.6603
Epoch 168/300, Loss: 9.6608
Epoch 169/300, Loss: 9.6625
Epoch 170/300, Loss: 9.6629
Epoch 171/300, Loss: 9.6580
Epoch 172/300, Loss: 9.6575
Epoch 173/300, Loss: 9.6610
Epoch 174/300, Loss: 9.6573
Epoch 175/300, Loss: 9.6596
Epoch 176/300, Loss: 9.6584
Epoch 177/300, Loss: 9.6579
Epoch 178/300, Loss: 9.6596
Epoch 179/300, Loss: 9.6592
Epoch 180/300, Loss: 9.6568
Epoch 181/300, Loss: 9.6624
Epoch 182/300, Loss: 9.6594
Epoch 183/300, Loss: 9.6598
Epoch 184/300, Loss: 9.6613
Epoch 185/300, Loss: 9.6607
Epoch 186/300, Loss: 9.6579
Epoch 187/300, Loss: 9.6550
Epoch 188/300, Loss: 9.6583
Epoch 189/300, Loss: 9.6560
Epoch 190/300, Loss: 9.6531
Epoch 191/300, Loss: 9.6600
Epoch 192/300, Loss: 9.6585
Epoch 193/300, Loss: 9.6561
Epoch 194/300, Loss: 9.6587
Epoch 195/300, Loss: 9.6594
Epoch 196/300, Loss: 9.6599
Epoch 197/300, Loss: 9.6608
Epoch 198/300, Loss: 9.6585
Epoch 199/300, Loss: 9.6567
Epoch 200/300, Loss: 9.6600
Epoch 201/300, Loss: 9.6628
Epoch 202/300, Loss: 9.6585
Epoch 203/300, Loss: 9.6559
Epoch 204/300, Loss: 9.6579
Epoch 205/300, Loss: 9.6610
Epoch 206/300, Loss: 9.6550
Epoch 207/300, Loss: 9.6546
Epoch 208/300, Loss: 9.6564
Epoch 209/300, Loss: 9.6573
Epoch 210/300, Loss: 9.6585
Epoch 211/300, Loss: 9.6576
Epoch 212/300, Loss: 9.6618
Epoch 213/300, Loss: 9.6561
Epoch 214/300, Loss: 9.6598
Epoch 215/300, Loss: 9.6574
Epoch 216/300, Loss: 9.6509
Epoch 217/300, Loss: 9.6594
Epoch 218/300, Loss: 9.6574
Epoch 219/300, Loss: 9.6545
Epoch 220/300, Loss: 9.6590
Epoch 221/300, Loss: 9.6572
Epoch 222/300, Loss: 9.6589
Epoch 223/300, Loss: 9.6611
Epoch 224/300, Loss: 9.6595
Epoch 225/300, Loss: 9.6595
Epoch 226/300, Loss: 9.6595
Epoch 227/300, Loss: 9.6550
Epoch 228/300, Loss: 9.6582
Epoch 229/300, Loss: 9.6581
Epoch 230/300, Loss: 9.6564
Epoch 231/300, Loss: 9.6576
Epoch 232/300, Loss: 9.6553
Epoch 233/300, Loss: 9.6546
Epoch 234/300, Loss: 9.6613
Epoch 235/300, Loss: 9.6561
Epoch 236/300, Loss: 9.6570
Epoch 237/300, Loss: 9.6615
Epoch 238/300, Loss: 9.6555
Epoch 239/300, Loss: 9.6604
Epoch 240/300, Loss: 9.6615
Epoch 241/300, Loss: 9.6578
Epoch 242/300, Loss: 9.6621
Epoch 243/300, Loss: 9.6599
Epoch 244/300, Loss: 9.6538
Epoch 245/300, Loss: 9.6562
Epoch 246/300, Loss: 9.6580
Epoch 247/300, Loss: 9.6534
Epoch 248/300, Loss: 9.6576
Epoch 249/300, Loss: 9.6661
Epoch 250/300, Loss: 9.6590
Epoch 251/300, Loss: 9.6578
Epoch 252/300, Loss: 9.6551
Epoch 253/300, Loss: 9.6586
Epoch 254/300, Loss: 9.6623
Epoch 255/300, Loss: 9.6538
Epoch 256/300, Loss: 9.6580
Epoch 257/300, Loss: 9.6612
Epoch 258/300, Loss: 9.6561
Epoch 259/300, Loss: 9.6560
Epoch 260/300, Loss: 9.6573
Epoch 261/300, Loss: 9.6581
Epoch 262/300, Loss: 9.6590
Epoch 263/300, Loss: 9.6584
Epoch 264/300, Loss: 9.6566
Epoch 265/300, Loss: 9.6539
Epoch 266/300, Loss: 9.6590
Epoch 267/300, Loss: 9.6557
Epoch 268/300, Loss: 9.6577
Epoch 269/300, Loss: 9.6591
Epoch 270/300, Loss: 9.6601
Epoch 271/300, Loss: 9.6551
Epoch 272/300, Loss: 9.6511
Epoch 273/300, Loss: 9.6585
Epoch 274/300, Loss: 9.6634
Epoch 275/300, Loss: 9.6572
Epoch 276/300, Loss: 9.6572
Epoch 277/300, Loss: 9.6567
Epoch 278/300, Loss: 9.6558
Epoch 279/300, Loss: 9.6530
Epoch 280/300, Loss: 9.6553
Epoch 281/300, Loss: 9.6578
Epoch 282/300, Loss: 9.6604
Epoch 283/300, Loss: 9.6509
Epoch 284/300, Loss: 9.6569
Epoch 285/300, Loss: 9.6512
Epoch 286/300, Loss: 9.6584
Epoch 287/300, Loss: 9.6566
Epoch 288/300, Loss: 9.6602
Epoch 289/300, Loss: 9.6579
Epoch 290/300, Loss: 9.6616
Epoch 291/300, Loss: 9.6567
Epoch 292/300, Loss: 9.6613
Epoch 293/300, Loss: 9.6573
Epoch 294/300, Loss: 9.6542
Epoch 295/300, Loss: 9.6572
Epoch 296/300, Loss: 9.6574
Epoch 297/300, Loss: 9.6564
Epoch 298/300, Loss: 9.6579
Epoch 299/300, Loss: 9.6525
Epoch 300/300, Loss: 9.6531

## Product Tensors for evaluation

In [264]:
def build_all_product_tensors(products_df): 
    product_feautures = {
        "product_idx": torch.tensor(products_df["product_idx"].values, dtype=torch.long),
        "category_idx": torch.tensor(products_df["category_idx"].values, dtype=torch.long),
        "sub_category_idx": torch.tensor(products_df["sub_category_idx"].values, dtype=torch.long),
        "brand_idx": torch.tensor(products_df["brand_idx"].values, dtype=torch.long),
        "price_norm": torch.tensor(products_df["price_norm"].values, dtype=torch.float),
        "offer_price_norm": torch.tensor(products_df["offer_price_norm"].values, dtype=torch.float),
        "text_tfidf": torch.tensor(products_df["text_tfidf"].tolist(), dtype=torch.float)
    }
    return product_feautures

In [265]:
all_product_features = build_all_product_tensors(products_df)

## Recommend Function

In [266]:
def recommend_by_user(
    model,
    user_id,
    products_df, 
    all_product_features,
    k=10, 
    exclude_product_ids = None
): 
    model.eval() 
    if exclude_product_ids is None:
        exclude_product_ids = set()
    if user_id not in user_id_to_index:
        print(f"User ID {user_id} not found in training data.")
        return []
    user_idx = user_id_to_index[user_id]

    with torch.no_grad(): 
        user_tensor = torch.tensor([user_idx],dtype=torch.long).to(device) #[1] 
        user_vector = model.encode_user(user_tensor) #[1, embedding_dim] 

        product_features = {k:v.to(device) for k,v in all_product_features.items()}

        item_vector = model.encode_item(
            product_features["product_idx"],
            product_features["category_idx"],
            product_features["sub_category_idx"],
            product_features["brand_idx"],
            product_features["price_norm"],
            product_features["offer_price_norm"],
            product_features["text_tfidf"]
        ) #[num_products, embedding_dim] 

        scores = torch.matmul(user_vector, item_vector.T) #[1, num_products] 
        scores = scores.squeeze(0) #[num_products]

        results_df = products_df.copy()
        results_df["score"] = scores.cpu().numpy()
        if len(exclude_product_ids) > 0:
            results_df = results_df[~results_df["id"].isin(exclude_product_ids)]
        top_k = results_df.sort_values("score", ascending=False).head(k)
        return top_k["id"].tolist()

## Evaluation

In [267]:
def hit_at_k(recommended_items,ground_truth_item):
    return 1.0 if ground_truth_item in recommended_items else 0.0
def recall_at_k(recommended_items, ground_truth_items):
    if len(ground_truth_items) == 0:
        return 0.0
    hits = sum([1.0 for item in recommended_items if item in ground_truth_items])
    return hits / len(ground_truth_items)
def ndcg_at_k(recommended_items, ground_truth_items):
    dcg = 0.0
    for rank,item_id in enumerate(recommended_items, start=1):
        if item_id in ground_truth_items:
            dcg += 1.0 / math.log2(rank + 1)
    ideal_hits = min(len(ground_truth_items), len(recommended_items))
    idcg = 0.0 
    for rank in range(1, ideal_hits + 1):
        idcg += 1.0 / math.log2(rank + 1)
    if idcg == 0:
        return 0.0
    return dcg / idcg

In [268]:
def evaluate_model(model, train_interactions_df, test_interactions_df, products_df, all_product_features, k=10):
    model.eval() 
    hit_scores =[] 
    recall_scores = []
    ndcg_scores = []
    test_users = test_interactions_df["user_id"].unique() 
    for user_id in test_users: 
        ground_truth_items = test_interactions_df[test_interactions_df["user_id"] == user_id]["product_id"].tolist()
        seen_train_items = train_interactions_df[train_interactions_df["user_id"] == user_id]["product_id"].tolist()

        recommended_items = recommend_by_user(
            model,
            user_id,
            products_df,
            all_product_features,
            k=k,
            exclude_product_ids=set(seen_train_items)
        )
        hit_scores.append(hit_at_k(recommended_items, ground_truth_items))
        recall_scores.append(recall_at_k(recommended_items, ground_truth_items))
        ndcg_scores.append(ndcg_at_k(recommended_items, ground_truth_items))
    if len(hit_scores) == 0:
        print("No test users to evaluate.")
        return 0.0, 0.0, 0.0
    return {
        "hit@k": sum(hit_scores) / len(hit_scores),
        "recall@k": sum(recall_scores) / len(recall_scores),
        "ndcg@k": sum(ndcg_scores) / len(ndcg_scores)
    }

In [269]:

for k in [3, 5, 10]:
    metrics = evaluate_model(
        model=model,
        train_interactions_df=train_interactions_df,
        test_interactions_df=test_interactions_df,
        products_df=products_df,
        all_product_features=all_product_features,
        k=k
    )

    print(f"\nEvaluation @ {k}:")
    for metric_name, metric_value in metrics.items():
        print(f"{metric_name}: {metric_value:.4f}")

Evaluation @ 3:
hit@k: 0.0000
recall@k: 0.1220
ndcg@k: 0.0800

Evaluation @ 5:
hit@k: 0.0000
recall@k: 0.2060
ndcg@k: 0.1141

Evaluation @ 10:
hit@k: 0.0000
recall@k: 0.3740
ndcg@k: 0.1676

## Recommend By Recent Products

In [270]:
def recommend_by_recent_products(
    model,
    recent_product_ids,
    products_df,
    all_product_features,
    k=5
): 
    model.eval()

    recent_product_indices = [product_id_to_index[pid] for pid in recent_product_ids if pid in product_id_to_index]

    if len(recent_product_indices) == 0:
        print("No valid recent products found for recommendation.")
        return []
    recent_products_df = products_df[products_df["product_idx"].isin(recent_product_indices)].copy()
    recent_product_features = build_all_product_tensors(recent_products_df)

    with torch.no_grad(): 
        recent_features= {k:v.to(device) for k,v in recent_product_features.items()}
        recent_item_vector = model.encode_item(
            recent_features["product_idx"],
            recent_features["category_idx"],
            recent_features["sub_category_idx"],
            recent_features["brand_idx"],
            recent_features["price_norm"],
            recent_features["offer_price_norm"],            
            recent_features["text_tfidf"]
        ) #[num_recent, embedding_dim]
    temp_user_vector = recent_item_vector.mean(dim=0, keepdim=True) #[1, embedding_dim]
    temp_user_vector = F.normalize(temp_user_vector, dim=1) #[1, embedding_dim]

    product_features = {k:v.to(device) for k,v in all_product_features.items()}

    all_item_vector = model.encode_item(
        product_features["product_idx"],
        product_features["category_idx"],
        product_features["sub_category_idx"],
        product_features["brand_idx"],
        product_features["price_norm"],     
        product_features["offer_price_norm"],
        product_features["text_tfidf"]
    ) #[num_products, embedding_dim]
    scores = temp_user_vector @ all_item_vector.T #[1, num_products] 
    scores = scores.squeeze(0) #[num_products] 

    results_df = products_df.copy()
    results_df["score"] = scores.cpu().detach().numpy()

    results_df = results_df[~results_df["id"].isin(recent_product_ids)]
    top_k = results_df.sort_values("score", ascending=False).head(k) 
    return top_k

In [271]:
new_user_recs = recommend_by_recent_products(
    model=model,
    recent_product_ids=[100,188],
    products_df=products_df,
    all_product_features=all_product_features, 
    k=10
)

In [272]:
new_user_recs

,id,category_id,sub_category_id,brand_id,price,offer_price,name,short_description,long_description,product_idx,category_idx,sub_category_idx,brand_idx,price_norm,offer_price_norm,full_text,text_tfidf,score
110,124,16,45,60,24.0,20.0,Estee Lauder Refreshing Body Wash,<b>Estee Lauder Body Wash</b><p>Refreshing dai...,<b>Estee Lauder Refreshing Body Wash</b><p>Gen...,110,5,22,27,-0.322229,-0.319002,estee lauder refreshing body wash bestee laude...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.658435
104,118,16,42,58,12.0,10.0,Maybelline Gentle Facial Cleanser,<b>Maybelline Facial Cleanser</b><p>Daily gent...,<b>Maybelline Gentle Facial Cleanser</b><p>Sof...,104,5,20,25,-0.328879,-0.324886,maybelline gentle facial cleanser bmaybelline ...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.653580
85,99,16,63,57,50.0,44.0,Chanel Beauty Hydrating Lipstick Pink,<b>Chanel Beauty Hydrating Lipstick</b><p>Mois...,<b>Chanel Beauty Hydrating Lipstick Pink</b><p...,85,5,26,24,-0.307820,-0.304881,chanel beauty hydrating lipstick pink bchanel ...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.637374
185,202,6,10,24,699.0,659.0,Apple iPad Air M2 Tablet,<b>Apple iPad Air M2 Tablet</b><p>Powerful tab...,<b>Apple iPad Air M2 Tablet</b><p>This tablet ...,185,1,7,9,0.051834,0.056971,apple ipad air m2 tablet bapple ipad air m2 ta...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.636581
91,105,16,63,58,15.0,12.0,Maybelline Fit Me Liquid Foundation,<b>Maybelline Fit Me Liquid Foundation</b><p>L...,<b>Maybelline Fit Me Liquid Foundation</b><p>T...,91,5,26,25,-0.327216,-0.323709,maybelline fit me liquid foundation bmaybellin...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.636515
95,109,16,63,59,28.0,24.0,MAC Cosmetics Powder Blush Coral,<b>MAC Powder Blush</b><p>Highly pigmented pow...,<b>MAC Cosmetics Powder Blush Coral</b><p>Prof...,95,5,26,26,-0.320012,-0.316649,mac cosmetics powder blush coral bmac powder b...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.636411
171,187,6,9,24,999.0,939.0,Apple iPhone 11 Plus Smartphone,<b>Apple iPhone 11 Plus Smartphone</b><p>Large...,<b>Apple iPhone 11 Plus Smartphone</b><p>This ...,171,1,6,9,0.218084,0.221717,apple iphone 11 plus smartphone bapple iphone ...,"[0.0, 0.4055603091560028, 0.0, 0.0, 0.0, 0.0, ...",0.635848
90,104,16,63,59,40.0,35.0,MAC Cosmetics Studio Fix Foundation,<b>MAC Cosmetics Studio Fix Foundation</b><p>P...,<b>MAC Cosmetics Studio Fix Foundation</b><p>T...,90,5,26,26,-0.313362,-0.310177,mac cosmetics studio fix foundation bmac cosme...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.635799
37,47,6,10,24,449.0,409.0,Apple iPad 10th Generation Tablet,<b>Apple iPad 10th Generation Tablet</b><p>Ver...,<b>Apple iPad 10th Generation Tablet</b><p>Thi...,37,1,7,9,-0.086708,-0.090123,apple ipad 10th generation tablet bapple ipad ...,"[0.4409199705714987, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.635510
99,113,16,63,60,34.0,29.0,Estee Lauder Lip Gloss Shine,<b>Estee Lauder Lip Gloss</b><p>Glossy lip col...,<b>Estee Lauder Lip Gloss Shine</b><p>Elegant ...,99,5,26,27,-0.316687,-0.313707,estee lauder lip gloss shine bestee lauder lip...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.635092

## Saving models

In [299]:
model.eval()
model.to(device)
product_features = {k:v.to(device) for k,v in all_product_features.items()}
all_item_vector = model.encode_item(
    product_features["product_idx"],
    product_features["category_idx"],   
    product_features["sub_category_idx"],
    product_features["brand_idx"],
    product_features["price_norm"],
    product_features["offer_price_norm"],
    product_features["text_tfidf"]
) #[num_products, embedding_dim] 
all_user_vector = model.encode_user(
    torch.arange(num_users, dtype=torch.long).to(device)
)

In [300]:
vector_embeddings = all_item_vector.detach().cpu()
all_user_vector = all_user_vector.detach().cpu()

In [301]:
# Convert numpy to python int 
user_id_to_index = {int(idx): int(pid) for idx, pid in user_id_to_index.items()}
idx_to_user_id = {int(idx): int(pid) for idx, pid in idx_to_user_id.items()}
product_id_to_index = {int(idx): int(pid) for idx, pid in product_id_to_index.items()}
idx_to_product_id = {int(idx): int(pid) for idx, pid in idx_to_product_id.items()}

# Save mappings
torch.save(vector_embeddings, "../models/twotower/vector_embeddings.pth")
torch.save(user_id_to_index, "../models/twotower/user_id_to_index.pth")
torch.save(idx_to_user_id, "../models/twotower/user_index_to_id.pth")
torch.save(product_id_to_index, "../models/twotower/product_id_to_index.pth")
torch.save(idx_to_product_id, "../models/twotower/product_index_to_id.pth")
torch.save(all_user_vector, "../models/twotower/all_user_vector.pth")

In [277]:
user_id_to_index[487], product_id_to_index[6], idx_to_product_id[1]

(2, 1, 6)