In [1]:
# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import numpy as np
import pandas as pd
import torch 
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    roc_auc_score,
    log_loss,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
from sqlalchemy import create_engine

import sys 
sys.path.append("../models/sasrec") 
from sasrec_model import SASRecModel 
sys.path.append("../models/comirec")
from comirec_model import ComiRecSAModel 
sys.path.append("../models/bert4rec")
from bert4rec_model import BERT4RecModel
import joblib

In [2]:
#1. Db Connection
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [12]:
# 2. Load data from MySQL
products_df = pd.read_sql(
    """
    SELECT *
    FROM products
    """,
    engine
)
interactions_df= pd.read_sql(
    """
    SELECT user_id, product_id, created_at
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)

In [13]:
products_df.head()

,id,name,slug,thumb_image,shop_profile_id,category_id,sub_category_id,brand_id,qty,short_description,...,offer_price,offer_start_price,offer_end_price,product_type,status,is_approved,seo_title,seo_description,created_at,updated_at
0,5,Nestle Ready Meal Bento Box,nestle-ready-meal-bento-box,uploads/2026-03-09_1773056017_69aeb0119a74a_ne...,7,20,58,52,120,<b>Instant Food</b><p>Convenient ready meal wi...,...,6.0,2026-03-01,2026-03-18,top,1,1,Nestle Ready Meal Bento Box,Shop Nestle Ready Meal Bento Box for a quick a...,2024-03-13 11:46:12,2026-03-09 11:33:37
1,6,Nike Summer Cotton T-Shirt,nike-summer-cotton-t-shirt,uploads/2026-03-09_1773057158_69aeb486e0a5d_ni...,3,5,7,19,120,<b>Summer T-Shirt</b><p>Breathable cotton t-sh...,...,20.0,2026-03-02,2026-03-20,featured,1,1,Nike Summer Cotton T-Shirt,Shop Nike Summer Cotton T-Shirt with breathabl...,2024-03-16 09:34:13,2026-03-09 11:52:38
2,7,Selons Knit Sweater,selons-knit-sweater,uploads/2026-03-09_1773057566_69aeb61e8c1db_se...,3,5,4,6,90,<b>Knit Sweater</b><p>Soft knit sweater design...,...,29.0,2026-03-01,2026-03-19,new_arrival,1,1,Selons Knit Sweater,Shop Selons Knit Sweater with soft fabric and ...,2024-03-16 09:37:00,2026-03-09 11:59:26
3,9,Samsung Galaxy Tab S9 5G,samsung-galaxy-tab-s9-5g,uploads/2026-03-09_1773057876_69aeb754dc20d_sa...,10,6,10,18,35,<b>Tablet</b><p>High performance tablet design...,...,649.0,2026-03-01,2026-03-18,top,1,1,Samsung Galaxy Tab S9 5G,Shop Samsung Galaxy Tab S9 5G for entertainmen...,2024-03-16 09:43:13,2026-03-09 12:04:36
4,10,Xiaomi Y68 Smart Watch,xiaomi-y68-smart-watch,uploads/2026-03-09_1773064221_69aed01d51bc1_xi...,10,7,14,12,70,<b>Smart Watch</b><p>Affordable smart watch wi...,...,34.0,2026-03-01,2026-03-20,featured,1,1,Xiaomi Y68 Smart Watch,Shop Xiaomi Y68 Smart Watch with fitness track...,2024-03-16 09:45:28,2026-03-09 13:50:21

In [14]:
interactions_df.head()

   user_id  product_id          created_at
0      485         258 2026-04-17 18:15:13
1      485         191 2026-04-17 18:15:13
2      485         192 2026-04-17 18:15:13
3      485         201 2026-04-17 18:15:13
4      485         187 2026-04-17 18:15:13

In [18]:

# 3. Prepare Data for XGBoost 
products_df.rename(columns={'id': 'product_id'}, inplace=True)
products_df['product_id'] = products_df['product_id'].astype(int) 
interactions_df['product_id'] = interactions_df['product_id'].astype(int)
interactions_df['user_id'] = interactions_df['user_id'].astype(int)

interactions_df['created_at'] = pd.to_datetime(interactions_df['created_at'])
interactions_df.sort_values(by=['user_id', 'created_at'], inplace=True)
interactions_df.drop_duplicates(inplace=True)

In [19]:

def split_past_future_by_user(interactions_df,past_ratio = 0.7): 
    past_parts = []
    future_parts = []
    for user_id, user_df in interactions_df.groupby('user_id'): 
        user_df = user_df.sort_values(by='created_at')
        split_index = int(len(user_df) * past_ratio)
        past_parts.append(user_df.iloc[:split_index])
        future_parts.append(user_df.iloc[split_index:])
    past_df = pd.concat(past_parts).reset_index(drop=True)
    future_df = pd.concat(future_parts).reset_index(drop=True)
    return past_df, future_df

In [20]:
past_interactions_df, future_interactions_df = split_past_future_by_user(interactions_df, past_ratio=0.7)
past_interactions_df.head()

   user_id  product_id          created_at
0      485         258 2026-04-17 18:15:13
1      485         191 2026-04-17 18:15:13
2      485         192 2026-04-17 18:15:13
3      485         201 2026-04-17 18:15:13
4      485         187 2026-04-17 18:15:13

In [21]:
future_interactions_df.head()

   user_id  product_id          created_at
0      485         256 2026-04-17 18:15:13
1      485          89 2026-04-17 18:15:13
2      485         253 2026-04-17 18:15:13
3      485         186 2026-04-17 18:15:13
4      485         259 2026-04-17 18:15:13

In [188]:
# 7. Build Mapping Dictionary for user_id and product_id
product_idx_to_id = {idx: product_id for idx, product_id in enumerate(products_df['product_id'].unique())}
product_id_to_idx = {product_id: idx for idx, product_id in enumerate(products_df['product_id'].unique())} 

user_idx_to_id = {idx: user_id for idx, user_id in enumerate(train_pairs_df['user_id'].unique())}
user_id_to_idx = {user_id: idx for idx, user_id in enumerate(train_pairs_df['user_id'].unique())}

In [189]:
# 8. Build Mapping Function From mapping dictionary
def get_user_index(user_id):
    return user_id_to_idx.get(user_id, None)

def get_product_index(product_id, isForSequential = False):
    if isForSequential:
        return product_id_to_idx.get(product_id, None) + 1
    else:
        return product_id_to_idx.get(product_id, None) 

def get_product_id(product_index, isForSequential = False):
    if isForSequential:
        return product_idx_to_id.get(product_index - 1, None)
    else:
        return product_idx_to_id.get(product_index, None)

In [190]:
# 9. Load output from 6 trained models
# 9.1 Matrix Factorization

matrix_factorization_item_factors = joblib.load("../models/matrix_factorization/item_factors.joblib")
matrix_factorization_user_factors = joblib.load("../models/matrix_factorization/user_factors.joblib") 

# 9.2 LightGCN 
lightgcn_item_embeddings = joblib.load("../models/lightgcn/item_embeddings.joblib")
lightgcn_user_embeddings = joblib.load("../models/lightgcn/user_embeddings.joblib") 

# 9.3 Two Tower  
vector_embeddings = torch.load("../models/twotower/vector_embeddings.pth")
two_tower_item_embeddings = vector_embeddings.cpu().numpy()
all_user_vector = torch.load("../models/twotower/all_user_vector.pth")
# 9.4 SASRec
# sasrec_model_checkpoint = torch.load("../models/sasrec/sasrec_checkpoint.pth", weights_only=False) 
# sasrec_model = SASRecModel(
#             num_items= int(sasrec_model_checkpoint["num_items"]),
#             max_seq_len=int(sasrec_model_checkpoint["max_seq_len"]),
#             embedding_dim=int(sasrec_model_checkpoint["embedding_dim"]),
#             num_attention_heads=int(sasrec_model_checkpoint["num_attention_heads"]),
#             num_transformer_blocks=int(sasrec_model_checkpoint["num_transformer_blocks"]),
#             dropout_rate=float(sasrec_model_checkpoint["dropout_rate"]),
#             )
# sasrec_model.load_state_dict(sasrec_model_checkpoint["model_state_dict"])
# 9.5 ComiRec 
comirec_model_checkpoint = torch.load("../models/comirec/comirec_checkpoint.pth",weights_only=False)
comirec_model = ComiRecSAModel(
            num_items= int(comirec_model_checkpoint["num_items"]),
            max_seq_len=int(comirec_model_checkpoint["max_seq_len"]),
            embedding_dim=int(comirec_model_checkpoint["embedding_dim"]),
            hidden_dim=int(comirec_model_checkpoint["hidden_dim"]),
            num_interests=int(comirec_model_checkpoint["num_interests"]),
            dropout_rate=float(comirec_model_checkpoint["dropout_rate"]),
            pad_id=int(comirec_model_checkpoint["pad_id"]),
        )
comirec_model.load_state_dict(comirec_model_checkpoint["model_state_dict"])
# 9.6 Bert4rec 
bert4rec_model_checkpoint = torch.load("../models/bert4rec/bert4rec_checkpoint.pth",weights_only=False)
bert4rec_model = BERT4RecModel(
            num_items= int(bert4rec_model_checkpoint["num_items"]),
            max_seq_len=int(bert4rec_model_checkpoint["max_seq_len"]),
            embedding_dim=int(bert4rec_model_checkpoint["embedding_dim"]),
            num_attention_heads=int(bert4rec_model_checkpoint["num_attention_heads"]),
            num_transformer_blocks=int(bert4rec_model_checkpoint["num_transformer_blocks"]),
            dropout_rate=float(bert4rec_model_checkpoint["dropout_rate"]),
        )
bert4rec_model.load_state_dict(bert4rec_model_checkpoint["model_state_dict"])

In [191]:
user_id_to_idx[487], product_id_to_idx[6], product_idx_to_id[1]

(2, 1, np.int64(6))

In [192]:
# 10. SCORE FUNCTIONS FROM 6 MODELS 

# 10.1 Matrix Factorization


def get_mf_score(user_id, product_id):
    user_idx = get_user_index(user_id)
    product_idx = get_product_index(product_id)

    if user_idx is None or product_idx is None:
        return 0.0

    user_vector = matrix_factorization_user_factors[user_idx]
    item_vector = matrix_factorization_item_factors[product_idx]

    score = np.dot(user_vector, item_vector)
    return score

# 10.2 LightGCN
def get_lightgcn_score(user_id, product_id):
    user_idx = get_user_index(user_id)
    product_idx = get_product_index(product_id)

    if user_idx is None or product_idx is None:
        return 0.0

    user_vector = lightgcn_user_embeddings[user_idx]
    item_vector = lightgcn_item_embeddings[product_idx]

    score = np.dot(user_vector, item_vector)
    return score

# 10.3 Two Tower
def get_two_tower_score(user_id, product_id):
    user_idx = get_user_index(user_id)
    product_idx = get_product_index(product_id)

    if user_idx is None or product_idx is None:
        return 0.0

    user_vector = all_user_vector[user_idx]
    item_vector = vector_embeddings[product_idx]

    score = torch.dot(user_vector, item_vector).item()
    return score

# For sequential models, each mapping will plus 1 
# Build Interaction Sequence 
MAX_SEQ_LEN = 17
def build_interactions_sequence(train_pairs_df, 
                               user_id, 
                               current_product_id, 
                               max_seq_len, 
                               pad_id,
                               product_id_to_idx, 
                               is_bert4rec=False, 
                               mask_id = None): 
    user_interaction_up_to_current = []

    user_interactions = train_pairs_df[(train_pairs_df['user_id'] == user_id) & (train_pairs_df['label'] == 1)]
    for _, row in user_interactions.iterrows():
        if row['product_id'] == current_product_id:
            break
        user_interaction_up_to_current.append(row)
    
    user_sequence = [get_product_index(item.product_id, isForSequential=True) 
                     for item in user_interaction_up_to_current 
                     if get_product_index(item.product_id, isForSequential=True) is not None]

    if is_bert4rec and mask_id is not None:
        user_sequence.append(mask_id)

    if len(user_sequence) > max_seq_len: 
        user_sequence = user_sequence[-max_seq_len:] 
    padding_length = max_seq_len - len(user_sequence)
    padded_sequence = [pad_id] * padding_length + user_sequence
    return padded_sequence,user_sequence

# 10.4 SASRec
# def get_sasrec_score(user_id, product_id):
#     user_idx = get_user_index(user_id) 
#     product_idx = get_product_index(product_id, isForSequential=True) 

#     if user_idx is None or product_idx is None:
#         return 0.0

#     sasrec_model.to("cpu")
#     sasrec_model.eval()
#     padded_sequence, user_sequence = build_interactions_sequence(
#         train_pairs_df, 
#         user_id, 
#         product_id, 
#         max_seq_len=MAX_SEQ_LEN, 
#         pad_id=sasrec_model.pad_id,
#         product_id_to_idx=product_id_to_idx,
#         is_bert4rec=False
#     )
#     input_tensor = torch.tensor(
#         [padded_sequence], 
#         dtype = torch.long,
#         device = "cpu"
#     )
#     with torch.no_grad():
#         logits = sasrec_model(input_tensor) 
#         scores = logits[0][product_idx]
#     return scores.item()

# # 10.5 Bert4Rec
def get_bert4rec_score(user_id, product_id):
    user_idx = get_user_index(user_id)
    product_idx = get_product_index(product_id, isForSequential=True) 

    if user_idx is None or product_idx is None:
        return 0.0

    bert4rec_model.to("cpu")
    bert4rec_model.eval()
    padded_sequence, user_sequence = build_interactions_sequence(
        train_pairs_df, 
        user_id, 
        product_id, 
        max_seq_len=MAX_SEQ_LEN, 
        pad_id=bert4rec_model.pad_id,
        product_id_to_idx=product_id_to_idx,
        is_bert4rec=True,
        mask_id=bert4rec_model_checkpoint["mask_id"] 
    )
    input_tensor = torch.tensor(
        [padded_sequence], 
        dtype = torch.long,
        device = "cpu"
    )
    with torch.no_grad():
        logits = bert4rec_model(input_tensor) 
        mask_position = len(padded_sequence) - 1 
        scores = logits[0][mask_position][product_idx]
    return scores.item()

def get_comirec_score(user_id, product_id):
    user_idx = get_user_index(user_id)
    product_idx = get_product_index(product_id, isForSequential=True) 

    if user_idx is None or product_idx is None:
        return 0.0
    comirec_model.to("cpu")
    comirec_model.eval()
    padded_sequence, user_sequence = build_interactions_sequence(
        train_pairs_df=train_pairs_df,
        user_id=user_id,
        current_product_id=product_id,
        max_seq_len=MAX_SEQ_LEN,
        pad_id=comirec_model.pad_id,
        product_id_to_idx=product_id_to_idx,
        is_bert4rec=False
    )
    
    input_tensor = torch.tensor([padded_sequence],dtype=torch.long).to("cpu") #[1,L] <= [L]

    with torch.no_grad():
        V, A = comirec_model(input_tensor) #[1,K,D],[1,K,L] 

        all_item_emb = comirec_model.item_embedding.weight #[num_items+1, D]
        all_item_emb = all_item_emb.T #[D, num_items+1]

        V = V.squeeze(0) #[K,D] <= [1,K,D] 

        scores_by_interest = V @ all_item_emb #[K,num_items+1] <= [K,D] @ [D,num_items+1] 

        final_scores,best_interest_for_item = torch.max(scores_by_interest,dim=0) #[num_items+1] <= max([K,num_items+1],dim=0) 
        scores = final_scores[product_idx]
    return scores.item()

In [193]:
comirecScore = get_comirec_score(485, 6)
# sasrecScore = get_sasrec_score(485, 6)
bert4recScore = get_bert4rec_score(485, 6)
print(f"ComiRec Score: {comirecScore}")
# print(f"SASRec Score: {sasrecScore}")
print(f"BERT4Rec Score: {bert4recScore}")
print("---------------------------------")
comirecScore = get_comirec_score(485, 192)
# sasrecScore = get_sasrec_score(485, 192)
bert4recScore = get_bert4rec_score(485, 192)
print(f"ComiRec Score: {comirecScore}")
# print(f"SASRec Score: {sasrecScore}")
print(f"BERT4Rec Score: {bert4recScore}")

ComiRec Score: 5.618265151977539
BERT4Rec Score: -5.30812931060791
---------------------------------
ComiRec Score: 11.48575496673584
BERT4Rec Score: 14.977136611938477

In [194]:
#8. Add model scores 
def add_model_scores(df): 
    df['mf_score'] = df.apply(lambda row: get_mf_score(row['user_id'], row['product_id']), axis=1)
    df['lightgcn_score'] = df.apply(lambda row: get_lightgcn_score(row['user_id'], row['product_id']), axis=1)
    # df['sasrec_score'] = df.apply(lambda row: get_sasrec_score(row['user_id'], row['product_id']), axis=1)
    df['bert4rec_score'] = df.apply(lambda row: get_bert4rec_score(row['user_id'], row['product_id']), axis=1)
    df['comirec_score'] = df.apply(lambda row: get_comirec_score(row['user_id'], row['product_id']), axis=1)
    df['two_tower_score'] = df.apply(lambda row: get_two_tower_score(row['user_id'], row['product_id']), axis=1)
    return df

train_pairs_df = add_model_scores(train_pairs_df)
train_pairs_df.head()

,user_id,product_id,label,mf_score,lightgcn_score,bert4rec_score,comirec_score,two_tower_score
0,485,258,1,1.011142,4.972530,-0.361836,NaN,0.987866
1,485,191,1,0.998777,5.119193,9.896655,3.929640,0.984646
2,485,192,1,0.965536,4.055376,14.977137,11.485755,0.984578
3,485,201,1,0.993748,4.282064,14.854943,16.811409,0.989916
4,485,187,1,0.939200,3.683261,16.734861,7.141994,0.990784

In [195]:
train_pairs_df[train_pairs_df.isna().any(axis=1)]

,user_id,product_id,label,mf_score,lightgcn_score,bert4rec_score,comirec_score,two_tower_score
0,485,258,1,1.011142,4.972530,-0.361836,NaN,0.987866
16,486,73,1,0.982314,1.909063,0.581955,NaN,0.039878
34,487,187,1,0.964720,3.987641,-0.499706,NaN,0.983367
52,488,189,1,0.978353,4.980894,0.358899,NaN,0.998990
68,489,191,1,0.947982,6.294207,0.225801,NaN,0.993046
...,...,...,...,...,...,...,...,...
7759,980,167,1,0.976444,9.513439,-0.303541,NaN,0.998770
7774,981,159,1,0.975783,9.185375,-1.110052,NaN,0.999811
7789,982,5,1,0.967612,6.865115,-1.311705,NaN,0.999630
7802,983,172,1,0.992549,7.867116,0.455976,NaN,0.999820
7818,984,5,1,0.967011,6.845899,-1.311705,NaN,0.999574

In [196]:
len(train_pairs_df)

39160

In [197]:
train_pairs_df.dropna(inplace=True)

In [198]:
len(train_pairs_df)

38660

In [199]:
train_pairs_df[train_pairs_df.isna().any(axis=1)]

Empty DataFrame
Columns: [user_id, product_id, label, mf_score, lightgcn_score, bert4rec_score, comirec_score, two_tower_score]
Index: []

In [201]:
# Add Rank Features

MODEL_SCORE_COLS = ['mf_score', 
                    'lightgcn_score', 
                    # 'sasrec_score', 
                    'bert4rec_score', 'comirec_score', 'two_tower_score']

def add_rank_features(df, score_cols=MODEL_SCORE_COLS):
    df = df.copy()
    for col in score_cols:
        rank_col = col + '_rank'
        df[rank_col] = df.groupby('user_id')[col].rank(method='first', ascending=False)
    return df

train_pairs_df = add_rank_features(train_pairs_df)
train_pairs_df.head()

,user_id,product_id,label,mf_score,lightgcn_score,bert4rec_score,comirec_score,two_tower_score,mf_score_rank,lightgcn_score_rank,bert4rec_score_rank,comirec_score_rank,two_tower_score_rank
1,485,191,1,0.998777,5.119193,9.896655,3.929640,0.984646,1.0,1.0,7.0,35.0,6.0
2,485,192,1,0.965536,4.055376,14.977137,11.485755,0.984578,6.0,9.0,2.0,4.0,7.0
3,485,201,1,0.993748,4.282064,14.854943,16.811409,0.989916,2.0,8.0,3.0,1.0,2.0
4,485,187,1,0.939200,3.683261,16.734861,7.141994,0.990784,10.0,10.0,1.0,15.0,1.0
5,485,211,1,0.980672,5.080219,13.473557,11.094738,0.774454,5.0,2.0,4.0,6.0,11.0

In [202]:
# Add Statistical Features

item_popularity_df = interactions_df.groupby('product_id').size().reset_index(name='item_popularity')
train_pairs_df = train_pairs_df.merge(item_popularity_df, on='product_id', how='left')
train_pairs_df['item_popularity'] = train_pairs_df['item_popularity'].fillna(0)

user_interaction_counts = interactions_df.groupby('user_id').size().reset_index(name='user_interaction_count')
train_pairs_df = train_pairs_df.merge(user_interaction_counts, on='user_id', how='left')
train_pairs_df['user_interaction_count'] = train_pairs_df['user_interaction_count'].fillna(0)

train_pairs_df.head()

,user_id,product_id,label,mf_score,lightgcn_score,bert4rec_score,comirec_score,two_tower_score,mf_score_rank,lightgcn_score_rank,bert4rec_score_rank,comirec_score_rank,two_tower_score_rank,item_popularity,user_interaction_count
0,485,191,1,0.998777,5.119193,9.896655,3.929640,0.984646,1.0,1.0,7.0,35.0,6.0,57,20
1,485,192,1,0.965536,4.055376,14.977137,11.485755,0.984578,6.0,9.0,2.0,4.0,7.0,43,20
2,485,201,1,0.993748,4.282064,14.854943,16.811409,0.989916,2.0,8.0,3.0,1.0,2.0,47,20
3,485,187,1,0.939200,3.683261,16.734861,7.141994,0.990784,10.0,10.0,1.0,15.0,1.0,44,20
4,485,211,1,0.980672,5.080219,13.473557,11.094738,0.774454,5.0,2.0,4.0,6.0,11.0,98,20

In [203]:
# 11. Merge product features 

PRODUCT_FEATURE_COLS = ['name',
                        'product_id', 
                        'category_id', 
                        'sub_category_id',
                        'brand_id', 
                        'price',
                        'offer_price', 
                        "short_description",
                        "long_description"]

train_pairs_df = train_pairs_df.merge(products_df[PRODUCT_FEATURE_COLS], on='product_id', how='left')
train_pairs_df.head()

joblib.dump(train_pairs_df, "../models/xgboost/train_pairs_with_features.joblib")

['../models/xgboost/train_pairs_with_features.joblib']

In [204]:
train_pairs_df.head()

,user_id,product_id,label,mf_score,lightgcn_score,bert4rec_score,comirec_score,two_tower_score,mf_score_rank,lightgcn_score_rank,...,item_popularity,user_interaction_count,name,category_id,sub_category_id,brand_id,price,offer_price,short_description,long_description
0,485,191,1,0.998777,5.119193,9.896655,3.929640,0.984646,1.0,1.0,...,57,20,Apple iPhone 15 Plus Smartphone,6,9,24,899.0,839.0,<b>Apple iPhone 15 Plus Smartphone</b><p>Large...,<b>Apple iPhone 15 Plus Smartphone</b><p>This ...
1,485,192,1,0.965536,4.055376,14.977137,11.485755,0.984578,6.0,9.0,...,43,20,Apple iPhone 12 Pro Smartphone,6,9,24,1099.0,1049.0,<b>Apple iPhone 12 Pro Smartphone</b><p>Advanc...,<b>Apple iPhone 12 Pro Smartphone</b><p>This s...
2,485,201,1,0.993748,4.282064,14.854943,16.811409,0.989916,2.0,8.0,...,47,20,Apple iPad 11th Generation Tablet,6,10,24,449.0,419.0,<b>Apple iPad 11th Generation Tablet</b><p>Ver...,<b>Apple iPad 11th Generation Tablet</b><p>Thi...
3,485,187,1,0.939200,3.683261,16.734861,7.141994,0.990784,10.0,10.0,...,44,20,Apple iPhone 11 Plus Smartphone,6,9,24,999.0,939.0,<b>Apple iPhone 11 Plus Smartphone</b><p>Large...,<b>Apple iPhone 11 Plus Smartphone</b><p>This ...
4,485,211,1,0.980672,5.080219,13.473557,11.094738,0.774454,5.0,2.0,...,98,20,Apple Watch Series 9 GPS Smartwatch,7,14,24,399.0,369.0,<b>Apple Watch Series 9 GPS Smartwatch</b><p>A...,<b>Apple Watch Series 9 GPS Smartwatch</b><p>T...

In [205]:
len(train_pairs_df)

38660

In [210]:
# 12. Define Feature Columns 

NUMERIC_FEATURES = [
    # Scores from 6 models 
    'mf_score', 'lightgcn_score', 
    # 'sasrec_score', 
    'bert4rec_score', 'comirec_score', 'two_tower_score', 

    # Rank features
    'mf_score_rank', 'lightgcn_score_rank', 
    # 'sasrec_score_rank', 
    'bert4rec_score_rank', 'comirec_score_rank', 'two_tower_score_rank',
    
    # Product features
    'price','offer_price', 

    # Statistical features
    'item_popularity', 'user_interaction_count'
]

CATEGORICAL_FEATURES = [
    'category_id', 
    'sub_category_id',
    'brand_id'
]
TEXT_FEATURES = [
    'name',
    'short_description',
    'long_description'
]

TARGET_COLUMN = 'label' 

FEATURE_COLUMNS = NUMERIC_FEATURES + CATEGORICAL_FEATURES + TEXT_FEATURES

In [211]:
# 13. Train/Test Split

X = train_pairs_df[FEATURE_COLUMNS]
y = train_pairs_df[TARGET_COLUMN] 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Train set: {X_train.shape[0]} samples")
print(f"Test set: {X_test.shape[0]} samples")

Train set: 30928 samples
Test set: 7732 samples

In [212]:
# 14. Preprocessing Pipeline for XGBoost
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', NUMERIC_FEATURES),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=True), CATEGORICAL_FEATURES),
        ('text_name', TfidfVectorizer(max_features=3000), 'name'),
        ('text_short', TfidfVectorizer(max_features=3000), 'short_description'),
        ('text_long', TfidfVectorizer(max_features=3000), 'long_description')
    ]
)

In [213]:
# 15. XGBoost Initialization
xgb_model = XGBClassifier(
    n_estimators = 1000, 
    max_depth = 6, 
    learning_rate = 0.05, 

    subsample = 0.8,
    colsample_bytree = 0.8,

    min_child_weight = 5, 
    gamma = 0.1, 

    reg_lambda = 3.0, 
    reg_alpha = 0.1, 

    objective = 'binary:logistic',
    eval_metric = 'logloss', 

    tree_method = 'hist',
    random_state = 42,
    n_jobs = -1
)

In [214]:
# 16. Pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', xgb_model)
])

In [215]:
# 17. Train the model 
pipeline.fit(X_train, y_train)
print("Model training completed.")

Model training completed.

In [216]:
pipeline.predict_proba(X_test)[:,1]

array([7.1072449e-05, 9.2635478e-04, 1.0636699e-03, ..., 9.7125936e-01,
       3.4693559e-05, 4.2668226e-01], shape=(7732,), dtype=float32)

In [217]:
# 18. Evaluation 

test_proba = pipeline.predict_proba(X_test)[:, 1]
y_pred = (test_proba >= 0.5).astype(int)

auc = roc_auc_score(y_test, test_proba) 
logloss = log_loss(y_test, test_proba)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Test AUC: {auc:.4f}")
print(f"Test Log Loss: {logloss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")
print(f"Test Precision: {precision:.4f}")
print(f"Test Recall: {recall:.4f}")
print(f"Test F1 Score: {f1:.4f}")

Test AUC: 0.9940
Test Log Loss: 0.0581
Test Accuracy: 0.9850
Test Precision: 0.9767
Test Recall: 0.9434
Test F1 Score: 0.9598

In [218]:
# 19. Top K metrics 

def recall_at_k(recommended_items,ground_truth_items,k=10): 
    recommended_items = recommended_items[:k]

    if len(ground_truth_items) == 0:
        return 0.0
    hits = sum(1 for item in recommended_items if item in ground_truth_items)
    return hits / len(ground_truth_items)

def ndcg_at_k(recommended_items,ground_truth_items,k=10): 
    recommended_items = recommended_items[:k] 
    dcg = 0.0

    for rank,item_id in enumerate(recommended_items, start=1):
        if item_id in ground_truth_items:
            dcg += 1 / np.log2(rank + 1)
    
    iteal_hits = min(len(ground_truth_items), k)

    if iteal_hits == 0:
        return 0.0
    idcg = sum(1/np.log2(rank + 1) for rank in range(1, iteal_hits + 1))
    return dcg / idcg if idcg > 0 else 0.0

In [219]:
# 20. Build Test Dataframe wiht predictions 


test_result_df = X_test.copy()
test_result_df["user_id"] = train_pairs_df.loc[X_test.index, "user_id"].values
test_result_df["product_id"] = train_pairs_df.loc[X_test.index, "product_id"].values
test_result_df["label"] = y_test.values
test_result_df["xgb_score"] = test_proba

test_result_df.head()

,mf_score,lightgcn_score,bert4rec_score,comirec_score,two_tower_score,mf_score_rank,lightgcn_score_rank,bert4rec_score_rank,comirec_score_rank,two_tower_score_rank,...,category_id,sub_category_id,brand_id,name,short_description,long_description,user_id,product_id,label,xgb_score
23154,0.008559,-0.490894,-1.624308,0.701698,-0.182112,35.0,46.0,43.0,58.0,53.0,...,5,4,19,Nike Everyday Crewneck Sweatshirt,<b>Nike Everyday Crewneck Sweatshirt</b><p>Cla...,<b>Nike Everyday Crewneck Sweatshirt</b><p>Thi...,730,37,0,0.000071
34275,-0.039162,-1.045053,-4.344168,4.891433,-0.049439,61.0,56.0,68.0,37.0,37.0,...,7,16,8,Sony The Last of Us Part I Game Disc,<b>The Last of Us Part I Game Disc</b><p>Story...,<b>Sony The Last of Us Part I Game Disc</b><p>...,911,255,0,0.000926
33455,-0.095181,1.623157,-5.161478,9.749023,0.385237,80.0,32.0,88.0,16.0,30.0,...,16,63,54,Gucci Beauty Glow Highlighter,<b>Gucci Beauty Highlighter</b><p>Luxury face ...,<b>Gucci Beauty Glow Highlighter</b><p>Silky h...,898,108,0,0.001064
3051,0.999984,6.383763,11.768278,8.758271,0.844576,4.0,3.0,6.0,14.0,2.0,...,7,14,24,Apple Watch Ultra 2 Smartwatch,<b>Apple Watch Ultra 2 Smartwatch</b><p>Rugged...,<b>Apple Watch Ultra 2 Smartwatch</b><p>This s...,685,213,1,0.999928
21192,-0.034874,-0.580016,-2.957319,-5.022812,-0.484157,60.0,47.0,53.0,79.0,74.0,...,5,4,6,Selons Knit Sweater,<b>Knit Sweater</b><p>Soft knit sweater design...,<b>Selons Knit Sweater</b><p>This sweater is m...,699,7,0,0.000014

In [220]:
# 21. Evalue TopK by user 

def evaluate_top_k_by_user(result_df, k =10): 
    precision_list = [] 
    recall_list = []
    ndcg_list = []
    for user_id , user_df in result_df.groupby("user_id"): 
        user_df = user_df.sort_values("xgb_score",ascending = False) 
        recommend = user_df["product_id"].tolist()

        ground_truth_items = set(
            user_df[user_df["label"] == 1]["product_id"].tolist()
        )

        if len(ground_truth_items) == 0:
            continue
        
        recall_list.append(recall_at_k(recommend, ground_truth_items, k))
        ndcg_list.append(ndcg_at_k(recommend, ground_truth_items, k))
    
    return {
        "recall_at_k": np.mean(recall_list),
        "ndcg_at_k": np.mean(ndcg_list)
    }

top_k_metrics = evaluate_top_k_by_user(test_result_df, k=10)

for metric_name,metric_value in top_k_metrics.items(): 
    print(f"{metric_name}: {metric_value:.4f}")

recall_at_k: 0.9966
ndcg_at_k: 0.9884

In [351]:
# # Building mapping function for matrix Factorization Model 
# def get_mapped_interactions(self, interactions):
#     mapped_interactions = []
#     for interaction in interactions:
#         product_id = interaction.product_id
#         interaction_type = interaction.interaction_type
#         if interaction_type == "click":
#             mapped_interactions.append((product_id, 0.05))
#         elif interaction_type == "wishlist_add":
#             mapped_interactions.append((product_id, 0.7))
#         elif interaction_type == "cart_add":
#             mapped_interactions.append((product_id, 1)) 
#         elif interaction_type == "R5":
#             mapped_interactions.append((product_id, 0.9))
#         elif interaction_type == "R4":
#             mapped_interactions.append((product_id, 0.8))
#         elif interaction_type == "R3":
#             mapped_interactions.append((product_id, 0.6))
#         elif interaction_type == "R2":
#             mapped_interactions.append((product_id, 0.4))
#         elif interaction_type == "R1":
#             mapped_interactions.append((product_id, 0.2)) 
#     return mapped_interactions

In [221]:
from pydantic import BaseModel
from typing import Literal 
class Interaction(BaseModel):
        product_id:int
        interaction_type:Literal[
            "click",
            "wishlist_add",
            "cart_add",
            "R5",
            "R4",
            "R3",
            "R2",
            "R1"
        ]

In [222]:
# Clean interactions function 
def clean_interactions(interactions:list[tuple]):
        interactions_df = pd.DataFrame([{"product_id": id} for id, interaction_type in interactions])
        interactions_df.drop_duplicates(inplace=True) 
        return interactions_df

In [223]:
# Build temporary user vector 

from pandas import DataFrame

def build_temp_user_vector(interactions:DataFrame,item_factors, get_product_index_func):
    embeddings = []
    for row in interactions.itertuples(index=False):
        product_idx = get_product_index_func(row.product_id)
        if product_idx is not None:
            embeddings.append(item_factors[product_idx])
    return np.mean(embeddings, axis=0)

In [224]:
# Get seen products for a user
def get_seen_products(interactions:list[tuple]):
    seen_products = set()
    for product_id, interaction_type in interactions:
        seen_products.add(product_id)
    return seen_products

In [225]:
# Classify interactions based on its sub_category_id 

def classify_interactions_by_sub_category(interactions:list[Interaction], products_df):
    sub_category_interactions = {}
    for interaction in interactions:
        product_id = interaction.product_id
        interaction_type = interaction.interaction_type
        sub_category_id = products_df.loc[products_df['product_id'] == product_id, 'sub_category_id'].values[0]
        if sub_category_id not in sub_category_interactions:
            sub_category_interactions[sub_category_id] = []
        sub_category_interactions[sub_category_id].append((product_id, interaction_type))
    return sub_category_interactions

In [226]:
# Nonsequential recommendation function
def nonsequential_recommend(interactions:list[Interaction],item_factors,top_k):
    sub_category_interactions = classify_interactions_by_sub_category(interactions, products_df) 
    candidate_scores = {}
    number_of_sub_categories = len(sub_category_interactions)
    # Take up to topk / number_of_sub_categories from each sub-category to ensure diversity
    k = top_k // number_of_sub_categories
    number_of_sub_categories = len(sub_category_interactions)
    for sub_category_id, interactions in sub_category_interactions.items():
        temp_user_vector = build_temp_user_vector(clean_interactions(interactions),
                                                   item_factors, 
                                                   get_product_index)
        seen_products = get_seen_products(interactions)

        scores = item_factors.dot(temp_user_vector).flatten()

        k_per_sub_category = 0
        rank_indices = np.argsort(scores)[::-1]
        for idx in rank_indices:
            product_id = get_product_id(idx)
            if product_id not in seen_products:
                seen_products.add(product_id)
                candidate_scores[product_id] = scores[idx]
                k_per_sub_category += 1
                if k_per_sub_category == k:
                    break

    sorted_candidates = sorted(candidate_scores.items(), key=lambda x: x[1], reverse=True)
    k_sorted_candidates = sorted_candidates[:top_k]
    # Convert to dictionary format
    candidates_dict = {product_id: score for product_id, score in k_sorted_candidates}
    return candidates_dict

In [227]:
# Sequential recommendation function


def build_interactions_sequence(interactions, max_seq_len, pad_id,is_bert4rec=False, mask_id=None):
        user_sequence = [get_product_index(item.product_id,isForSequential=True) for item in interactions]
        #Remove similar items from the sequence
        user_sequence = list(dict.fromkeys(user_sequence))
        
        if is_bert4rec and mask_id is not None:
            user_sequence.append(mask_id)
    
        if len(user_sequence) > max_seq_len: 
            user_sequence = user_sequence[-max_seq_len:] 
        padding_length = max_seq_len - len(user_sequence)
        padded_sequence = [pad_id] * padding_length + user_sequence
        return padded_sequence,user_sequence

In [228]:
def sequential_recommend(interactions:list[Interaction],model, max_seq_len ,pad_id, is_bert4rec=False, mask_id=None, top_k=10):
    model.to("cpu")
    model.eval()
    padded_sequence, user_sequence = build_interactions_sequence(
        interactions, 
        max_seq_len, 
        pad_id ,
        is_bert4rec, 
        mask_id
    )
    input_tensor = torch.tensor(
        [padded_sequence], 
        dtype = torch.long,
        device = "cpu"
    )
    with torch.no_grad():
        # if model == sasrec_model: 
        #     logits = model(input_tensor) 
        #     scores = logits[0] 
        if model == bert4rec_model:
            logits = model(input_tensor) 
            mask_position = len(padded_sequence) - 1 
            scores = logits[0][mask_position]
        else: 
            V, A = model(input_tensor) #[1,K,D],[1,K,L] 
            all_item_emb = model.item_embedding.weight #[num_items+1, D]
            all_item_emb = all_item_emb.T #[D, num_items+1]
            V = V.squeeze(0) #[K,D] <= [1,K,D] 
            scores_by_interest = V @ all_item_emb #[K,num_items+1] <= [K,D] @ [D,num_items+1] 
            final_scores,best_interest_for_item = torch.max(scores_by_interest,dim=0) #[num_items+1] <= max([K,num_items+1],dim=0) 
            scores = final_scores

    scores[pad_id] = float("-inf")
    if is_bert4rec and mask_id is not None:
        scores[mask_id] = float("-inf")

    for item_index in set(user_sequence): 
        scores[item_index] = float("-inf")
    top_scores,top_items = torch.topk(scores,k=top_k)
    
    candidates = []
    for item_index, score in zip(top_items.cpu().numpy(), top_scores.cpu().numpy()):
        product_id = get_product_id(item_index, isForSequential=True)
        candidates.append((product_id, score))
    
    # Convert to dictionary format
    candidates = {product_id: score for product_id, score in candidates}
    return candidates

In [229]:
# 22. Candidate Generators 


def mf_recommend(interactions:list[Interaction], top_k=100):
    return nonsequential_recommend(interactions, matrix_factorization_item_factors, top_k)

def lightgcn_recommend(interactions:list[Interaction], top_k=100):
    return nonsequential_recommend(interactions, lightgcn_item_embeddings, top_k)


def two_tower_recommend(interactions:list[Interaction], top_k=100):
    return nonsequential_recommend(interactions, two_tower_item_embeddings, top_k)


# def sasrec_recommend(interacted_items, top_k=100):
#     return sequential_recommend(
#         interacted_items, 
#         sasrec_model, 
#         max_seq_len=MAX_SEQ_LEN, 
#         pad_id=sasrec_model.pad_id, 
#         is_bert4rec=False, 
#         top_k=top_k
#     )

def bert4rec_recommend(interacted_items, top_k=100):
    return sequential_recommend(
        interacted_items, 
        bert4rec_model, 
        max_seq_len=MAX_SEQ_LEN, 
        pad_id=bert4rec_model.pad_id, 
        is_bert4rec=True, 
        mask_id=bert4rec_model_checkpoint["mask_id"], 
        top_k=top_k
    )

def comirec_recommend(interacted_items, top_k=100):
    return sequential_recommend(
        interacted_items, 
        comirec_model, 
        max_seq_len=MAX_SEQ_LEN, 
        pad_id=comirec_model.pad_id, 
        is_bert4rec=False, 
        top_k=top_k
    )

# SELF TESTING

In [230]:
# Testing candidate generators 
# dump interactions 

final_k = 20

interactions = [
    # Interaction(product_id= 44, interaction_type="cart_add"), # Lotso Plush Toy
    # Interaction(product_id= 280, interaction_type="cart_add"), # Iphone 14 
    # Interaction(product_id= 100, interaction_type="click"), # Mac cosmetic 
    Interaction(product_id= 186, interaction_type="cart_add"), # Iphone 14 
    Interaction(product_id= 187, interaction_type="cart_add"), # Iphone 14 
    Interaction(product_id= 188, interaction_type="cart_add"), # Iphone 14 
    Interaction(product_id= 189, interaction_type="cart_add"), # Iphone 14 
    Interaction(product_id= 190, interaction_type="cart_add"), # Iphone 14 
    Interaction(product_id= 191, interaction_type="cart_add"), # Iphone 14 

]
# matrix factorization recommendations
mf_recommendations_id = mf_recommend(interactions, top_k=50)
mf_recommendations_products = [products_df.loc[products_df['product_id'] == prod_id, 'name'].values[0]
                            for prod_id,score in mf_recommendations_id.items()][:final_k]
# lightgcn recommendations
lightgcn_recommendations_id = lightgcn_recommend(interactions, top_k=50)
lightgcn_recommendations_products = [products_df.loc[products_df['product_id'] == prod_id, 'name'].values[0]
                            for prod_id,score in lightgcn_recommendations_id.items()][:final_k]
# two tower recommendations
two_tower_recommendations_id = two_tower_recommend(interactions, top_k=50)
two_tower_recommendations_products = [products_df.loc[products_df['product_id'] == prod_id, 'name'].values[0]
                            for prod_id,score in two_tower_recommendations_id.items()][:final_k] 

# sasrec recommendations
# sasrec_recommendations_id = sasrec_recommend(interactions, top_k=50)
# sasrec_recommendations_products = [products_df.loc[products_df['product_id'] == prod_id, 'name'].values[0]
#                             for prod_id,score in sasrec_recommendations_id.items()][:final_k]

# bert4rec recommendations
bert4rec_recommendations_id = bert4rec_recommend(interactions, top_k=50)
bert4rec_recommendations_products = [products_df.loc[products_df['product_id'] == prod_id, 'name'].values[0]
                            for prod_id,score in bert4rec_recommendations_id.items()][:final_k]
# comirec recommendations
comirec_recommendations_id = comirec_recommend(interactions, top_k=50)
comirec_recommendations_products = [products_df.loc[products_df['product_id'] == prod_id, 'name'].values[0]
                            for prod_id,score in comirec_recommendations_id.items()][:final_k]



DataFrame({
    # "sasrec_recommendations": sasrec_recommendations_products,
    # "sasrec_scores": [score for prod_id, score in sasrec_recommendations_id.items()][:final_k],
    "bert4rec_recommendations": bert4rec_recommendations_products,
    "bert4rec_scores": [score for prod_id, score in bert4rec_recommendations_id.items()][:final_k], 
    "comirec_recommendations": comirec_recommendations_products,
    "comirec_scores": [score for prod_id, score in comirec_recommendations_id.items()][:final_k]    
})

,bert4rec_recommendations,bert4rec_scores,comirec_recommendations,comirec_scores
0,Apple iPhone 14 Smartphone,10.634661,Xiaomi Mi Smart Watch S1,15.709005
1,Apple Watch Ultra 2 Smartwatch,10.122615,Apple MacBook Air M2 Laptop,15.059644
2,Apple iPad Air M2 Tablet,9.761910,Rolex Submariner Automatic Men Watch,14.008641
3,Apple iPad 11th Generation Tablet,9.454754,Apple iPad Mini 6 Tablet,13.507591
4,Apple Magnetic Battery Pack,8.627844,Apple iPhone 14 Smartphone,13.304179
5,Apple MacBook Air M3 Laptop,7.027974,Apple iPad 10th Generation Tablet,12.835350
6,HP Bluetooth Silent Mouse,6.896679,Disney Stitch Blue Plush Toy,12.561740
7,Apple MacBook Pro 14 Inch M3 Laptop,6.801456,Estee Lauder Lip Gloss Shine,11.976355
8,Dior Beauty Rouge Lipstick Crimson,6.717241,Apple Watch Series 9 Cellular Smartwatch,11.888526
9,Apple Watch Series 8 Smartwatch,6.252708,Sony EA Sports FC 24 PS5 Game Disc,11.804017
10,Apple iPhone 12 Pro Smartphone,6.213426,Apple Watch SE 2nd Generation Smartwatch,11.422621
11,Apple Watch SE 2nd Generation Smartwatch,5.545141,Samsung Galaxy Tab S9 5G,11.326306
12,Apple iPhone 13 Smartphone,5.165833,Samsung Galaxy Tab A9 Tablet,11.229265
13,Samsung Galaxy Watch 5 Pro Smart Watch,5.102157,Samsung Galaxy Watch FE Smartwatch,11.212934
14,Xiaomi Smart Fitness Watch Pro,5.052150,Samsung Galaxy Watch 6 Smartwatch,10.965320
15,Dell Professional Wired Keyboard,4.973253,Samsung Galaxy Tab S9 FE Tablet,10.901553
16,Apple MacBook Air M1 Laptop,4.814903,Apple MacBook Air M1 Laptop,10.668881
17,Samsung Galaxy Watch 6 Classic Smartwatch,4.098488,Omega Constellation Women Watch,10.589433
18,Apple Watch Series 9 GPS Smartwatch,3.803919,Apple iPad Pro 13 Inch Tablet,10.541890
19,Samsung Galaxy Watch FE Smartwatch,3.624030,Samsung Galaxy Z Fold6 512GB Smartphone,9.949059

In [231]:
DataFrame({
    "mf_recommendations": mf_recommendations_products,
    "mf_scores": [score for prod_id, score in mf_recommendations_id.items()][:final_k],
    "lightgcn_recommendations": lightgcn_recommendations_products,
    "lightgcn_scores": [score for prod_id, score in lightgcn_recommendations_id.items()][:final_k], 
    "two_tower_recommendations": two_tower_recommendations_products,
    "two_tower_scores": [score for prod_id, score in two_tower_recommendations_id.items()][:final_k],
})

,mf_recommendations,mf_scores,lightgcn_recommendations,lightgcn_scores,two_tower_recommendations,two_tower_scores
0,Xiaomi Watch S1 Smartwatch,0.052467,Apple Watch Ultra 2 Smartwatch,8.924639,Apple iPhone 13 Smartphone,0.999760
1,Dell Professional Wired Keyboard,0.050808,Apple Watch Series 9 GPS Smartwatch,8.396135,Apple iPad Mini 6 Tablet,0.999753
2,Apple iPhone 12 Pro Smartphone,0.046489,Apple iPad Air M2 Tablet,8.367411,Apple iPhone 14 Smartphone,0.999704
3,Apple Magnetic Battery Pack,0.042203,Apple MacBook Air M3 Laptop,8.348406,Apple Magnetic Battery Pack,0.999697
4,Apple iPad 10th Generation Tablet,0.039763,Apple iPhone 13 Smartphone,8.125824,Apple iPad Air M2 Tablet,0.999534
5,Apple Watch Ultra 2 Smartwatch,0.038833,Apple MacBook Pro 14 Inch M3 Laptop,7.728431,Apple iPad 11th Generation Tablet,0.999511
6,Apple iPad 11th Generation Tablet,0.038046,Apple Watch Series 9 Cellular Smartwatch,7.659643,Apple iPad Pro 13 Inch Tablet,0.999489
7,Apple iPad Mini 6 Tablet,0.037637,Apple MacBook Air M1 Laptop,7.610768,Apple iPhone 12 Pro Smartphone,0.999484
8,Apple iPad Pro 13 Inch Tablet,0.036868,Apple Clear MagSafe Phone Case,7.438286,Apple Clear MagSafe Phone Case,0.998806
9,Apple iPhone 14 Smartphone,0.036143,Apple MacBook Air M2 Laptop,7.436790,Apple iPad 10th Generation Tablet,0.998757
10,Apple iPad Air M2 Tablet,0.034248,Apple iPad Pro 13 Inch Tablet,7.408525,Apple MacBook Air M3 Laptop,0.957766
11,Apple Clear MagSafe Phone Case,0.034240,Apple iPad 10th Generation Tablet,7.373334,Apple MacBook Air M2 Laptop,0.937605
12,Lenovo Precision Optical Mouse,0.032242,Apple iPad 11th Generation Tablet,7.372903,Apple MacBook Pro 14 Inch M3 Laptop,0.935344
13,Apple Watch Series 9 Cellular Smartwatch,0.031417,Apple Magnetic Battery Pack,7.122052,Apple MacBook Air M1 Laptop,0.930089
14,Samsung Galaxy Watch 5 Pro Smart Watch,0.029157,Apple Watch Series 8 Smartwatch,6.995013,Apple Watch Series 9 Cellular Smartwatch,0.860564
15,Dell USB Stereo Desktop Speaker,0.028845,Apple Watch SE 2nd Generation Smartwatch,6.851839,Apple Watch SE 2nd Generation Smartwatch,0.851795
16,Xiaomi POCO X7 5G Smartphone,0.028549,Apple iPhone 12 Pro Smartphone,6.782305,Apple Watch Series 9 GPS Smartwatch,0.848544
17,Samsung Galaxy Watch 6 Classic Smartwatch,0.028032,Apple iPhone 14 Smartphone,6.616918,Apple Watch Ultra 2 Smartwatch,0.824657
18,Samsung Galaxy Watch 4 Smartwatch,0.027917,Apple iPad Mini 6 Tablet,6.174897,Apple Watch Series 8 Smartwatch,0.824451
19,Samsung Galaxy Tab A10 Tablet,0.026640,Dell Professional Wired Keyboard,5.035740,Asus Precision Gaming Mouse,0.635348

# ENDING SELF TESTING

In [232]:
# 23. Build candidate features for one user 

def build_candidate_features_for_user(interacted_items,candidate_top_k=100): 

    candidate_items = set()

    mf_recommend_products = mf_recommend(interacted_items, candidate_top_k)
    lightgcn_recommend_products = lightgcn_recommend(interacted_items, candidate_top_k)
    # sasrec_recommend_products = sasrec_recommend(interacted_items, candidate_top_k)
    bert4rec_recommend_products = bert4rec_recommend(interacted_items, candidate_top_k)
    comirec_recommend_products = comirec_recommend(interacted_items, candidate_top_k)
    two_tower_recommend_products = two_tower_recommend(interacted_items, candidate_top_k)

    candidate_items.update(mf_recommend_products.keys())
    candidate_items.update(lightgcn_recommend_products.keys())
    # candidate_items.update(sasrec_recommend_products.keys())
    candidate_items.update(bert4rec_recommend_products.keys())
    candidate_items.update(comirec_recommend_products.keys())
    candidate_items.update(two_tower_recommend_products.keys())

    candidate_items = list(candidate_items)


    candidate_df = pd.DataFrame({
        'user_id': [0] * len(candidate_items),
        'product_id': candidate_items
    })
    
    candidate_df['mf_score'] = candidate_df['product_id'].map(mf_recommend_products).fillna(0)
    candidate_df['lightgcn_score'] = candidate_df['product_id'].map(lightgcn_recommend_products).fillna(0)
    candidate_df['two_tower_score'] = candidate_df['product_id'].map(two_tower_recommend_products).fillna(0)
    # candidate_df['sasrec_score'] = candidate_df['product_id'].map(sasrec_recommend_products).fillna(0)
    candidate_df['bert4rec_score'] = candidate_df['product_id'].map(bert4rec_recommend_products).fillna(0)
    candidate_df['comirec_score'] = candidate_df['product_id'].map(comirec_recommend_products).fillna(0)



    # Add rank features
    candidate_df = add_rank_features(candidate_df,MODEL_SCORE_COLS) 

    # Add statistical features
    candidate_df = candidate_df.merge(item_popularity_df, on='product_id', how='left')
    candidate_df = candidate_df.merge(user_interaction_counts, on='user_id', how='left') 
    candidate_df['item_popularity'] = candidate_df['item_popularity'].fillna(0)
    candidate_df['user_interaction_count'] = candidate_df['user_interaction_count'].fillna(0)

    # Merge Product features
    candidate_df = candidate_df.merge(products_df[PRODUCT_FEATURE_COLS], on='product_id', how='left')

    return candidate_df

In [233]:
# 24. recommend function using XGBoost

def recommend(interacted_items, top_k=10, candidate_top_k=100): 
    candidate_df = build_candidate_features_for_user(interacted_items,candidate_top_k)
    candidate_df["xgb_score"] = pipeline.predict_proba(candidate_df[FEATURE_COLUMNS])[:, 1] 
    top_items_df = candidate_df.sort_values("xgb_score", ascending=False).head(top_k) 
    return top_items_df

In [235]:
interactions = [
    # Interaction(product_id= 44, interaction_type="cart_add"), # Lotso Plush Toy
    # Interaction(product_id= 280, interaction_type="cart_add"), # Iphone 14 
    # Interaction(product_id= 100, interaction_type="click"), # Mac cosmetic 
    Interaction(product_id= 186, interaction_type="cart_add"), # Iphone 14 
    Interaction(product_id= 187, interaction_type="cart_add"), # Iphone 15
    Interaction(product_id= 188, interaction_type="cart_add"), # Iphone 16 
    Interaction(product_id= 189, interaction_type="cart_add"), # Iphone 17 
    Interaction(product_id= 190, interaction_type="cart_add"), # Iphone X 
    Interaction(product_id= 191, interaction_type="cart_add"), # Iphone 8 

]
recommendations_df = recommend(interactions, top_k=60, candidate_top_k=50)
recommendations_df[["product_id","name", "xgb_score"]]

     product_id                                           name  xgb_score
43           90                 HP Multimedia Computer Speaker   0.999960
110         267                        Acer Swift Go 14 Laptop   0.999947
40           87              Lenovo IPS Office Monitor 24 Inch   0.999943
45           92             Sony Desktop Stereo Speaker System   0.999940
34           81                  Acer Slim Multimedia Keyboard   0.999922
31           78                    HP Wireless Office Keyboard   0.999906
44           91                 Lenovo Compact Desktop Speaker   0.999836
109         266                    Asus Zenbook 14 OLED Laptop   0.999782
4            13                    Asus Precision Gaming Mouse   0.999698
107         264                  HP Envy 14 Performance Laptop   0.999693
33           80            Asus RGB Mechanical Gaming Keyboard   0.999666
30           77                Dell UltraSharp 24 Inch Monitor   0.999461
108         265            Lenovo ThinkPad E14 Business Laptop   0.999335
32           79                    Lenovo Compact USB Keyboard   0.999291
102         257                    Apple MacBook Air M2 Laptop   0.999200
3            12                Asus Mechanical Gaming Keyboard   0.998846
92          218          Samsung Galaxy Watch 5 Pro Smartwatch   0.997891
57          114             Clinique Moisture Surge Face Cream   0.997296
36           83                      HP Bluetooth Silent Mouse   0.997153
96          223                  Xiaomi Watch 2 Pro Smartwatch   0.996934
103         258                    Apple MacBook Air M3 Laptop   0.996857
114         285            Pop Mart Loopy Strawberry Plush Toy   0.996793
24           63                  Xiaomi Redmi Smart Watch Lite   0.996544
85          211            Apple Watch Series 9 GPS Smartwatch   0.996395
23           58                 Xiaomi Smart Fitness Watch Pro   0.996049
50          100         MAC Cosmetics Matte Lipstick Retro Red   0.996028
65          140            Seiko Presage Rose Gold Women Watch   0.995490
105         262            Dell Inspiron 15 Performance Laptop   0.995452
68          154                Tissot Junior Classic Kid Watch   0.995437
84          210             Samsung Galaxy Tab S8 Ultra Tablet   0.995003
17           46                   Samsung Galaxy Tab A9 Tablet   0.994903
52          105            Maybelline Fit Me Liquid Foundation   0.993907
5            17                   Under Armour Hoodie With Cap   0.993723
113         282         Pop Mart Lotso Blind Box Plush Pendant   0.993572
64          139                Omega Constellation Women Watch   0.993409
112         278         Disney Lotso Strawberry Bear Plush Toy   0.992680
90          216              Samsung Galaxy Watch 6 Smartwatch   0.991963
89          215                Apple Watch Series 8 Smartwatch   0.991751
7            22        Samsung Galaxy Z Fold6 512GB Smartphone   0.989344
56          113                   Estee Lauder Lip Gloss Shine   0.989234
2            10                         Xiaomi Y68 Smart Watch   0.989107
1             9                       Samsung Galaxy Tab S9 5G   0.983228
76          196             Samsung Galaxy S24 Plus Smartphone   0.982804
12           38            Under Armour Performance Polo Shirt   0.980984
8            26                      Puma Casual Street Hoodie   0.980509
70          158                  Cheetos Crunchy Cheese Snacks   0.980150
49           98             Dior Beauty Rouge Lipstick Crimson   0.977434
25           64        Samsung Galaxy Fit 3 Smart Fitness Band   0.972909
27           69             Sony EA Sports FC 24 PS5 Game Disc   0.965059
115         287                   Disney Stitch Blue Plush Toy   0.961782
111         268           Rolex Submariner Automatic Men Watch   0.946795
97          224                     Xiaomi Mi Watch Smartwatch   0.933002
67          146          Fossil Jacqueline Leather Women Watch   0.922462
99          248  Sony Attack on Titan 2 Final Battle Game Disc   0.893577
9            32                         Nike Sports Polo Shirt   0.864981
48           97          YSL Beauty Velvet Matte Lipstick Ruby   0.863023
61          124              Estee Lauder Refreshing Body Wash   0.860488
59          117               Dior Beauty Hydrating Face Serum   0.840030
42           89                Dell USB Stereo Desktop Speaker   0.824074
35           82                  Dell Wireless Precision Mouse   0.807292

In [236]:
# lightgcn recommendations
lightgcn_recommendations_id = lightgcn_recommend(interactions, top_k=100)
lightgcn_recommendations_products = [products_df.loc[products_df['product_id'] == prod_id, 'name'].values[0]
                            for prod_id,score in lightgcn_recommendations_id.items()][:40]
lightgcn_recommendations_products

['Apple Watch Ultra 2 Smartwatch',
 'Apple Watch Series 9 GPS Smartwatch',
 'Apple iPad Air M2 Tablet',
 'Apple MacBook Air M3 Laptop',
 'Apple iPhone 13 Smartphone',
 'Apple MacBook Pro 14 Inch M3 Laptop',
 'Apple Watch Series 9 Cellular Smartwatch',
 'Apple MacBook Air M1 Laptop',
 'Apple Clear MagSafe Phone Case',
 'Apple MacBook Air M2 Laptop',
 'Apple iPad Pro 13 Inch Tablet',
 'Apple iPad 10th Generation Tablet',
 'Apple iPad 11th Generation Tablet',
 'Apple Magnetic Battery Pack',
 'Apple Watch Series 8 Smartwatch',
 'Apple Watch SE 2nd Generation Smartwatch',
 'Apple iPhone 12 Pro Smartphone',
 'Apple iPhone 14 Smartphone',
 'Apple iPad Mini 6 Tablet',
 'Dell Professional Wired Keyboard',
 'Lenovo Precision Optical Mouse',
 'Lenovo IPS Office Monitor 24 Inch',
 'Dell USB Stereo Desktop Speaker',
 'HP Full HD 22 Inch Monitor',
 'HP Bluetooth Silent Mouse',
 'Lenovo ThinkPad E14 Business Laptop',
 'Xiaomi Smart Fitness Watch Pro',
 'Asus RGB Mechanical Gaming Keyboard',
 'Asus Full HD Gaming Monitor 27 Inch',
 'HP Multimedia Computer Speaker',
 'Dell Inspiron 15 Performance Laptop',
 'Lenovo Compact Desktop Speaker',
 'Acer Office Wireless Mouse',
 'HP Pavilion 15 Everyday Laptop',
 'HP Envy 14 Performance Laptop',
 'Acer Slim Multimedia Keyboard',
 'Xiaomi Watch 2 Pro Smartwatch',
 'Samsung Galaxy Watch 6 Smart Watch',
 'Dell Wireless Precision Mouse',
 'Xiaomi Y68 Smart Watch']

In [ ]:
# 25. Save model 

joblib.dump(pipeline, "xgb_recommender_pipeline.joblib")
print("Model saved to xgb_recommender_pipeline.joblib")

Model saved to xgb_recommender_pipeline.joblib